### PR TITLE
Adds Precompiled headers to build

### PR DESCRIPTION
**Pull request by QuantamHD**
This PR adds some commonly included headers as pre-compiled headers (PCH) it speeds up the build time pretty considerably on my laptop.

It only works on CMake 3.16 so added a few ifdef guards.

### CODE REVIEW

**Review by maliberty — APPROVED** [review]
Great.  I bet there are more places that would benefit.

I would be find to use 3.16 in cmake_minimum_required and drop the ifs.   Ubuntu 20, Centos8, FreeBSD12, and Debian 11 all are 3.16+

**Comment by antonblanchard** [comment]
> I would be find to use 3.16 in cmake_minimum_required and drop the ifs. Ubuntu 20, Centos8, FreeBSD12, and Debian 11 all are 3.16+

Openlane is still CentOS7, but we really should move that and the OpenROAD CI to something newer.

**Comment by maliberty** [comment]
centos7 defaults to cmake 2.8 which we don't support anyways.  You have to install a newer cmake on centos7 today.

**Comment by QuantamHD** [comment]
It's super interesting to me that this fails CI.

**Comment by maliberty** [comment]
> It's super interesting to me that this fails CI.

It is surprising.  It looks just like two tests on certain platforms.

**Comment by maliberty** [comment]
@QuantamHD do you have any further insight on the CI?

**Comment by maliberty** [comment]
@QuantamHD do you plan to look at the failures or close?

**Comment by maliberty** [comment]
Reopen if you plan to work on this

**Pull request closed without merging**
