### PR TITLE
mpl2: improve annealing and debugger

### PR DESCRIPTION
**Pull request by AcKoucher**
When running CI for #4206, gf12/ariane failed in hierarchical macro placement for a specific macro cluster. Some debugging showed that some good results generated when SA temperature is high are being wasted. This PR is to make sure we keep the  lowest cost valid result.

Also, we now know in which annealing step and perturb we are when debugging.

Some small rearrangement and cleaning as well.

### CODE REVIEW

**Comment by AcKoucher** [comment]
Running Secure-CI.

**Review by maliberty — APPROVED** [review]
The code looks fine but I'll hold the merge until the CI results are in

**Comment by AcKoucher** [comment]
CI is showing some failures, but I'll way to dig until #4357 is merged. I think it can have some meaningful impact.

**Comment by AcKoucher** [comment]
Running Secure-CI with updates.

**Comment by maliberty** [comment]
@AcKoucher what the status of this?

**Comment by AcKoucher** [comment]
@maliberty I'm addressing the question in #4206, as it will be easier to not split the answer.

**Pull request closed without merging**
