### PR TITLE
tap: check if edge is filled before inserting endcaps

### PR DESCRIPTION
**Pull request by eder-matheus**
Fix https://github.com/The-OpenROAD-Project/OpenROAD/issues/5720

### CODE REVIEW

**Comment by gadfort** [comment]
@eder-matheus please add a testcase which reflects the issue in the issue so we can continue to test for this condition

**Comment by maliberty** [comment]
The code is fine, please add the requested test.

**Comment by eder-matheus** [comment]
@maliberty @gadfort test added.

**Review by gadfort — APPROVED** [review]
Lgtm

**Pull request merged**
