### PR TITLE
grt: fix wire creation during antenna check

### PR DESCRIPTION
**Pull request by eder-matheus**
Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/3803

### CODE REVIEW

**Comment by eder-matheus** [comment]
@maliberty I still have a crash that only happens sometimes in ant/src/AntennaChecker.cc, which I believe is related to how we create the connections to the pins.

Previously, we were using the virtual paths, leading to another crash. Using a regular path is the best choice, but I'm likely doing something wrong when creating these pin connections. I'll investigate more on what should be done to fix it, but any insights would be appreciated.

**Comment by eder-matheus** [comment]
@maliberty I think this can be reviewed now. It will not fully solve the related issue, but at least if fixes a couple of bugs that I found in the code. I'll start a secure-ci for it as well, and will investigate the remaining issues later.

**Review by maliberty — APPROVED** [review]
you can merge once the CI is passing

**Comment by maliberty** [comment]
@eder-matheus looks ok to me

**Comment by eder-matheus** [comment]
@maliberty FYI, CI is passing now. I have the artifacts for the previous failure in gf180/jpeg that I will continue investigating, but this PR is safe to merge.

**Pull request merged**
