### PR TITLE
Add PDNSim

### PR DESCRIPTION
**Pull request by VidyaChhabria**
Add the analyze_power_grid facility to the OpenROAD app.

### CODE REVIEW

**Comment by VidyaChhabria** [comment]
Just noticed that OpenROAD:openroad and OpenROAD-flow:openroad do not build. Noticed after creating the pull request. Will rerun Jenkins and reopen pull request after the two builds. Confident about PDNSim tests passing.

**Comment by jjcherry56** [comment]
broke my build
CMake Warning (dev) at src/PDNSim/modules/superlu/CMakeLists.txt:11 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.


Process XSDK defaults ...
USE_XSDK_DEFAULTS = 'FALSE'
-- SuperLU will be built as a static library.
-- The Fortran compiler identification is unknown
CMake Error at src/PDNSim/modules/superlu/CMakeLists.txt:62 (enable_language):
  No CMAKE_Fortran_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/Users/cherry/sta/openroad/build/CMakeFiles/CMakeOutput.log".
See also "/Users/cherry/sta/openroad/build/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] Error 1
make: Target `default_target' not remade because of errors.

Compilation exited abnormally with code 2 at Thu Mar  5 13:14:10

**Comment by jjcherry56** [comment]
fortran? are fucking kidding me?

**Comment by tspyrou** [comment]
I didnt notice the fortran. We will look for another solver. In the meantime can you install it?

**Comment by maliberty** [comment]
The library provides a fortran interface - we aren't using it and shouldn't
be compiling it.

**Comment by jjcherry56** [comment]
gee, this only generates 252 compiler warnings (after Matt got around the fortran nonsense)

grep warning ~/tmp/w
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/CBLAS/sgemv.c:153:45: warning: '&&'
      parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/CBLAS/ssymv.c:148:34: warning: '&&'
      parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/CBLAS/dgemv.c:150:44: warning: '&&'
      parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/CBLAS/dsymv.c:148:33: warning: '&&'
      parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/CBLAS/cgemv.c:157:66: warning: '&&'
      parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/CBLAS/chemv.c:156:55: warning: '&&'
      parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/CBLAS/cgerc.c:131:47: warning: '&&'
      parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/CBLAS/cher2.c:155:36: warning: '&&'
      parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/CBLAS/zgemv.c:159:64: warning: '&&'
      parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/CBLAS/zhemv.c:153:53: warning: '&&'
      parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/CBLAS/zgerc.c:133:46: warning: '&&'
      parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/CBLAS/zher2.c:156:35: warning: '&&'
      parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/sgscon.c:103:21: warning: 
      parentheses around left hand side expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/scopy_to_ucol.c:87:21: warning: 
      place parentheses around the assignment to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/scopy_to_ucol.c:90:21: warning: 
      place parentheses around the assignment to silence this warning
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/ssnode_dfs.c:91:22: warning: 
      parentheses around the assignment to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/ssnode_dfs.c:104:21: warning: 
      place parentheses around the assignment to silence this warning
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/ssnode_bmod.c:113:2: warning: 
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/ssnode_bmod.c:114:2: warning: 
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/sreadMM.c:60:8: warning: 
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/sreadMM.c:144:8: warning: add
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/scolumn_dfs.c:139:18: warning: 
      place parentheses around the assignment to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/scolumn_dfs.c:181:24: warning: 
      place parentheses around the assignment to silence this warning
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/scolumn_bmod.c:283:16: warning: 
      place parentheses around the assignment to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/smemory.c:453:14: warning: 
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/sgsisx.c:588:7: warning: 
      parentheses around left hand side expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/dgscon.c:103:21: warning: 
      parentheses around left hand side expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/dcopy_to_ucol.c:87:21: warning: 
      place parentheses around the assignment to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/dcopy_to_ucol.c:90:21: warning: 
      place parentheses around the assignment to silence this warning
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/dsnode_dfs.c:91:22: warning: 
      parentheses around the assignment to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/dsnode_dfs.c:104:21: warning: 
      place parentheses around the assignment to silence this warning
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/dsnode_bmod.c:113:2: warning: 
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/dsnode_bmod.c:114:2: warning: 
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/dreadMM.c:60:8: warning: 
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/dreadMM.c:149:8: warning: add
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/dcolumn_dfs.c:139:18: warning: 
      place parentheses around the assignment to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/dcolumn_dfs.c:181:24: warning: 
      place parentheses around the assignment to silence this warning
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/dcolumn_bmod.c:283:16: warning: 
      place parentheses around the assignment to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/dmemory.c:453:14: warning: 
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/dgsisx.c:588:7: warning: 
      parentheses around left hand side expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/csp_blas2.c:502:27: warning: 
      parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/cgscon.c:102:21: warning: 
      parentheses around left hand side expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/ccopy_to_ucol.c:87:21: warning: 
      place parentheses around the assignment to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/ccopy_to_ucol.c:90:21: warning: 
      place parentheses around the assignment to silence this warning
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/csnode_dfs.c:91:22: warning: 
      parentheses around the assignment to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/csnode_dfs.c:104:21: warning: 
      place parentheses around the assignment to silence this warning
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/csnode_bmod.c:114:2: warning: 
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/csnode_bmod.c:115:2: warning: 
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/creadMM.c:60:8: warning: 
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/creadMM.c:144:8: warning: add
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/ccolumn_dfs.c:139:18: warning: 
      place parentheses around the assignment to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/ccolumn_dfs.c:181:24: warning: 
      place parentheses around the assignment to silence this warning
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/ccolumn_bmod.c:296:16: warning: 
      place parentheses around the assignment to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/cmemory.c:453:14: warning: 
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/cgsisx.c:588:7: warning: 
      parentheses around left hand side expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zsp_blas2.c:502:27: warning: 
      parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zgscon.c:102:21: warning: 
      parentheses around left hand side expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zcopy_to_ucol.c:87:21: warning: 
      place parentheses around the assignment to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zcopy_to_ucol.c:90:21: warning: 
      place parentheses around the assignment to silence this warning
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zsnode_dfs.c:91:22: warning: 
      parentheses around the assignment to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zsnode_dfs.c:104:21: warning: 
      place parentheses around the assignment to silence this warning
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zsnode_bmod.c:114:2: warning: 
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zsnode_bmod.c:115:2: warning: 
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zreadMM.c:60:8: warning: 
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zreadMM.c:149:8: warning: add
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zcolumn_dfs.c:139:18: warning: 
      place parentheses around the assignment to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zcolumn_dfs.c:181:24: warning: 
      place parentheses around the assignment to silence this warning
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zcolumn_bmod.c:298:16: warning: 
      place parentheses around the assignment to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zmemory.c:453:14: warning: 
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/SRC/zgsisx.c:588:7: warning: 
      parentheses around left hand side expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/src/ir_solver.cpp:134:3: warning: 'register' storage
/Users/cherry/sta/openroad/src/PDNSim/src/ir_solver.cpp:134:3: warning: 'register' storage
/Users/cherry/sta/openroad/src/PDNSim/src/ir_solver.cpp:134:3: warning: 'register' storage
3 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/slatms.c:461:37: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/slatms.c:463:43: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/slatms.c:464:11: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/slatms.c:464:50: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/slatms.c:465:11: warning: 
      place parentheses around the '&&' expression to silence this warning
5 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/slaror.c:170:37: warning: 
      place parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/slarot.c:271:33: warning: 
      place parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/dlatms.c:465:37: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/dlatms.c:467:43: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/dlatms.c:468:11: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/dlatms.c:468:50: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/dlatms.c:469:11: warning: 
      place parentheses around the '&&' expression to silence this warning
5 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/dlaror.c:174:37: warning: 
      place parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/dlarot.c:271:33: warning: 
      place parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/csymv.c:121:38: warning: 
      add parentheses around left hand side expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/csymv.c:139:55: warning: 
      place parentheses around the '&&' expression to silence this warning
2 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/clatms.c:493:37: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/clatms.c:495:43: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/clatms.c:496:11: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/clatms.c:496:50: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/clatms.c:497:11: warning: 
      place parentheses around the '&&' expression to silence this warning
5 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/claror.c:191:37: warning: 
      place parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/clarot.c:280:33: warning: 
      place parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/zsymv.c:139:53: warning: 
      place parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/zlatms.c:496:37: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/zlatms.c:498:43: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/zlatms.c:499:11: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/zlatms.c:499:50: warning: 
      place parentheses around the '&&' expression to silence this warning
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/zlatms.c:500:11: warning: 
      place parentheses around the '&&' expression to silence this warning
5 warnings generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/zlaror.c:195:37: warning: 
      place parentheses around the '&&' expression to silence this warning
1 warning generated.
/Users/cherry/sta/openroad/src/PDNSim/modules/superlu/TESTING/MATGEN/zlarot.c:280:33: warning: 
      place parentheses around the '&&' expression to silence this warning
1 warning generated.
CerezaBook> grep warning ~/tmp/w | wc
     252    1210   16789

**Pull request merged**
