### PR TITLE
Cts new clustering

### PR DESCRIPTION
**Pull request by tspyrou**

### CODE REVIEW

**Comment by maliberty** [comment]
@tspyrou How is this different from https://github.com/The-OpenROAD-Project-private/OpenROAD/pull/409 ?

**Comment by tspyrou** [comment]
@maliberty its not different. This is the public PR after labeling. I can't tell from the context if its ready or not.

**Comment by maliberty** [comment]
It's not

**Comment by tspyrou** [comment]
@mathursanjiv and @ravi-varadarajan is this ready to go in or should I close it until it is?

**Comment by mathursanjiv** [comment]
Hi Tom,

We need to merge this in. Shrey is not getting time to come back to it.
Give to 1 more day. I'll review each comment and get back on readiness.

Thanks,
Sanjiv

**Comment by mathursanjiv** [comment]
@tspyrou files are ready to be checked in. However I am getting permission denied during push in this branch.

**Pull request closed without merging**
