### PR TITLE
deltaDebug.py: fewer red lines in editor, no change

### PR DESCRIPTION
**Pull request by oharboe**
no change, just fewer red lines in python editors while wandering through the code.

### CODE REVIEW

**Comment by gadfort** [comment]
@oharboe I think a python lint spec is needed since your "red lines" might be different from "mine" (I'm not disagreeing this PR, just observing).

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
@gadfort do you think we should use the same as OR (https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/.github/workflows/black.yaml)?

**Comment by oharboe** [comment]
> @gadfort do you think we should use the same as OR (https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/.github/workflows/black.yaml)?

I'm confused, aren't we doing that already?

I just fixed some additional line-length issues and re-ran black; slightly stricter than black for some default visual studio config.

Ideally black would just fix everything so we never have to be distracted in IDEs again :-)

**Comment by maliberty** [comment]
I see so the request is for a black settings file?

**Comment by gadfort** [comment]
@maliberty yeah, I didn't realize there was a formatter running since the files don't appear to be formatted

**Comment by maliberty** [comment]
@gadfort what seems unformatted?  I ran black and didn't find anything.

**Comment by gadfort** [comment]
@maliberty I'm mistaken, I was thinking of the test files, but those were formatted.

**Comment by maliberty** [comment]
@oharboe it sounds like your setting in VS are the issue.  The files are all formatted according to black and you wouldn't see any issue with compatible settings.

**Pull request merged**
