### PR TITLE
grt: use route layer above pin layer for connection

### PR DESCRIPTION
**Pull request by eder-matheus**

### CODE REVIEW

**Review by jjcherry56 — APPROVED** [review]

**Comment by rovinski** [comment]
@maliberty FYI the formatting change probably breaks the rc correlation scripts for ORFS

**Comment by jjcherry56** [comment]
@rovinski which illustrates why parsing debugging statement output is a really bad idea

**Comment by rovinski** [comment]
It was a low-cost solution to get correlation working quickly. There's a reason it isn't checked into the repo.

**Comment by jjcherry56** [comment]
I'll sign up for adding support for a real file format to openroad if you spec and parse it.

**Pull request merged**
