### PR TITLE
revert illegal copyright/license in src copied from opensta

### PR DESCRIPTION
**Pull request by jjcherry56**
Signed-off-by: James Cherry <cherry@parallaxsw.com>

### CODE REVIEW

**Review by tspyrou — CHANGES_REQUESTED** [review]
@jjcherry56 can you add a line at the top of each file pointing to where it came from. This is in lieu of using a link it github which would be messy. That way the origin is known.

**Review by oharboe — COMMENTED** [review]
@tspyrou IANAL The copyright pertains to the original works. I thought there was no copyright transfer in OpenROAD. In which case, the copyright for improvements belong to the contributors.

Should the copright statement be amended, removed or left as is?

**Comment by tspyrou** [comment]
@oharboe OpenSTA is under GPL, the rest is under BSD3 and works as you expect.

**Comment by oharboe** [comment]
> @oharboe OpenSTA is under GPL, the rest is under BSD3 and works as you expect.

Yes, but with GPL, there is no copyright transfer done when  the work is extended. So e.g. Linux has many thousands of copyright holders and lots of those copyright holders are estates. It is impossible to change the Linux license, it would require agreement from all copyright holders.

**Comment by QuantamHD** [comment]
OpenROAD is managed under the DCO, and just ensures that the code can be licensed under BSD. Various large orgs have signed the DCO.

You are correct that the change above is not allowed. James Cherry owns OpenSTA outright, and dual licenses it under GPL. He also sells commercial licenses to OpenSTA. He has a CLA in place that licenses new contributions under a permissive license, but he doesn't really accept contributions.

These files were copied from his repo, and thus maintain their GPL status indefinitely or until such a time that James deems the GPL components can be licensed under something else.

**Comment by oharboe** [comment]
> OpenROAD is managed under the DCO, and just ensures that the code can be licensed under BSD. Various large orgs have signed the DCO.
> 
> You are correct that the change above is not allowed. James Cherry owns OpenSTA outright, and dual licenses it under GPL. He also sells commercial licenses to OpenSTA. He has a CLA in place that licenses new contributions under a permissive license, but he doesn't really accept contributions.
> 
> These files were copied from his repo, and thus maintain their GPL status indefinitely or until such a time that James deems the GPL components can be licensed under something else.

I see.

Could you provide a link to the definition of the DCO or how all the copyrights and licensing is handled?

DCO, Developer Certificate of Origin, doesnt sound like an assignment.

**Comment by QuantamHD** [comment]
It's not an assignment https://en.m.wikipedia.org/wiki/Developer_Certificate_of_Origin#:~:text=Instead%20of%20a%20signed%20legal,entry%20introduced%20by%20a%20CLA.

It just ensures that you are licensing your code under BSD. You retain the copyright.

When you contribute code to a GPL file in this repo two things are happening. You are creating a derivative GPL work, and are bound by the GPL to release that derivative work under the GPL license, but you also retain a copyright to those modifications that OpenROAD's DCO asks that you license under BSD. These BSD license are in effect moot, because the GPL is in force and your contributions must be licensed under GPL

If one day all the original GPL copyright holders relicense under a more permissive license your original contributions licensed under BSD come into force, and the entire file can be relicensed under BSD or a combination of the new license and BSD

**Comment by oharboe** [comment]
Thanks!

**Pull request merged**
