### PR TITLE
etc: Take into account tcl multi-lines messages in find_messages and fix new raised errors.

### PR DESCRIPTION
**Pull request by titan73**

### CODE REVIEW

**Review by maliberty — APPROVED** [review]
Thanks.  The regex system isn't perfect at finding all messages but any improvement is appreciated.

**Comment by titan73** [comment]
The checks do no pass due to change in the message id.

This is clear for rsz:
```
*** /home/costa/OpenROAD_/src/rsz/test/repair_wire3.ok	2024-10-24 18:50:22.815081276 +0200
--- /home/costa/OpenROAD_/src/rsz/test/results/repair_wire3-tcl.log	2024-10-24 19:31:13.672892671 +0200
***************
*** 8,14 ****
  [WARNING RSZ-0011] Signal/clock vertical wire resistance is 0.
  [WARNING RSZ-0012] Signal/clock horizontal wire capacitance is 0.
  [WARNING RSZ-0013] Signal/clock vertical wire capacitance is 0.
! [WARNING RSZ-0014] wire capacitance for corner default is zero. Use the set_wire_rc command to set wire resistance and capacitance.
  Driver    length delay
  u2/Z manhtn 1998.8 steiner 1998.8 0.00
  u3/Z manhtn 1.3 steiner 1.3 0.00
--- 8,14 ----
  [WARNING RSZ-0011] Signal/clock vertical wire resistance is 0.
  [WARNING RSZ-0012] Signal/clock horizontal wire capacitance is 0.
  [WARNING RSZ-0013] Signal/clock vertical wire capacitance is 0.
! [WARNING RSZ-0018] wire capacitance for corner default is zero. Use the set_wire_rc command to set wire resistance and capacitance.
  Driver    length delay
  u2/Z manhtn 1998.8 steiner 1998.8 0.00
  u3/Z manhtn 1.3 steiner 1.3 0.00
```
which is easy to fix by updating the ok file.

But for ppl it's weird:
```
*** /home/costa/OpenROAD_/src/rsz/test/repair_wire3.ok	2024-10-24 18:50:22.815081276 +0200
--- /home/costa/OpenROAD_/src/rsz/test/results/repair_wire3-tcl.log	2024-10-24 19:31:13.672892671 +0200
***************
*** 8,14 ****
  [WARNING RSZ-0011] Signal/clock vertical wire resistance is 0.
  [WARNING RSZ-0012] Signal/clock horizontal wire capacitance is 0.
  [WARNING RSZ-0013] Signal/clock vertical wire capacitance is 0.
! [WARNING RSZ-0014] wire capacitance for corner default is zero. Use the set_wire_rc command to set wire resistance and capacitance.
  Driver    length delay
  u2/Z manhtn 1998.8 steiner 1998.8 0.00
  u3/Z manhtn 1.3 steiner 1.3 0.00
--- 8,14 ----
  [WARNING RSZ-0011] Signal/clock vertical wire resistance is 0.
  [WARNING RSZ-0012] Signal/clock horizontal wire capacitance is 0.
  [WARNING RSZ-0013] Signal/clock vertical wire capacitance is 0.
! [WARNING RSZ-0018] wire capacitance for corner default is zero. Use the set_wire_rc command to set wire resistance and capacitance.
  Driver    length delay
  u2/Z manhtn 1998.8 steiner 1998.8 0.00
  u3/Z manhtn 1.3 steiner 1.3 0.00
```
I can add add a new line to the ok file but I don't understand why it does not appear before and appear after the change.

Does anybody has an idea what's going on?

**Comment by maliberty** [comment]
We suppress that message in testing https://github.com/The-OpenROAD-Project/OpenROAD/blob/f8280f5bfe0e945d0973cf8fa7c995ded3490da6/test/helpers.tcl#L210

Usually we suppress messages that have a file path or a time stamp in them as they differ.  I don't see why it is suppress here - perhaps someone changed the code earlier.

**Comment by maliberty** [comment]
I think you could remove that suppression (also in the .py equivalent).  It would be good to audit them if you have time.

**Comment by titan73** [comment]
Ah ok. Thanks. I had the feeling the message was filtered out somewhere but could grep it.
I'll remove this message suppression in another PR. Regarding python I see a file IOPlacer-py.i but I don't see any python code.

**Comment by titan73** [comment]
All checks pass now.

**Comment by maliberty** [comment]
For python I meant helper.py which has similar suppressions as helper.tcl

**Comment by titan73** [comment]
> For python I meant helper.py which has similar suppressions as helper.tcl

Ah ok. I don't see any ref to this file. I can I run tests from python?

**Comment by titan73** [comment]
> > For python I meant helper.py which has similar suppressions as helper.tcl
> 
> Ah ok. I don't see any ref to this file. Is it normal? How can I run tests from python?

Ah found it.

**Pull request merged**
