### PR TITLE
[FR] Ignore OBSes completely outside the die area

### PR DESCRIPTION
**Pull request by ax3ghazy**
This lets FastRoute ignore obstructions that lie completely outside the die area, where no tracks exist anyway. I attached a test case of a design that contains a core ring that is placed outside the die area.  Running the included script produces a segfault on the current version of FastRoute. This commit is one possible way to fix it.

[fastroute_ring_crash.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/5735625/fastroute_ring_crash.tar.gz)

### CODE REVIEW

**Comment by maliberty** [comment]
Please set the merge to branch to openroad rather than master.

**Comment by ax3ghazy** [comment]
@maliberty: I can't see any branches other than `master` and `docs`.

**Comment by maliberty** [comment]
@ax3ghazy sorry I forgot we changed the structure of the public repo branches.

**Comment by maliberty** [comment]
The change seems to appear both here and in your other PR

**Comment by ax3ghazy** [comment]
@maliberty: Sorry about that; seems I had a wrong base branch. I fixed that; the FR changes exist now only here. (cc: @eder-matheus)

**Comment by eder-matheus** [comment]
@ax3ghazy can you add a warning message before the "continue"?

**Comment by ax3ghazy** [comment]
@eder-matheus: Yup, done.

**Review by eder-matheus — APPROVED** [review]

**Comment by maliberty** [comment]
@ax3ghazy please resolve the conflicts and let's get this merged.

**Comment by tspyrou** [comment]
@eder-matheus Please resolve the conflict on the branch I created and merge the PR to that branch. I will handle the merge to master.

**Comment by eder-matheus** [comment]
@tspyrou I've fixed the conflict, but I don't have permission to push to this branch.

**Comment by tspyrou** [comment]
@Eder, I made a copy of the branch in the private project area. Can you push it there and file a PR to master? When it passes i will merge it there and push it public which will automatically close this PR.

**Comment by tspyrou** [comment]
merged from private

**Pull request closed without merging**
