### PR TITLE
Use const references in loop variables to avoid copying.

### PR DESCRIPTION
**Pull request by hzeller**

### CODE REVIEW

**Review by maliberty — APPROVED** [review]
Thanks

**Comment by maliberty** [comment]
If you want to go further, Coverity recently generated
```
** CID 1500205:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/dst/src/BalancerConnection.cc: 202 in dst::BalancerConnection::handle_read(const boost::system::error_code &, unsigned long)()


________________________________________________________________________________________________________
*** CID 1500205:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/dst/src/BalancerConnection.cc: 202 in dst::BalancerConnection::handle_read(const boost::system::error_code &, unsigned long)()
196             pool.join();
197             JobMessage result(JobMessage::SUCCESS);
198             std::string msgStr;
199             unsigned short successBroadcast
200                 = owner_->workers_.size() - failed_workers.size();
201             if (failed_workers.size() > 0) {
>>>     CID 1500205:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type pair.
202               for (auto worker : failed_workers) {
203                 owner_->removeWorker(worker.first, worker.second, false);
204               }
205               logger_->warn(utl::DST,
206                             207,
207                             "{} workers failed to receive the broadcast message "

** CID 1500204:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/sta/search/ClkSkew.cc: 179 in sta::ClkSkews::findWorstClkSkew(const sta::Corner *, const sta::MinMax *)()


________________________________________________________________________________________________________
*** CID 1500204:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/sta/search/ClkSkew.cc: 179 in sta::ClkSkews::findWorstClkSkew(const sta::Corner *, const sta::MinMax *)()
173       for (Clock *clk : *sdc_->clocks())
174         clks.insert(clk);
175       ClkSkewMap skews;
176       findClkSkew(&clks, corner, setup_hold, skews);
177       if (!skews.empty()) {
178         float worst_skew = INF;
>>>     CID 1500204:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type pair.
179         for (auto clk_skew_itr : skews) {
180           ClkSkew *clk_skew = clk_skew_itr.second;
181           float skew = clk_skew->skew();
182           if (skew < worst_skew)
183             worst_skew = skew;
184         }

** CID 1500203:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/sta/search/Search.cc: 879 in sta::Search::visitStartpoints(sta::VertexVisitor *)()


________________________________________________________________________________________________________
*** CID 1500203:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/sta/search/Search.cc: 879 in sta::Search::visitStartpoints(sta::VertexVisitor *)()
873           Vertex *vertex = graph_->pinDrvrVertex(pin);
874           visitor->visit(vertex);
875         }
876       }
877       delete pin_iter;
878     
>>>     CID 1500203:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type pair.
879       for (auto iter : sdc_->inputDelayPinMap()) {
880         const Pin *pin = iter.first;
881         // Already hit these.
882         if (!network_->isTopLevelPort(pin)) {
883           Vertex *vertex = graph_->pinDrvrVertex(pin);
884           if (vertex)

** CID 1500202:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/ant/src/AntennaChecker.cc: 708 in ant::AntennaChecker::gateArea(odb::dbMTerm *)()


________________________________________________________________________________________________________
*** CID 1500202:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/ant/src/AntennaChecker.cc: 708 in ant::AntennaChecker::gateArea(odb::dbMTerm *)()
702       double max_gate_area = 0;
703       if (mterm->hasDefaultAntennaModel()) {
704         dbTechAntennaPinModel* pin_model = mterm->getDefaultAntennaModel();
705         vector<std::pair<double, dbTechLayer*>> gate_areas;
706         pin_model->getGateArea(gate_areas);
707     
>>>     CID 1500202:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type pair.
708         for (auto gate_area_layer : gate_areas) {
709           double gate_area = gate_area_layer.first;
710           max_gate_area = std::max(max_gate_area, gate_area);
711         }
712       }
713       return max_gate_area;

** CID 1500201:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/odb/src/lefin/WidthTableParser.cpp: 68 in odb::WidthTableParser::parse(std::basic_string<char, std::char_traits<char>, std::allocator<char>>)()


________________________________________________________________________________________________________
*** CID 1500201:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/odb/src/lefin/WidthTableParser.cpp: 68 in odb::WidthTableParser::parse(std::basic_string<char, std::char_traits<char>, std::allocator<char>>)()
62     }
63     
64     void WidthTableParser::parse(std::string s)
65     {
66       std::vector<std::string> rules;
67       boost::split(rules, s, boost::is_any_of(";"));
>>>     CID 1500201:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type basic_string.
68       for (auto rule : rules) {
69         boost::algorithm::trim(rule);
70         if (rule.empty())
71           continue;
72         rule += " ; ";
73         if (!parseSubRule(rule))

** CID 1500200:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/sta/parasitics/ConcreteParasitics.cc: 899 in sta::ConcreteParasitics::deleteParasitics()()


________________________________________________________________________________________________________
*** CID 1500200:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/sta/parasitics/ConcreteParasitics.cc: 899 in sta::ConcreteParasitics::deleteParasitics()()
893             delete parasitics[i];
894           delete [] parasitics;
895         }
896       }
897       drvr_parasitic_map_.clear();
898     
>>>     CID 1500200:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type pair.
899       for (auto net_parasitics : parasitic_network_map_) {
900         ConcreteParasiticNetwork **parasitics = net_parasitics.second;
901         if (parasitics) {
902           for (int i = 0; i < ap_count; i++)
903             delete parasitics[i];
904           delete [] parasitics;

** CID 1500199:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/gui/src/search.cpp: 366 in gui::Search::addSNet(odb::dbNet *)()


________________________________________________________________________________________________________
*** CID 1500199:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/gui/src/search.cpp: 366 in gui::Search::addSNet(odb::dbNet *)()
360               points = box->getOct().getPoints();
361             } else {
362               odb::Rect rect = box->getBox();
363               points = rect.getPoints();
364             }
365             Polygon poly;
>>>     CID 1500199:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type Point.
366             for (auto point : points)
367               bg::append(poly.outer(), Point(point.getX(), point.getY()));
368             polygon_shapes_[box->getTechLayer()].insert({bbox, poly, net});
369           }
370         }
371       }

** CID 1500198:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/sta/sdc/WriteSdc.cc: 877 in sta::WriteSdc::writeClockSenses() const()


________________________________________________________________________________________________________
*** CID 1500198:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/sta/sdc/WriteSdc.cc: 877 in sta::WriteSdc::writeClockSenses() const()
871       for (auto iter : sdc_->clk_sense_map_)
872         pin_clks.push_back(iter.first);
873     
874       // Sort by pin/clk pair so regressions results are stable.
875       sort(pin_clks, PinClockPairNameLess(sdc_network_));
876       
>>>     CID 1500198:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type pair.
877       for (auto pin_clk : pin_clks) {
878         ClockSense sense;
879         bool exists;
880         sdc_->clk_sense_map_.findKey(pin_clk, sense, exists);
881         if (exists)
882           writeClockSense(pin_clk, sense);

** CID 1500197:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/odb/src/db/dbPowerDomain.cpp: 215 in odb::dbPowerDomain::getIsolations()()


________________________________________________________________________________________________________
*** CID 1500197:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/odb/src/db/dbPowerDomain.cpp: 215 in odb::dbPowerDomain::getIsolations()()
209     {
210       _dbPowerDomain* obj = (_dbPowerDomain*) this;
211       _dbBlock* par = (_dbBlock*) obj->getOwner();
212     
213       std::vector<dbIsolation*> isolations;
214     
>>>     CID 1500197:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type dbId.
215       for (auto iso : obj->_isolation) {
216         isolations.push_back((dbIsolation*) par->_isolation_tbl->getPtr(iso));
217       }
218     
219       return isolations;
220     }
221     
222     // User Code End dbPowerDomainPublicMethods
223     }  // namespace odb

** CID 1500196:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/dst/src/Distributed.cc: 102 in dst::Distributed::runLoadBalancer(const char *, unsigned short, const char *)()


________________________________________________________________________________________________________
*** CID 1500196:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/dst/src/Distributed.cc: 102 in dst::Distributed::runLoadBalancer(const char *, unsigned short, const char *)()
96                                       const char* workers_domain)
97     {
98       try {
99         asio::io_service io_service;
100         LoadBalancer balancer(this, io_service, logger_, ip, workers_domain, port);
101         if (std::strcmp(workers_domain, "") == 0)
>>>     CID 1500196:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type EndPoint.
102           for (auto worker : end_points_)
103             balancer.addWorker(worker.ip, worker.port);
104         io_service.run();
105       } catch (std::exception& e) {
106         logger_->error(utl::DST, 9, "LoadBalancer error: {}", e.what());
107       }

** CID 1500195:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/sta/liberty/Liberty.cc: 1246 in sta::LibertyCell::findDefaultCondArcs()()


________________________________________________________________________________________________________
*** CID 1500195:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/sta/liberty/Liberty.cc: 1246 in sta::LibertyCell::findDefaultCondArcs()()
1240         inferLatchRoles(debug);
1241     }
1242     
1243     void
1244     LibertyCell::findDefaultCondArcs()
1245     {
>>>     CID 1500195:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type pair.
1246       for (auto port_pair_set : port_timing_arc_set_map_) {
1247         TimingArcSetSeq *sets = port_pair_set.second;
1248         bool has_cond_arcs = false;
1249         for (auto set : *sets) {
1250           if (set->cond()) {
1251            has_cond_arcs = true;

** CID 1500194:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/odb/src/lefin/lefTechLayerCutSpacingTableParser.cpp: 173 in lefTechLayerCutSpacingTable::setNonOppositeEnclosureSpacing(std::vector<boost::fusion::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char>>, double>, std::allocator<boost::fusion::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char>>, double>>>, odb::lefTechLayerCutSpacingTableParser *, odb::lefin *)()


________________________________________________________________________________________________________
*** CID 1500194:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/odb/src/lefin/lefTechLayerCutSpacingTableParser.cpp: 173 in lefTechLayerCutSpacingTable::setNonOppositeEnclosureSpacing(std::vector<boost::fusion::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char>>, double>, std::allocator<boost::fusion::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char>>, double>>>, odb::lefTechLayerCutSpacingTableParser *, odb::lefin *)()
167     void setNonOppositeEnclosureSpacing(
168         std::vector<boost::fusion::vector<std::string, double>> params,
169         odb::lefTechLayerCutSpacingTableParser* parser,
170         odb::lefin* lefin)
171     {
172       parser->curRule->setNonOppositeEnclosureSpacingValid(true);
>>>     CID 1500194:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type vector.
173       for (auto item : params) {
174         auto cls = at_c<0>(item).c_str();
175         auto ext = lefin->dbdist(at_c<1>(item));
176         parser->curRule->addNonOppEncSpacingEntry(cls, ext);
177       }
178     }

** CID 1500193:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/ant/src/AntennaChecker.cc: 1834 in ant::AntennaChecker::diffArea(odb::dbMTerm *)()


________________________________________________________________________________________________________
*** CID 1500193:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/ant/src/AntennaChecker.cc: 1834 in ant::AntennaChecker::diffArea(odb::dbMTerm *)()
1828     
1829     double AntennaChecker::diffArea(dbMTerm* mterm)
1830     {
1831       double max_diff_area = 0.0;
1832       vector<std::pair<double, dbTechLayer*>> diff_areas;
1833       mterm->getDiffArea(diff_areas);
>>>     CID 1500193:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type pair.
1834       for (auto area_layer : diff_areas) {
1835         double diff_area = area_layer.first;
1836         max_diff_area = std::max(max_diff_area, diff_area);
1837       }
1838       return max_diff_area;
1839     }

** CID 1500192:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/drt/src/gc/FlexGC_cut.cpp: 194 in fr::FlexGCWorker::Impl::checkLef58CutSpacingTbl_sameMetal(fr::gcRect *, fr::gcRect *)()


________________________________________________________________________________________________________
*** CID 1500192:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/drt/src/gc/FlexGC_cut.cpp: 194 in fr::FlexGCWorker::Impl::checkLef58CutSpacingTbl_sameMetal(fr::gcRect *, fr::gcRect *)()
188     {
189       box_t qb(point_t(gtl::xl(*viaRect1), gtl::yl(*viaRect1)),
190                point_t(gtl::xh(*viaRect1), gtl::yh(*viaRect1)));
191       vector<rq_box_value_t<gcRect*>> results;
192       auto& workerRegionQuery = getWorkerRegionQuery();
193       workerRegionQuery.queryMaxRectangle(qb, viaRect1->getLayerNum() - 1, results);
>>>     CID 1500192:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type pair.
194       for (auto res : results) {
195         auto metalRect = res.second;
196         if (gtl::intersects(*metalRect, *viaRect1, false))
197           if (gtl::intersects(*metalRect, *viaRect2, false))
198             return true;
199       }

** CID 1500191:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/tap/src/tapcell.cpp: 444 in tap::Tapcell::checkIfFilled(int, int, odb::dbOrientType &, const std::vector<std::vector<int, std::allocator<int>>, std::allocator<std::vector<int, std::allocator<int>>>> &)()


________________________________________________________________________________________________________
*** CID 1500191:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/tap/src/tapcell.cpp: 444 in tap::Tapcell::checkIfFilled(int, int, odb::dbOrientType &, const std::vector<std::vector<int, std::allocator<int>>, std::allocator<std::vector<int, std::allocator<int>>>> &)()
438         x_end = x;
439       } else {
440         x_start = x;
441         x_end = x + width;
442       }
443     
>>>     CID 1500191:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type vector.
444       for (auto placement : row_insts) {
445         if (x_end > placement[0] && x_start < placement[1]) {
446           int left_x = placement[0] - width;
447           int right_x = placement[1];
448           return left_x + right_x > 0;
449         }

** CID 1500190:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/odb/src/db/dbMPin.cpp: 169 in odb::dbMPin::getPinAccess() const()


________________________________________________________________________________________________________
*** CID 1500190:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/odb/src/db/dbMPin.cpp: 169 in odb::dbMPin::getPinAccess() const()
163     std::vector<std::vector<odb::dbAccessPoint*>> dbMPin::getPinAccess() const
164     {
165       _dbMPin* pin = (_dbMPin*) this;
166       // TODO: fix for multi chip block heirarchy
167       _dbBlock* block = (_dbBlock*) getDb()->getChip()->getBlock();
168       std::vector<std::vector<odb::dbAccessPoint*>> result;
>>>     CID 1500190:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type dbVector.
169       for (auto pa : pin->aps_) {
170         result.push_back(std::vector<odb::dbAccessPoint*>());
171         for (auto ap : pa) {
172           result.back().push_back((dbAccessPoint*) block->ap_tbl_->getPtr(ap));
173         }
174       }

** CID 1500189:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/odb/src/db/dbTechLayerCutSpacingTableDefRule.cpp: 975 in odb::dbTechLayerCutSpacingTableDefRule::getPrlEntry(std::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::basic_string<char, std::char_traits<char>, std::allocator<char>>)()


________________________________________________________________________________________________________
*** CID 1500189:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/odb/src/db/dbTechLayerCutSpacingTableDefRule.cpp: 975 in odb::dbTechLayerCutSpacingTableDefRule::getPrlEntry(std::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::basic_string<char, std::char_traits<char>, std::allocator<char>>)()
969     
970     int dbTechLayerCutSpacingTableDefRule::getPrlEntry(std::string cutClass1,
971                                                        std::string cutClass2)
972     {
973       _dbTechLayerCutSpacingTableDefRule* obj
974           = (_dbTechLayerCutSpacingTableDefRule*) this;
>>>     CID 1500189:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type tuple.
975       for (auto entry : obj->prl_tbl_) {
976         std::string class1 = std::get<0>(entry);
977         std::string class2 = std::get<1>(entry);
978         int prl = std::get<2>(entry);
979         if ((class1 == cutClass1 || class1 == "ALL")
980             && (class2 == cutClass2 || class2 == "ALL"))

** CID 1500188:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/odb/src/lefin/lefTechLayerSpacingTablePrlParser.cpp: 125 in lefTechLayerSpacingTablePrl::parse<__gnu_cxx::__normal_iterator<char *, std::basic_string<char, std::char_traits<char>, std::allocator<char>>>>(T1, T1, odb::dbTechLayer *, odb::lefin *, odb::lefTechLayerSpacingTablePrlParser *)()


________________________________________________________________________________________________________
*** CID 1500188:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/odb/src/lefin/lefTechLayerSpacingTablePrlParser.cpp: 125 in lefTechLayerSpacingTablePrl::parse<__gnu_cxx::__normal_iterator<char *, std::basic_string<char, std::char_traits<char>, std::allocator<char>>>>(T1, T1, odb::dbTechLayer *, odb::lefin *, odb::lefTechLayerSpacingTablePrlParser *)()
119     
120       if (!valid)  // fail if we did not get a full match
121         odb::dbTechLayerSpacingTablePrlRule::destroy(rule);
122       else {
123         if (parser->spacing_tbl.size() != parser->width_tbl.size())
124           valid = false;
>>>     CID 1500188:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type vector.
125         for (auto spacing : parser->spacing_tbl)
126           if (spacing.size() != parser->length_tbl.size())
127             valid = false;
128         if (valid) {
129           rule->setTable(parser->width_tbl,
130                          parser->length_tbl,

** CID 1500187:  Memory - corruptions  (OVERRUN)


________________________________________________________________________________________________________
*** CID 1500187:  Memory - corruptions  (OVERRUN)
/src/rcx/src/extRCmodel.cpp: 3568 in rcx::extMetRCTable::addRCw(rcx::extMeasure *)()
3562         }
3563       } else {
3564         n = m->getUnderIndex();
3565         table = _capUnder[m->_met];
3566       }
3567       if (table != NULL)
>>>     CID 1500187:  Memory - corruptions  (OVERRUN)
>>>     Calling "addRCw" with "table->_rcDistTable" and "n" is suspicious because of the very large index, 4294967295. The index may be due to a negative parameter being interpreted as unsigned.
3568         table->addRCw(n, m->_w_nm, m->_tmpRC);
3569     }
3570     void extRCModel::addRC(extMeasure* m) {
3571       if (m->_overUnder) {
3572         uint maxCnt = _modelTable[m->_rIndex]->_capOverUnder[m->_met]->_metCnt;
3573         uint n = getOverUnderIndex(m, maxCnt);

** CID 1500186:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/drt/src/io/io.cpp: 969 in fr::io::Parser::setAccessPoints(odb::dbDatabase *)()


________________________________________________________________________________________________________
*** CID 1500186:  Performance inefficiencies  (AUTO_CAUSES_COPY)
/src/drt/src/io/io.cpp: 969 in fr::io::Parser::setAccessPoints(odb::dbDatabase *)()
963                            term->getName());
964           frUInt4 i = 0;
965           auto& pins = term->getPins();
966           for (auto db_pin : db_pins) {
967             auto& pin = pins[i++];
968             auto db_pas = db_pin->getPinAccess();
>>>     CID 1500186:  Performance inefficiencies  (AUTO_CAUSES_COPY)
>>>     Using the "auto" keyword without an "&" causes the copy of an object of type vector.
969             for (auto db_aps : db_pas) {
970               std::unique_ptr<frPinAccess> pa = make_unique<frPinAccess>();
971               for (auto db_ap : db_aps) {
972                 std::unique_ptr<frAccessPoint> ap = make_unique<frAccessPoint>();
973                 updatefrAccessPoint(db_ap, ap.get(), tech_);
974                 ap_map[db_ap] = ap.get();
```

**Comment by hzeller** [comment]
yes, I'll probably work on this TODO slowly. These are things that can also be found wtih clang-tidy, which might be good to integrate into the CI.
I've done this for other projects, so if desired I can add this to OpenRoad.

Q: should I rund clang-format on the files I changed ? The CI found some [pre-existing format issues](https://github.com/The-OpenROAD-Project/OpenROAD/actions/runs/3371505514/jobs/5593816094), so I could this in this PR while at it.

**Comment by maliberty** [comment]
We are planning to integrate clang-tidy as a CI check.  We're working on getting clang-format going first.

The clang-format is not yet mandatory to merge as we are scheduling the formatting to not generate big merge conflicts with in progress work.  You can skip it for now.  

Shall we merge this PR and you can open others as you make further improvements?

**Comment by hzeller** [comment]
Yes, let's merge now and I'll follow-up with more fixes in separate PRs.

**Pull request merged**
