### PR TITLE
gui: add to sta descriptors

### PR DESCRIPTION
**Pull request by gadfort**
Adds:
- sta::Corner descriptor
- sta::Instance descriptor
- adds fields to the properties in allow access to more information
- add highlighting where possible
- sta::Instance can be slow to load the first time since it needs to get power information, but I think it's worth having access to that, especially when debugging things like clock gating power @QuantamHD (the added loading time is also why I think it makes sense to keep it separate the DB descriptor).

Discussion:
- I don't like the names I've chosen for `STA Instance` and `DB ???`, so I'm open to suggestions for what to rename those to make it better

### CODE REVIEW

**Comment by maliberty** [comment]
Why not just put the timing data on dbInst?  The split between db and sta is mostly relevant to developers and not users.

**Comment by maliberty** [comment]
I'm glad I lured you into adding more timing descriptors :)

**Comment by gadfort** [comment]
@maliberty because the STA instance takes time to load, I think it makes sense to separate it out (on a large design is can be a long time for STA to compute the information so it would be annoying (I think) to force that on the dbInst descriptor. But we could "rename" the STA instance descriptor to something like "Timing/Power"?

**Comment by gadfort** [comment]
@maliberty I added a clock descriptor and added some handling of port busses as well

**Comment by maliberty** [comment]
The code looks good.  Thanks for filling in the highlighting.

If the timing/power is going to take time then we should have some indication (eg wait cursor) that processing is happening.

**Comment by maliberty** [comment]
Do you have an example of what the timing/power inspector looks like?

**Comment by gadfort** [comment]
@maliberty 
image

I think the power activity formatting could use some work.
The setup and hold times are actually arrival times, so I'm open to rename them, if you have any suggestions.
Additionally, if there are other information that would be accessible that is useful I can add it now (if you have something in mind). This was largely done to take a look at the clockgating power activities.

**Comment by gadfort** [comment]
@maliberty I added a wait cursor to the data loading in the inspector

**Comment by maliberty** [comment]
I think we can skip activity on power/ground pins.  I think we should suppress "INF ps"/"-INF ps" or replace them with "None"

How about "Max arrival times" for "Setup times" and min for hold?  If it is an timing endpoint you could add the actual setup/hold times separately where applicable.

**Comment by maliberty** [comment]
It also too many digits, eg "50.0000%".  Two is the default in sta_report_default_digits

**Comment by gadfort** [comment]
@maliberty 
image

This is what it looks like now + a segfault fix on internal ports.

**Comment by maliberty** [comment]
Much nicer.  I gave 50.0000% as an example but I really mean all the values in the form not just the percentage.

**Comment by gadfort** [comment]
> Much nicer. I gave 50.0000% as an example but I really mean all the values in the form not just the percentage.

image

How about now?

**Review by maliberty — APPROVED** [review]

**Comment by rovinski** [comment]
Maybe `0.00% at 0 aHz from constant` could just be `constant`

**Pull request merged**
