### PR TITLE
pdn: ensure adjustment to min area is rounded up

### PR DESCRIPTION
**Pull request by gadfort**
@eder-matheus please check if this resolves the min-area issue you saw. I was able to trigger an issue with the new test, but please check on the test you showed me

Fixes: min area getting rounded down causing a min area violation

### CODE REVIEW

**Comment by rovinski** [comment]
If the whole lef file needed for the test case?

**Comment by gadfort** [comment]
@rovinski I'll see, it would be nice to not need it (I was just being a little lazy and copying it forward)

**Comment by maliberty** [comment]
@eder-matheus you should do a squash commit if it is removed to eliminate it from the history (or @gadfort could rebase/squash/force push)

**Comment by gadfort** [comment]
@maliberty I just forced pushed to remove it and replace it with a call to setArea on metal6 (much nicer solution). Thanks @rovinski

**Pull request merged**
