### PR TITLE
Move install of gtest to DependencyInstaller.sh.

### PR DESCRIPTION
**Pull request by titan73**
For https://github.com/The-OpenROAD-Project/OpenROAD/issues/5530.

Tested with clean build and make test.

### CODE REVIEW

**Comment by QuantamHD** [comment]
Yeah. I'm personally opposed to this. Sorry I forgot to respond to your original issue, but pull the system GTest is exactly what we want to avoid. Most of the time Gtest is just directly included in a repo this is a nicer alternative to committing the files to the repo.

This is just generally the way Gtest asks you to install into your repo. https://github.com/google/googletest/blob/main/googletest/README.md#build-with-cmake
image

I understand your company has firewall rules that's blocking this stuff, and I think a better approach for you is to be able to override the URL to a local file. We could dependency install a tar file somewhere on the system and then point Fetch content at that, but I just fear a super super old version of gtest that just happens to be installed on someones machine.

**Comment by titan73** [comment]
@QuantamHD I don't know what you mean by "pulling the system GTest". I do exactly things the same way as in DependencyInstaller.sh.

Who are the "we" in "what we want to avoid"?

AFAIK:
- OpenSTA and abc are submodules
- DependencyInstaller.sh manages over 20 dependencies
- Gtest is the single dependency manage by the build system

So can you explain why Gtest have an exception?

I noticed cudd has been recently added into DependencyInstaller.sh. Why not integrated into the build system as got gtest?

**Comment by QuantamHD** [comment]
By the system GTest I mean the version the user happened to install.

We is in general the project, but I don't speak for everyone. What I worry about is getting a really old version of Gtest where the tests don't work because the user has an out of date version of Gtest. Gtest in particular is finicky about versions and changes frequently which is why most projects just include it in their build tree. 

If we can avoid relying on a system dependency that's more ideal since we build it in tree rather than relying on something on the system. Ideally we could just build and statically link our transitive dependency closure from source and do away with dependency installer entirely. But for now every dependency that doesn't have to be in the dependency installer is one less platform issue we run into.

**Comment by QuantamHD** [comment]
I'm totally fine if you want to download the gtest zip file somewhere on the system from the dependency installer and point fetch content at that file. It achieves the same thing as pulling it from github.

**Comment by titan73** [comment]
I clearly understand that we want to use our own installed version of gtest (1.13.0) and not the system one installed with apt. The PR does this and I tested version 1.13.0 is used whatever the system one is installed or not. But indeed it is installed in /usr/local. If /usr/local should be avoided, all the prefixes in deps installer should be modfied to a local directory then.

**Comment by maliberty** [comment]
We assume that we can install to /usr/local so I don't see this as an issue.  We do allow a prefix to be specified for those that need it.

**Comment by QuantamHD** [comment]
This PR is fine. I personally dislike /usr/local install stuff and would happily remove it all if we could, but that's a personal issue, and if this helps you use OpenROAD we should move ahead with it.

**Comment by titan73** [comment]
Rebasing.
clang-tidy-review fails because the CI is not update with new deps.
I guess the 2 builds too although oddly the details show all steps green.

**Comment by titan73** [comment]
Is there anything more to do in this PR?
The CI needs to be updated to make the checks pass. I don't know how to do it.

**Review by vvbandeira — APPROVED** [review]

**Pull request merged**
