### PR TITLE
Update new tool patch

### PR DESCRIPTION
**Pull request by Aidan-McNay**
I updated ./docs/misc/AddTool.patch. The previous version was outdated, and resulted in lots of hunks being lost when patching. This one should be revised so that the new tool works right after patching.

### CODE REVIEW

**Review by maliberty — APPROVED** [review]
Just curious - are you trying to add a new tool?

**Comment by Aidan-McNay** [comment]
Yes! Working with @rovinski to develop a tool to visualize the clock tree with the GUI, allowing users to possibly better visualize timing errors

**Comment by maliberty** [comment]
Great!  I think it would be good to have a sense of how you plan to implement this so we have up front agreement on the architecture.  It isn't clear to me that it needs to be a new tool.

**Comment by rovinski** [comment]
Yep, totally fair. I was just giving @Aidan-McNay a good starting point to get new code running in OpenROAD. As we get closer to getting some of the base functionality in, we can talk more about architecture.

**Pull request merged**
