### PR TITLE
grt:not rerouting simple vertical or horizontal edges on FastRouteCore::fixOverlappingEdge

### PR DESCRIPTION
**Pull request by arthurjolo**
Signed-off-by: arthur <arthurjolo@gmail.com>
Fixes [1639](https://github.com/The-OpenROAD-Project/OpenLane/issues/1639)

At FastRouteCore::fixOverlappingEdge, when trying to reroute simple vertical or horizontal, the function routeLShape wasn't updating the edges grids, X and Y, correctly. For example at the Net net83 the edge 74 of the example
Edge grid (x,y) before fixEmbeddedTrees:
edge_antes

Edge grid (x,y) after fixEmbeddedTrees:
edge-depois_errada

This correction doesn't allow this types of edges to be rerouted, and prevent the error on the edges grid 

example:
[example.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/10701200/example.zip)

### CODE REVIEW

**Comment by maliberty** [comment]
If the attached example is small enough it can be turned into a unit test.

**Comment by arthurjolo** [comment]
The DEF file has 5MB, is it ok?

**Comment by maliberty** [comment]
That a bit big.  Perhaps you can use https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/etc/deltaDebug.py to reduce it while keeping the interesting behavior.

**Comment by maliberty** [comment]
I'm ok to take the test in a follow on PR.  Please work with @eder-matheus to run a secure CI for this change.

**Comment by eder-matheus** [comment]
@arthurjolo @maliberty I've created a secure- branch for this PR now. When it finishes, I will approve the PR.

**Review by eder-matheus — APPROVED** [review]

**Comment by maliberty** [comment]
Why is this reopened?

**Comment by maliberty** [comment]
nvm I see it wasn't actually merged yet

**Comment by arthurjolo** [comment]
I just accidentally closed the PR, so I  reopened it

**Pull request merged**
