### PR TITLE
Fix finding the clocks of the cells after scan replace and rollback

### PR DESCRIPTION
**Pull request by fgaray**
I found this bug while implementing scan stitching. The unit tests for this part will in the PR for scan stitching

### CODE REVIEW

**Comment by maliberty** [comment]
I curious why this is required.  Sta should be listening for db callbacks and handling this automatically.  What problem did you observe?

**Comment by fgaray** [comment]
Hi Matt,

The problem is that when I call Sta::clocks, I get an empty ClockSet after rollback, that is: I am unable to find the driving clock for the cell when I revert back from the scan cell to a non-scan one.

I agree that STA should be listening to changes, so maybe it is a bug with one of the observers?

I can provide a quick test case if you want to take a look, but adding this line solved the issue that I was seeing.

**Comment by maliberty** [comment]
I wonder if ensureClkNetwork() would be better.  I'm afraid your approach might have performance implications.

**Comment by fgaray** [comment]
I tried sta_->ensureClkNetwork() but doesn't seems to fix the issue. I wonder if there is another function that it is being called by networkChanged that is making the difference.

How big is the performance implication?, in total I should be calling networkChanged 3 times: 2 for preview_dft and 1 for insert_dft.

**Comment by fgaray** [comment]
Ok, so I commented search_->clear() and now calling networkChanged is NOT fixing the issue.

So I guess there is some observer that is not updating search_ in STA?

**Comment by maliberty** [comment]
I'm ok to merge this as is and we can sort it out later if it proves to be an issue.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
