### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by dralabeing**
Adopting the contributor covenant as The Code of Conduct for OpenROAD

### CODE REVIEW

**Comment by maliberty** [comment]
The branch for this PR should have been created in a fork of this repo.

**Comment by dralabeing** [comment]
Matt, I realized this.. Should I close this and create another one from a fork?

Also, we are using the default Contributor covenant for now since we will need a lawyer to review a non-standard one.

thanks

**Review by tspyrou — APPROVED** [review]

**Comment by maliberty** [comment]
@dralabeing it is ok as I just deleted your branch now that it is merged, just use a fork in the future.

**Comment by dralabeing** [comment]
@maliberty  got it...will do so...thank you

**Pull request merged**
