### PR TITLE
rsz: dont touch special nets

### PR DESCRIPTION
**Pull request by gadfort**
Changes:
- dont touch special nets in resizer, during eliminate_dead_logic the power nets get deleted without this.

### CODE REVIEW

**Comment by gadfort** [comment]
@QuantamHD there are plenty of cases were we want to be able to delete and modify special nets, but resizer is not one of those tools

**Comment by QuantamHD** [comment]
You know what we should have... https://man.openbsd.org/pledge.2

We should add something to ODB that let's us pledge away certain thing like deleting special nets in resizer. Then remove the pledges once rsz is done.

**Comment by gadfort** [comment]
@QuantamHD I think that is beyond the scope of this PR. I would suggest creating an issue since that would be a larger task

**Comment by maliberty** [comment]
This sounds like a bug in eliminate dead logic.  The power nets shouldn't be fully disconnected and so shouldn't be deleted.  I'm wondering if this fixes a symptom.  @povik please comment.

**Comment by povik** [comment]
@maliberty Yes, I think the root cause is eliminate_dead_logic ignoring pins if their direction is none of input, output, tristate, bidirectional, but there are also directions ground/power. I can write a fix later.

Not sure if we want to conflate special nets with dont touch for the following reason: if I remember right if an instance is connected to a dont touch net on any pin, that instance cannot be changed (other than maybe sizing?), special nets don't have the same restriction

**Comment by gadfort** [comment]
Closed in favor of: #6314

**Pull request closed without merging**
