### PR TITLE
fix  #3563: Handle top level port with no net connected to it

### LINKED ISSUE #3563: repairDesign dumps core when buffering net connected to IO pad (output on core-side) and SRAM macro (input)
### Describe the bug

I have two similar test cases:
A non-clock net is connected to the core side output of an IO pad, and to an input of an SRAM macro. Additionally, the net has fan-out to a set of registers. I have two testcases for OpenROAD to dump core, one within the `resizer.tcl` script, one within the `gpl.tcl` script. Based on the logs, I assume both test cases to have the same root cause, so I'm filing this as one issue only.

**Testcase 1 (resizer):**
With only a few registers connected (two flops), the `resizer.tcl` script will dump core during `repairDesign`.

**Testcase 2 (gpl):**
With more registers connected (162 flops), even the `gpl.tcl` script will dump core during `repairDesign`.

**Workaround**
As a work-around, I have to manually add a buffer after the core-side output of the IO pad cell, and set the net between IO pad cell and buffer as `dont_touch`. OpenROAD will then create more buffers after output of the manually inserted buffer.

For both test cases, I have additionally attached an ipython notebook for Google Colab to reproduce the issue.

/cc @proppy 
/cc @dhaentz1

### Expected Behavior

OpenROAD should buffer the net connected to the core-side output of the IO pad.

### OpenROAD Environment

```shell
Env.sh seems not to be included in my litex-hub package - please use the testcase notebook to extract data.
```

### OpenLane Environment

```shell
env.py seems to be broken in my setup - please use the testcase notebook to extract data.
```

### To Reproduce

**Testcase 1 (resizer):**
[_build.coredump_resizer.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/11934005/_build.coredump_resizer.zip)
[OpenRoad__coredump_when_resizing_net_driven_by_pad_and_connected_to_sram_macro.ipynb.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/11934022/OpenRoad__coredump_when_resizing_net_driven_by_pad_and_connected_to_sram_macro.ipynb.gz)

**Testcase 2 (gpl):**
[_build.coredump_gpl.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/11934011/_build.coredump_gpl.zip)
[OpenRoad__coredump_when_global_placing_highfanout_net_driven_by_pad_and_connected_to_sram_macro.ipynb.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/11934027/OpenRoad__coredump_when_global_placing_highfanout_net_driven_by_pad_and_connected_to_sram_macro.ipynb.gz)

### Relevant log output

```shell
**Testcase 1 (resizer):**
[INFO]: Setting RC values...
[INFO RSZ-0058] Using max wire length 6781um.
Signal 11 received
Stack trace:
 0# 0x0000000000B9BB0B in openroad
 1# 0x00007F7E3FF54090 in /lib/x86_64-linux-gnu/libc.so.6
 2# odb::dbNet::getITerms() in openroad
 3# sta::dbNetwork::visitConnectedPins(sta::Net const*, sta::PinVisitor&, sta::NetSet&) const in openroad
 4# sta::Network::connectedPinIterator(sta::Net const*) const in openroad
 5# rsz::RepairDesign::hasInputPort(sta::Net const*) in openroad
 6# rsz::RepairDesign::makeRepeater(char const*, int, int, sta::LibertyCell*, bool, int, sta::Vector<sta::Pin const*>&, float&, float&, float&, sta::Net*&, sta::Pin*&, sta::Pin*&) in openroad
 7# rsz::RepairDesign::makeFanoutRepeater(sta::Vector<sta::Pin const*>&, sta::Vector<sta::Pin const*>&, odb::Rect, odb::Point, bool, bool, int, bool) in openroad
 8# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
 9# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
10# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
11# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
12# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
13# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
14# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
15# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
16# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
17# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
18# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
19# rsz::RepairDesign::repairNet(sta::Net*, sta::Pin const*, sta::Vertex*, bool, bool, bool, int, bool, int&, int&, int&, int&, int&) in openroad
20# rsz::RepairDesign::repairDesign(double, double, double, int&, int&, int&, int&, int&) in openroad
21# rsz::RepairDesign::repairDesign(double, double, double) in openroad
22# 0x0000000000CD5341 in openroad
23# TclNRRunCallbacks in /content/eda/bin/../lib/libtcl8.6.so
24# 0x00007F7E41A741BF in /content/eda/bin/../lib/libtcl8.6.so
25# Tcl_EvalEx in /content/eda/bin/../lib/libtcl8.6.so
26# Tcl_Eval in /content/eda/bin/../lib/libtcl8.6.so
27# sta::sourceTclFile(char const*, bool, bool, Tcl_Interp*) in openroad
28# ord::tclAppInit(Tcl_Interp*) in openroad
29# Tcl_MainEx in /content/eda/bin/../lib/libtcl8.6.so
30# main in openroad
31# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
32# 0x0000000000B85E22 in openroad



**Testcase 2 (gpl):**
[INFO]: Setting RC values...
[INFO RSZ-0058] Using max wire length 6781um.
Signal 11 received
Stack trace:
 0# 0x0000000000B9BB0B in openroad
 1# 0x00007F7E3FF54090 in /lib/x86_64-linux-gnu/libc.so.6
 2# odb::dbNet::getITerms() in openroad
 3# sta::dbNetwork::visitConnectedPins(sta::Net const*, sta::PinVisitor&, sta::NetSet&) const in openroad
 4# sta::Network::connectedPinIterator(sta::Net const*) const in openroad
 5# rsz::RepairDesign::hasInputPort(sta::Net const*) in openroad
 6# rsz::RepairDesign::makeRepeater(char const*, int, int, sta::LibertyCell*, bool, int, sta::Vector<sta::Pin const*>&, float&, float&, float&, sta::Net*&, sta::Pin*&, sta::Pin*&) in openroad
 7# rsz::RepairDesign::makeFanoutRepeater(sta::Vector<sta::Pin const*>&, sta::Vector<sta::Pin const*>&, odb::Rect, odb::Point, bool, bool, int, bool) in openroad
 8# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
 9# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
10# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
11# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
12# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
13# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
14# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
15# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
16# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
17# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
18# rsz::RepairDesign::makeRegionRepeaters(rsz::LoadRegion&, int, int, sta::Pin const*, bool, bool, int, bool) in openroad
19# rsz::RepairDesign::repairNet(sta::Net*, sta::Pin const*, sta::Vertex*, bool, bool, bool, int, bool, int&, int&, int&, int&, int&) in openroad
20# rsz::RepairDesign::repairDesign(double, double, double, int&, int&, int&, int&, int&) in openroad
21# rsz::RepairDesign::repairDesign(double, double, double) in openroad
22# 0x0000000000CD5341 in openroad
23# TclNRRunCallbacks in /content/eda/bin/../lib/libtcl8.6.so
24# 0x00007F7E41A741BF in /content/eda/bin/../lib/libtcl8.6.so
25# Tcl_EvalEx in /content/eda/bin/../lib/libtcl8.6.so
26# Tcl_Eval in /content/eda/bin/../lib/libtcl8.6.so
27# sta::sourceTclFile(char const*, bool, bool, Tcl_Interp*) in openroad
28# ord::tclAppInit(Tcl_Interp*) in openroad
29# Tcl_MainEx in /content/eda/bin/../lib/libtcl8.6.so
30# main in openroad
31# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
32# 0x0000000000B85E22 in openroad
```

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by openroadie**
fixes #3563

### CODE REVIEW

**Comment by maliberty** [comment]
How can you have a top level port without a net connected to it?  dbBTerm::create requires a non-null net.

**Comment by openroadie** [comment]
> How can you have a top level port without a net connected to it? dbBTerm::create requires a non-null net.

I do not have an answer to this question. I do have a loop where I am encountering this situation (see the code change). Maybe this issue should be looked at by somebody who is an odb expert?

**Comment by maliberty** [comment]
Which test case shows this and what is the port in question?

**Comment by openroadie** [comment]
https://github.com/The-OpenROAD-Project/OpenROAD/issues/3563

**Comment by maliberty** [comment]
You didn't specify which of the test cases to look at.  I looked at the first and I don't see anything related to bterms at all.  It is failing due to the logic in RepairDesign::makeRegionRepeaters:
```
    if (repeater_loads.size() >= max_fanout / 2)
```
where you have 0 >= 1/2 which makes little sense to buffer.

**Comment by openroadie** [comment]
Sorry @maliberty .... it was not clear to me from your question that you wanted to know which of the two tests I was using.

**Comment by maliberty** [comment]
Does this PR relate to the other test case?

**Comment by openroadie** [comment]
> Does this PR relate to the other test case?

There are two tests. One for resizer and another for gpl. This PR relates to the resizer test. Let me take a look at your earlier comment about invalid comparisons in the buffer insertion code and update this PR as needed.

**Comment by openroadie** [comment]
@maliberty Addressed your comment. Thanks for the help.

**Comment by openroadie** [comment]
@maliberty This PR is ready unless you have additional feedback.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
