### PR TITLE
psm: add sources from pads

### PR DESCRIPTION
**Pull request by gadfort**
Changes:
- add sources from pads to the power grid to enable wirebond IR drop

### CODE REVIEW

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
I looked at zerosoc and I still see what look like the signs of bumps despite the pads:
image

**Comment by gadfort** [comment]
image
@maliberty this is what I get when I run the rest (no appearance of the bumps)

**Comment by maliberty** [comment]
It would be nice if the heatmap defaulted to the lowest populated layer.  Here it defaults to li1 which has no data and confusingly seems like a no-op.

**Comment by maliberty** [comment]
An aside - this def is odd in that the tie cells are not placed that close to the pads:
image

**Comment by gadfort** [comment]
@maliberty the smooth ness would be nice to find a good solution for.  I think we could default to something different (maybe), just depends on how and when the default it chosen.
As for tiecells, we aren't doing anything special here, so this is how OR chose to place them (and I agree that does look a little less ideal). Maybe they are connected to multiple things and that is causing them to move around? Might be worth investigating since this will cause a lot of extra routing.

**Comment by maliberty** [comment]
At least that one tie I looked at had only a single connection.  Do you have a test case for gpl for this design?

**Pull request merged**
