### PR TITLE
grt: fix congestion information in the last col/row of global routing grid

### PR DESCRIPTION
**Pull request by eder-matheus**
Address comments about routing congestion heatmap on https://github.com/The-OpenROAD-Project/OpenROAD/discussions/3953.

### CODE REVIEW

**Comment by eder-matheus** [comment]
@maliberty I expect small changes in the final global routing. I've started a secure-ci to make sure nothing will break.

**Comment by eder-matheus** [comment]
@AcKoucher FYI.

**Comment by maliberty** [comment]
Would you summarize what the issue is and why all the iteration ranges have changed.

**Comment by eder-matheus** [comment]
> Would you summarize what the issue is and why all the iteration ranges have changed.

The issue is that we are not calculating the resource adjustments defined by the users in the last row and column of the global routing grid. My update is to add this information to the last col/row.

But I just noticed that I don't need all these updates in the iteration ranges. It should be only applied to the functions related to the congestion map.

**Comment by eder-matheus** [comment]
Secure-ci is green, but I have a congestion error in sky130hd/aes. I'm looking into it right now.

**Comment by maliberty** [comment]
> Secure-ci is green, but I have a congestion error in sky130hd/aes. I'm looking into it right now.

any update?

**Comment by eder-matheus** [comment]
> > Secure-ci is green, but I have a congestion error in sky130hd/aes. I'm looking into it right now.
> 
> any update?

The fix for the congestion issue is in this PR: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1457.

Also, this update is fixing the resources on the last col/row of the global routing grid, not only for the congestion heatmap but for the actual global routing. Secure-ci was green before, but I started another run now.

**Comment by eder-matheus** [comment]
@maliberty I forgot to ping you here, but this is ready to merge. Should I address the clang-tidy comments about `int16_t`/`uint16_t`?

**Comment by maliberty** [comment]
> @maliberty I forgot to ping you here, but this is ready to merge. Should I address the clang-tidy comments about `int16_t`/`uint16_t`?

The problem is pervasive in this code so we should clean it up in one pass later.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
