### PR TITLE
etc: Add option to disable certificate checks

### PR DESCRIPTION
**Pull request by titan73**
Every now and then I get issue with certificates so add an option to workaround it.
"eval" is added before wget as alias are expanded when reading the commands and not executed.

### CODE REVIEW

**Review by maliberty — APPROVED** [review]

**Comment by rovinski** [comment]
Seems rather dangerous from a security perspective...

**Comment by maliberty** [comment]
> Seems rather dangerous from a security perspective...

Its only for use by user opt-in.  OR will never use it by default or in the CI.

**Comment by rovinski** [comment]
Yeah, I mean even from a user standpoint. If someone is having this problem then they should figure out the issue themselves. They could be victim of a MITM attack.

**Comment by maliberty** [comment]
@titan73 can you describe the problem further?

**Comment by titan73** [comment]
An example of error:
```
--2024-09-08 12:08:01--  https://cmake.org/files/v3.24/cmake-3.24.2-linux-x86_64.sh
Resolving cmake.org (cmake.org)... 66.194.253.25
Connecting to cmake.org (cmake.org)|66.194.253.25|:443... connected.
ERROR: cannot verify cmake.org's certificate, issued by ‘CN=Zscaler Intermediate Root CA (zscaler.net) (t)\\ ,OU=Zscaler Inc.,O=Zscaler Inc.,ST=California,C=US’:
  Unable to locally verify the issuer's authority.
To connect to cmake.org insecurely, use `--no-check-certificate'.
```

Zscaler is the firewall which is complaining. This firewall causes a lot of troubles. Nothing to do with any osrt of attacks.

**Comment by rovinski** [comment]
So it is an MITM attack... just one that you intend. There should be a warning attached to this option so that users know that under normal circumstances they should not use it.

**Pull request merged**
