### PR TITLE
Check compiler version in CMake

### PR DESCRIPTION
**Pull request by vvbandeira**
Make it more clear deps.

Ref:
https://github.com/The-OpenROAD-Project/OpenROAD/issues/1049#issuecomment-913715284
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/150

Signed-off-by: Vitor Bandeira <vitor.vbandeira@gmail.com>

### CODE REVIEW

**Comment by rovinski** [comment]
Do we specifically need GCC 8.3? I thought we only needed GCC 7 for the C++14 support.

**Comment by maliberty** [comment]
> Do we specifically need GCC 8.3? I thought we only needed GCC 7 for the C++14 support.

we test with 8.3 so anything older might work but it won't be certain.

**Comment by rovinski** [comment]
> > Do we specifically need GCC 8.3? I thought we only needed GCC 7 for the C++14 support.
> 
> we test with 8.3 so anything older might work but it won't be certain.

But with this PR, it will fatal error on 7 so it definitely won't work.

**Comment by maliberty** [comment]
> But with this PR, it will fatal error on 7 so it definitely won't work.

there are two cases
1) it works on 7 and we are too restrictive
2) it doesn't work on 7 and we get an issue which we won't fix and have to reset the limit to 8

I would rather eliminate 2 than cater to the possibility of 1.    Note that:

GCC has had complete support for C++17 language features since version 8.
[https://en.wikipedia.org/wiki/C%2B%2B17]

**Comment by maliberty** [comment]
Note TR use c++17

**Review by maliberty — APPROVED** [review]

**Comment by rovinski** [comment]
> Note TR use c++17

That was a typo, I meant C++17.

> it doesn't work on 7 and we get an issue which we won't fix and have to reset the limit to 8

That's not what would happen - this case is already covered by `CXX_STANDARD_REQUIRED` afaik. It would really be:

If GCC 7 doesn't cover all of our features and we need 8:
* Users using less than 7 get a nice error message
* Users using 7 get the same error as #1049
* Users using 8+ build successfully

If GCC 7 covers all our features:
* Users build successfully

According to https://gcc.gnu.org/projects/cxx-status.html#cxx17 there is only one C++ feature not completely covered by 7.

**Comment by rovinski** [comment]
I guess I can understand just wanting to be done with it though. I don't see any reason why installing 8 would be harder for anyone than 7.

**Comment by maliberty** [comment]
> I guess I can understand just wanting to be done with it though. I don't see any reason why installing 8 would be harder for anyone than 7.

I don't care that strongly, if you want it to be 7.  Just expect I'll assign you any issues reported against 7 :)

**Comment by vvbandeira** [comment]
@rovinski, just to make sure: should I change to 7 or keep 8.3?

**Comment by jjcherry56** [comment]
I would say the issue has more to do with what OS/tool versions ship with 8 because changing the version if it is not part of the bundled tools is nearly impossible. So my question is what OS versions are we excluding with this change?

**Comment by rovinski** [comment]
From what I can tell from a brief search:

| Distro  | Default compiler | Latest available through package manager |
| ------------- | ------------- | -- |
| CentOS 7  | gcc-4.8.5  | gcc-10.2.1 |
| CentOS 8  | gcc-8.4.1  | gcc-10.2.1 |
| Ubuntu 18 | gcc-7.3.0 | gcc-8 |
| Ubuntu 20 | gcc-9.3.0 | gcc-10 |

Ubuntu 16 and CentOS 6 were EOL'd April / November 2020, respectively so I assume we don't care about those.

**Comment by maliberty** [comment]
From @rovinski analysis I don't see any platform that can't easily use gcc8.  @jjcherry56 / @rovinski  any concerns about merging this as is?

**Comment by jjcherry56** [comment]
Thanks Austin, that looks good to me

**Comment by jjcherry56** [comment]
One more thought is to check with Colin because Arm seems to be in the deep dark ages when it comes to infrastructure versions.

**Comment by vvbandeira** [comment]
I checked with Colin and he has access to newer versions of gcc and clang.

**Pull request merged**
