### PR TITLE
Add pdnsim

### PR DESCRIPTION
**Pull request by VidyaChhabria**
This adds an analyze_power_grid facility to OpenROAD. External dependency on a voltage source location file and a default resistance configuration file for via resistance and per-unit R.

### CODE REVIEW

**Comment by tspyrou** [comment]
I noticed that the pdn sim references a standalone mode in the readme versus the integrated usage. I think it would be good to highlight the integrated usage. What others have done is to eliminate the standalone mode and in the readme point to the integrated version to reduce maintenance.

**Comment by VidyaChhabria** [comment]
I just noticed the failure on bp_fe_top. this morning. 
Error: field droute_viols fails rule 213.0 <= 193.0. I will look into it and update the documentation.

**Comment by rovinski** [comment]
`droute_viols` is the field that @maliberty added to ensure that changes do not cause drastic regressions to the number of DRVs (as detected by TritonRoute).

Does PDNSim actually impact the QoR, or is it just an analysis engine? If it's the latter, that indicates that some other change on the branch is responsible.

**Comment by jjcherry56** [comment]
why is this using a side file to read resistances when they are in the database?
that is not only a pain to maintain but anytime you copy data you are asking for inconsistencies

**Pull request closed without merging**
