### PR TITLE
Opendp pad inst

### PR DESCRIPTION
**Pull request by jjcherry56**

### CODE REVIEW

**Comment by maliberty** [comment]
There is a long standing request to implement this in opendb which I was going to do next week.  The padding needs to be seen by global placement as well so it makes more sense to put it in the db.

**Comment by jjcherry56** [comment]
I don't believe it or any other tool controls belong in the db. global placement can access the values from where they live now.

**Comment by tspyrou** [comment]
I am used to tool control being in a singleton owned by the app as opposed to the db. The singleton is populated as the tcl control commands are read. The singleton should not be owned by a subsystem but rather to app level.

**Comment by jjcherry56** [comment]
The existing api in opendp can be refactored/migrated to OpenRoad.
In the short term there is no reason the public api in opendp cannot be
used to access the padding.

**Pull request merged**
