### PR TITLE
redirect some report commands

### PR DESCRIPTION
**Pull request by gadfort**
Replaces: #6046

Changes:
add redirect to some report_* commands.

### CODE REVIEW

**Comment by gadfort** [comment]
@oharboe FYI

**Comment by gadfort** [comment]
With https://github.com/The-OpenROAD-Project/OpenROAD/pull/6160 this PR is not needed. Unless @oharboe feels strongly about it, I would be fine closing it.

**Comment by maliberty** [comment]
I'm fine as well.

**Comment by oharboe** [comment]
a general tee command seems more tcl idiomatic to me, less surprising...

**Pull request closed without merging**
