### PR TITLE
Cts enhance clkgater handling

### PR DESCRIPTION
**Pull request by arthurjolo**
This PR enhances how clock gater are treated during CTS and it has 2 main changes:

1. Balance gated sinks and non gated sinks. Now the sinks that are gated are treated as a separate sub tree and are later balanced with the non gated sink.
2. Compute the path delays separate from the sta API. This is done to support the clock gaters that are not clock gater cells, but are defined behaviorally by the designer.

### CODE REVIEW

**Comment by arthurjolo** [comment]
It has been throw a secure CI, there are 2 diode count failures on ibex gf180 and sky130hs. The critical failure is a time out on the microwatt design. Other than these all designs are passing.

**Comment by arthurjolo** [comment]
I ran Microwatt loacally and it finished just fine. I am going to create a PR with the metrics update necessaries.

**Comment by arthurjolo** [comment]
Pr with the metric update are were created, microwatt had a slight degradation on finish timing.

**Comment by maliberty** [comment]
@precisionmoon please do that first pass.

**Comment by maliberty** [comment]
Please resolve the clang-tidy

**Comment by arthurjolo** [comment]
> Please resolve the clang-tidy

I had addressed all the clang-tidy suggestions and resolved them, is there any I am missing?

**Comment by maliberty** [comment]
Please merge master to this branch to resolve the c++20 issue.

**Comment by maliberty** [comment]
> I had addressed all the clang-tidy suggestions and resolved them, are there any I am missing?

Sorry I missed the 👍

**Comment by precisionmoon** [comment]
> @precisionmoon please do that first pass.

OK.   I'll schedule a review with Arthur tomorrow.

**Comment by precisionmoon** [comment]
I reviewed code changes and QoR results with @arthurjolo today.  These changes look fine.

**Comment by maliberty** [comment]
Are any metrics updates needed?

**Comment by arthurjolo** [comment]
> Are any metrics updates needed?

Yes, this pr has the necessary metrics changes: https://github.com/The-OpenROAD-Project-private/OpenROAD-flow-scripts/pull/942

**Comment by maliberty** [comment]
I've sync'ed it to public but also noticed you have metric conflicts
image

**Comment by arthurjolo** [comment]
Just fixed the merging, i believe it is ready now.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
