### PR TITLE
gui: ensure renderImage does not request an impossibly large QImage

### PR DESCRIPTION
**Pull request by gadfort**
Fixes:
- automatic scaling of renderImage limited to 7200px, preventing max image size violations.

### CODE REVIEW

**Comment by gadfort** [comment]
@maliberty this should fix the issue you ran into with the max size.

**Comment by maliberty** [comment]
Not so good, its just cut off:
image

**Comment by gadfort** [comment]
> Not so good, its just cut off: image

@maliberty I've adjusted rendering pixel ratio, which should fix it. I have not been able to replicate your exact issue, so I have no great way to test this unfortunately.

**Comment by maliberty** [comment]
replaced by https://github.com/The-OpenROAD-Project/OpenROAD/pull/2587

**Pull request closed without merging**
