### PR TITLE
rudy: avoid heatmap crash 

### PR DESCRIPTION
**Pull request by gudeh**
avoid crash when clicking on rudy heatmap and there are unplaced cells.

### CODE REVIEW

**Review by maliberty — COMMENTED** [review]
Will the user get any notification as to why the heatmap isn't shown?

**Comment by gudeh** [comment]
> Will the user get any notification as to why the heatmap isn't shown?

Yes. It generates the usual "not populated with data".

**Comment by maliberty** [comment]
> It generates the usual "not populated with data". Should it be more specific?

I think so as it won't be obvious why it isn't populated (which normally happens on demand rather than through an explicit step).

**Comment by gudeh** [comment]
We get the following when trying to activate rudy's heatmap after a `make gui_floorplan`
Screenshot from 2024-04-26 11-34-18

**Review by maliberty — APPROVED** [review]

**Pull request merged**
