### PR TITLE
rsz: Enable pin swapping 3+ input standard cells

### PR DESCRIPTION
**Pull request by QuantamHD**

### CODE REVIEW

**Comment by QuantamHD** [comment]
If you want to see what's required check out https://github.com/The-OpenROAD-Project/OpenROAD/pull/4681/commits/fdc3ef7d534eb028bdb0c5d0b0c75a7cfbe32eb8

**Comment by QuantamHD** [comment]
@maliberty any way to look at this change through the fancy graph thing?

**Comment by maliberty** [comment]
What is "the fancy graph thing"?  I'm hoping to land your dependent PR tomorrow (secure CI is running tonight).

**Comment by QuantamHD** [comment]
The website with the PPA graphs you guys have shown me before

**Comment by maliberty** [comment]
> The website with the PPA graphs you guys have shown me before

https://dashboard.theopenroadproject.org/

**Comment by maliberty** [comment]
secure CI started

**Pull request merged**
