### PR TITLE
lef: check if windows compile in lef.y and avoid referencing the lef_parser.hpp as it fails to compile

### PR DESCRIPTION
**Pull request by gadfort**
Fixes:
- Compiles for LEF parser only on windows.

### CODE REVIEW

**Comment by maliberty** [comment]
What happens without this change on windows?  It looks strange to exclude that include.

**Comment by gadfort** [comment]
> What happens without this change on windows? It looks strange to exclude that include.

A bunch of linker errors related to undefined symbols, it's not clear to me why it's in the .y to begin with, but this was the smallest change I needed to make to get windows to pass.

**Review by maliberty — APPROVED** [review]

**Comment by rovinski** [comment]
...is there native Windows support in the making? Or is this for WSL?

**Comment by maliberty** [comment]
> ...is there native Windows support in the making? Or is this for WSL?

There is no plan for native windows support.  It wouldn't be required for WSL.  I assume this is a one-off for some side purpose.

**Comment by gadfort** [comment]
> > ...is there native Windows support in the making? Or is this for WSL?
> 
> There is no plan for native windows support. It wouldn't be required for WSL. I assume this is a one-off for some side purpose.

SC builds a lef parser and it's distributed on windows as well. It's a one of application, I doubt anyone else is doing that

**Pull request merged**
