### PR TITLE
drt: fix interpretation of ndr vias

### PR DESCRIPTION
**Pull request by osamahammad21**
Fixes the coverage error.

### CODE REVIEW

**Review by maliberty — APPROVED** [review]
Please tidy & format before merging.  Does this affect non-NDR designs (if so a secure CI is needed)?

**Comment by osamahammad21** [comment]
@maliberty tidy and format actions were failing for unrelated reasons. It doesn't affect non-ndr designs

**Comment by maliberty** [comment]
I thought we had tidy'ed all of drt.  Is that not true?

**Comment by osamahammad21** [comment]
@maliberty Yes. The github actions were failing not the formatting. I restarted it and it worked the second time.

**Pull request merged**
