### PR TITLE
dr: fix via2via forbidden len

### PR DESCRIPTION
**Pull request by osamahammad21**
Signed-off-by: osamahammad21 <osama21@aucegypt.edu>

### CODE REVIEW

**Comment by osamahammad21** [comment]
Running Secure CI and ISPD tests.

**Comment by osamahammad21** [comment]
@maliberty
* Passes ISPD
* Passes Secure CI
* Passes All Tests Private except for one failure in [riscv32i/sky130hd in drv_max_slew_limit](https://jenkins.openroad.tools/blue/organizations/jenkins/OpenROAD-flow-scripts-All-Tests-Private/detail/secure_drt-fix-via-stacking/1/pipeline/681)

**Comment by osamahammad21** [comment]
@maliberty
* Passes ISPD
* Passes Secure CI
* Passes All Tests Private except for one failure in [riscv32i/sky130hd in drv_max_slew_limit](https://jenkins.openroad.tools/blue/organizations/jenkins/OpenROAD-flow-scripts-All-Tests-Private/detail/secure_drt-fix-via-stacking/1/pipeline/681)

**Comment by maliberty** [comment]
You should update the metrics for [riscv32i/sky130hd in drv_max_slew_limit](https://jenkins.openroad.tools/blue/organizations/jenkins/OpenROAD-flow-scripts-All-Tests-Private/detail/secure_drt-fix-via-stacking/1/pipeline/681)

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
@arlpetergadfort once this is merge can you try your via stacking fake-constraint again?

**Comment by arlpetergadfort** [comment]
> @arlpetergadfort once this is merge can you try your via stacking fake-constraint again?

@maliberty sure, just let me know when and I'll bring that code up again

**Comment by maliberty** [comment]
@arlpetergadfort merged

**Comment by maliberty** [comment]
I ran sky130hd/riscv32i after merging this change and there is no max_slew violation.  Something else must have changed in the meantime.

**Pull request merged**
