### PR TITLE
gui: resize viewer based on its actual size rather than the padded rect dimensions

### LINKED ISSUE #4033: zoom in/out to the position of the mouse in the view, not the view center
### Description

The current OpenRoad behavior is to zoom in/out of the center of the view.

It's much more useful when the point to zoom in or out to is determined by the position of the mouse cursor in the view.
This is the default behavior of klayout.

### Suggested Solution

"Zoom in window" is already using the mouse cursor to determine the new view coordinates by drawing the new view bounding box.
So using the mouse position for keyboard or mouse wheel zoom in/out instead of the view center should be fairly straight forward.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by AcKoucher**
Fix #4033

### CODE REVIEW

**Comment by maliberty** [comment]
@stefanottili would you try this out and see if it satisfies your request?

**Comment by stefanottili** [comment]
Nope, doesn't fix the issue.

Zoom into an area close to the chip boundary.
Use shift-Z to zoom-out to where your mouse is pointing.
Keep on zooming-out.

Eventually you hit an artificial OpenROAD "you're not allowed to zoom out any further" limit and the view shifts from under your mouse and then you can't zoom out any further with only half the chip in view.

The fix would be to completely remove the limit or at least allow zoom-out until the chip only covers a fifth of the width/height of the view.

If in doubt about OR gui behavior, compare it to klayout.
Its gui controls, mouse focus behavior and draw speed have seen decades of refinement and optimization.

**Comment by AcKoucher** [comment]
@stefanottili Did you test with the changes in this PR's branch?

**Comment by stefanottili** [comment]
yes, of course.

Use the "draw rectangle to zoom into" gesture to zoom into any corner of a block, so that the corner is in the middle of the view. Then place the mouse on the corner in the middle of the view and hit "shift-z" to zoom out. This keeps the corner in the middle of the view only up to the point where the size of the block matches the size of the view (fit) and the view shifts.
it wouldn't if the artificial "can't zoom out further then this" limit wouldn't kick in. See klayout.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
