### PR TITLE
Openroad exit crash fix

### LINKED ISSUE #3263: Crash when exiting openroad -gui
> 

Aha! This bug is on master, not in this PR. I tested this PR by merging with master as I thought master was working.

To reproduce:

1. Check out master
2. ./build_openroad.sh --local --clean-force
3. Run: `make DESIGN_CONFIG=designs/asap7/mock-array-big/config.mk` or `make DESIGN_CONFIG=designs/asap7/gcd/config.mk`
4. `openroad -gui` and load 6_final.odb of the design, exit immediately. Crash below.

```
Signal 11 received
Stack trace:
 0# 0x0000562A15A686FB in openroad
 1# 0x00007FED40A42520 in /lib/x86_64-linux-gnu/libc.so.6
 2# std::_Rb_tree_increment(std::_Rb_tree_node_base const*) in /lib/x86_64-linux-gnu/libstdc++.so.6
 3# std::_Rb_tree_const_iterator<gui::Renderer*>::operator++() in openroad
 4# gui::MainWindow::~MainWindow() in openroad
 5# gui::MainWindow::~MainWindow() in openroad
 6# gui::startGui(int&, char**, Tcl_Interp*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) in openroad
 7# 0x0000562A15A69007 in openroad
 8# ord::tclAppInit(Tcl_Interp*) in openroad
 9# Tcl_MainEx in /lib/x86_64-linux-gnu/libtcl8.6.so
10# main in openroad
11# 0x00007FED40A29D90 in /lib/x86_64-linux-gnu/libc.so.6
12# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
13# _start in openroad
Segmentation fault (core dumped)
```

_Originally posted by @oharboe in https://github.com/The-OpenROAD-Project/OpenROAD/issues/3258#issuecomment-1527198864_

### PR DESCRIPTION
**Pull request by oharboe**
Merging this to fix the crash until a more permanent solution can be found is an option...

Fixes #3263

### CODE REVIEW

**Comment by vijayank88** [comment]
@oharboe 
Click on `Set DCO to pass` by selecting `Details`

**Comment by oharboe** [comment]
> @oharboe Click on `Set DCO to pass` by selecting `Details`

Thanks! I cross fingers that a fix is just around the corner making this PR moot.

**Comment by gadfort** [comment]
@maliberty I think this is the correct thing to do. Because we allow for the gui to be closed and reopened, the registered renderers should not be removed (I was wrong before)

**Comment by oharboe** [comment]
> @maliberty I think this is the correct thing to do. Because we allow for the gui to be closed and reopened, the registered renderers should not be removed (I was wrong before)

Someone who knows what is going on should articulate the revert pull request and commit comment...

**Pull request closed without merging**
