### PR TITLE
etc: add gtest to DependencyInstaller

### PR DESCRIPTION
**Pull request by vvbandeira**
cherry-picked from #5592

### CODE REVIEW

**Comment by stefanottili** [comment]
This comit broke compling on MacOS.
"brew install googletest" is not suficcient, linking steps fail with
```
[ 73%] Built target odb_test_helper
ld: warning: ignoring duplicate libraries: '../../src/db/libdb.a', '../../src/zutil/libzutil.a'
ld: library 'gtest' not found
```

**Comment by maliberty** [comment]
@eder-matheus would you try?

**Comment by gadfort** [comment]
@maliberty this introduced a new requirement which is not captured in the dependency installer.
I need to install `unzip` which is not available in the minimal ubuntu docker images, if I want to install this. This used to not be required.

**Comment by maliberty** [comment]
@vvbandeira please add unzip

**Pull request merged**
