### PR TITLE
etc: use brew to install or-tools in macOS

### PR DESCRIPTION
**Pull request by eder-matheus**
The runtime errors on macOS are fixed when using brew to install or-tools.

Possible fix for https://github.com/The-OpenROAD-Project/OpenROAD/issues/4583

### CODE REVIEW

**Comment by stefanottili** [comment]
Just in case you have not seen this discussion, could you please also get the swig 4.1.1 compile fix into the installer to get a clean compile on Mac ?

https://github.com/The-OpenROAD-Project/OpenROAD/discussions/4956

**Comment by eder-matheus** [comment]
> Just in case you have not seen this discussion, could you please also get the swig 4.1.1 compile fix into the installer to get a clean compile on Mac ?
> 
> #4956

@stefanottili Done! Could you try it in your end?

**Comment by stefanottili** [comment]
works on M1 macOS Sonoma, manually downloading the 7 files as raw

OpenROAD v2.0-13316-g10056c339 
Features included (+) or not (-):  +Charts +GPU +GUI +Python

	modified:   ../etc/DependencyInstaller.sh
	modified:   ../include/ord/OpenRoad.hh
	modified:   ../src/CMakeLists.txt
	modified:   ../src/Main.cc
	modified:   ../src/OpenRoad-py.i
	modified:   ../src/OpenRoad.cc
	modified:   ../src/OpenRoad.i

**Comment by stefanottili** [comment]
I just noticed +GPU, is it safe to assume that that won't work on M1 ?

**Pull request merged**
