### PR TITLE
DO NOT MERGE checking for negative total wire length

### PR DESCRIPTION
**Pull request by oharboe**

### CODE REVIEW

**Comment by oharboe** [comment]
@maliberty Someone noticed hpwl being negative, so I thought I would check quickly in master on any of the tests there.

This assert should never trigger, right?

**Comment by maliberty** [comment]
It should not fail.  Likewise in NesterovBase::getHpwl.  Note that we compile asserts out in optimized builds so they don't create a lot of coverage in the CI.

It seems unlikely that we are overflowing an int64_t.  Is there a testcase that shows the problem?

**Comment by oharboe** [comment]
> It should not fail. Likewise in NesterovBase::getHpwl. Note that we compile asserts out in optimized builds so they don't create a lot of coverage in the CI.
> 
> It seems unlikely that we are overflowing an int64_t. Is there a testcase that shows the problem?

Yes, someone noticed it in the discussions, but how do I search discussions?

**Comment by maliberty** [comment]
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1001
(just use the search box at the top of the GH page)

**Comment by oharboe** [comment]
> [The-OpenROAD-Project/OpenROAD-flow-scripts#1001](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1001) (just use the search box at the top of the GH page)

It doesnt show issues, pull requests or discussions NAICT

**Comment by maliberty** [comment]
> > [The-OpenROAD-Project/OpenROAD-flow-scripts#1001](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1001) (just use the search box at the top of the GH page)
> 
> It doesnt show issues, pull requests or discussions NAICT

image

**Pull request closed without merging**
