### PR TITLE
Add `or-tools` to cmake and remove hard coded paths

### PR DESCRIPTION
**Pull request by joennlae**
This fixes the non-docker build. It includes `or-tools` as described by the devs here: https://github.com/or-tools/cmake_or-tools/tree/main/LocalInstall

I tried to get the `local` build running due to not having access to docker (not my decision), and it always crashed because of the hard-coded paths in `cmake`.

Here:
https://github.com/The-OpenROAD-Project/OpenROAD/blob/df19865e51b0c192caf4e8ee7ecf7b88ee593194/src/mpl2/CMakeLists.txt#L37-L40

And here:

https://github.com/The-OpenROAD-Project/OpenROAD/blob/df19865e51b0c192caf4e8ee7ecf7b88ee593194/src/CMakeLists.txt#L39-L42

This works nicely in a docker env, and I tried to bypass it by setting `CMAKE_INSTALL_RPATH` and `CMAKE_INSTALL_PREFIX`, but I still had some linking issues.

I know my proposed solution will lead to longer build times, but I think it will mitigate issues in the future. 

I tagged the latest release here:

https://github.com/joennlae/OpenROAD/blob/7c3c5cdef94cb29434b418999434fc5f62db2e4c/src/cmake/ortools.CMakeLists.txt#L8

Tell me what you think about this solution.

It could maybe also fix the macOS problem:
https://github.com/The-OpenROAD-Project/OpenROAD/blob/df19865e51b0c192caf4e8ee7ecf7b88ee593194/src/CMakeLists.txt#L328-L331
but I did not run any tests.

### CODE REVIEW

**Comment by maliberty** [comment]
CMAKE_INSTALL_RPATH just sets a default and isn't a requirement.  It avoids the need to set LD_LIBRARY_PATH if you choose to use that path but shouldn't cause a crash or any error.

Would you explain further your crash?  I use a non-docker local build daily without issue.  

I'm not keen on the increased build time this solution represents.  We also have seen that such solutions lead to random build failures when the remote site is unavailable/unreachable for any reason.

**Comment by joennlae** [comment]
Yes, so I try to build an independent toolchain. Also, building other eda tools for our environment here. I tried to make it work, but I always get a linker error when not using the defined `/opt/or-tools/`. And I can not use that folder. The best-case scenario for me would be not to patch it (openroad). That is why I proposed this solution.

I obviously understand that introducing this build dependency is not the best case, especially for the devs. Yeah, so maybe I have to figure out another solution.

**Comment by joennlae** [comment]
I also tried with LD_LIBRARY_PATH and CMAKE_INSTALL_RPATH, but somehow it doesn't help.

**Comment by maliberty** [comment]
What is the link error?

**Comment by joennlae** [comment]
LD_error:
```
mpl2/mpl2.a(bus_synthesis.cpp.o): In function `mpl2::calNetPaths(std::vector<mpl2::SoftMacro, std::allocator<mpl2::SoftMacro> >&, std::vector<int, std::allocator<int> >&, std::vector<mpl2::Edge, std::allocator<mpl2::Edge> >&, std::vector<mpl2::Vertex, std::allocator<mpl2::Vertex> >&, std::vector<mpl2::BundledNet, std::allocator<mpl2::BundledNet> >&, float, utl::Logger*)':                                                                                                                                                                                                                                                                                                                                    
bus_synthesis.cpp:(.text+0x97af): undefined reference to `operations_research::MPSolver::CreateSolver(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
bus_synthesis.cpp:(.text+0x98b3): undefined reference to `operations_research::MPSolver::MakeIntVar(double, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
bus_synthesis.cpp:(.text+0x99fe): undefined reference to `operations_research::MPSolver::MakeIntVar(double, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
bus_synthesis.cpp:(.text+0xa0b4): undefined reference to `operations_research::MPSolver::MakeRowConstraint(double, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'                                                                                                                                                                                                                                                                                                             
bus_synthesis.cpp:(.text+0xa18c): undefined reference to `operations_research::MPSolver::MakeRowConstraint(double, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
bus_synthesis.cpp:(.text+0xa3c0): undefined reference to `operations_research::MPSolver::MakeRowConstraint(double, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
collect2: error: ld returned 1 exit status   
```

**Comment by joennlae** [comment]
What compiler are you using? I am using `gcc-11.2.0`

**Comment by maliberty** [comment]
Does closing this mean you have resolved it?

**Comment by joennlae** [comment]
@maliberty It is resolved now. 
So I think it is a local issue. Because when I build `or-tools` locally and link it the same way when using the downloaded centos7 release, it works. So I believe there must be some ABI compatibility issues between the official centos7 release build image and our local centos7 installation. Our setup is non-standard. So I believe this is an isolated bug. Sorry for the inconvenience.

**Pull request closed without merging**
