### PR TITLE
meta: Adds ClangTidy check to class names

### PR DESCRIPTION
**Pull request by QuantamHD**
We'll see if this does what I'm expecting, and only checks class names.

### CODE REVIEW

**Comment by maliberty** [comment]
Are you doing manual testing as this PR won't trigger any actual scan of code?

**Comment by QuantamHD** [comment]
Yeah let me give it a shot

**Comment by maliberty** [comment]
any update?

**Comment by maliberty** [comment]
stale - reopen if relevant

**Pull request closed without merging**
