### PR TITLE
gui: add qtmessagehandler and save images without transparency

### PR DESCRIPTION
**Pull request by gadfort**
Adds:
- qtmessagehandler to redirect qt messages to the logger and suppress warnings about plugins when compiled with NDEBUG.

Changes:
- Converts images before saving to avoid transparency in the image. @maliberty could you try this and see if this solves the background issue you are having?

### CODE REVIEW

**Comment by maliberty** [comment]
It doesn't help with the color.  I loaded the webp into gimp and I see the alpha is 255 in the background area:
image

**Comment by gadfort** [comment]
> With the DISPLAY set: image

grrrrrrrr, okay, I'll keep poking around

**Comment by maliberty** [comment]
Even in master alpha=255

**Review by maliberty — APPROVED** [review]
The message handler piece is good.

**Comment by gadfort** [comment]
> The message handler piece is good.

@maliberty I've tried setting the background to white instead of nobrush (when you have a chance could you see if that fixes it?) If it doesn't I'll revert is out and then I'm out of ideas at the moment for how to solve it.

**Comment by maliberty** [comment]
No change, still blackish

**Comment by gadfort** [comment]
> No change, still blackish

alright, well worth a shot, so for now I'm out of ideas.

**Comment by QuantamHD** [comment]
It might help to drop into gdb and step through the image writing function. Eventually you'll get to a place where the background color is being chosen, and it'll become clear why

**Comment by maliberty** [comment]
Unfortunately Peter can't reproduce my problem so I'll have to do that myself

**Pull request merged**
