### PR TITLE
Improve hold fixing

### PR DESCRIPTION
**Pull request by openroadie**
Add a small fix to not create new slew violations when fixing hold violations. This helps with the testcase provided by @luis201420 where we are running repair design with global routing parasitics.

### CODE REVIEW

**Comment by maliberty** [comment]
ci issues

**Comment by openroadie** [comment]
I updated the involved metric a bit (1.5%) since this seems to be a platform variation (not related to current code change... but somehow triggered by it). Open to thoughts on a better way to handle this. @vvbandeira @maliberty

**Comment by maliberty** [comment]
I think the metric update is fine.  I think it is worth a secure CI.

**Comment by openroadie** [comment]
It is a one line change but ok...

**Comment by openroadie** [comment]
So I see that there are some failures. I still don't have access. So how do we proceed?

**Comment by vvbandeira** [comment]
> So I see that there are some failures. I still don't have access. So how do we proceed?

I can help with that, will ping you on Slack.

**Comment by maliberty** [comment]
On the public side you could look at jpeg nangate45

**Comment by openroadie** [comment]
@maliberty I looked at nangate45/jpeg and I don't see any errors/problems. Could you be more specific on what I am looking for. Here are some snippets of the log:

```
TNS end percent 100
[INFO RSZ-0046] Found 65 endpoints with hold violations.
[INFO RSZ-0032] Inserted 3 hold buffers.
...
==========================================================================
cts final max_slew_violation_count
--------------------------------------------------------------------------
max slew violation count 0
==========================================================================
cts final max_fanout_violation_count
--------------------------------------------------------------------------
max fanout violation count 0
==========================================================================
cts final max_cap_violation_count
--------------------------------------------------------------------------
max cap violation count 1

```

**Comment by maliberty** [comment]
On https://jenkins.openroad.tools/job/OpenROAD-flow-scripts-All-Tests-Private/job/secure-hold-fixing-improvements/ you can see the results.   In particular https://jenkins.openroad.tools/job/OpenROAD-flow-scripts-All-Tests-Private/job/secure-hold-fixing-improvements/1/execution/node/773/log/ shows

```
[ERROR] finish__timing__setup__ws fail test: -0.125572 >= -0.12
[ERROR] finish__timing__drv__setup_violation_count fail test: 196.0 <= 58.0
```

**Comment by openroadie** [comment]
Interesting. So ORFS scripts are not the same in public and private. I will take a look. Here are the public results:

```
[INFO] finish__timing__setup__ws pass test: -0.0379476 >= -0.12
[INFO] finish__design__instance__area pass test: 100819.0 <= 115889.0
[INFO] finish__timing__drv__max_slew_limit pass test: 0.308282 >= -0.2
[INFO] finish__timing__drv__max_fanout_limit pass test: 0.0 >= -0.2
[INFO] finish__timing__drv__max_cap_limit pass test: -0.0730568 >= -0.2
[INFO] finish__timing__drv__setup_violation_count pass test: 40.0 <= 58.0
[INFO] finish__timing__drv__hold_violation_count pass test: 0.0 <= 10.0
[INFO] finish__timing__wns_percent_delay pass test: -1.948185 >= -12.33

```

**Comment by maliberty** [comment]
That was from the public Jenkins on the PR you submitted.  Where are you getting the results you are quoting?

**Comment by openroadie** [comment]
> That was from the public Jenkins on the PR you submitted. Where are you getting the results you are quoting?

I am getting them from the public ORFS. I can see the same problem in the private ORFS (with this public case). But why should hold fixing impact setup checks? And what should really be done if post CTS results are good but the final results end up being worse? I will see if I can tune the logic for not adding new slew violations by a bit and whether that helps.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
