### PR TITLE
[TritonCTS] Review: Updated function to find clock nets

### PR DESCRIPTION
**Pull request by MarceloDanigno**
**[PR for Review!!!]**
This changes how clocks are loaded into TritonCTS.
First, we create a set and use dbSta's findClkNets function. After that, we insert all clocks from the user inputs (if there are any and if they aren't already in the set.)
After that, we create the Clock objects inside TritonCTS for the nets that have more than 2 sinks. This includes input and inout pins.

Another thing that was added to this PR was a unit test that test the new functionality. This was based on Cherry's dbSta find_clock unit test. Also, the reports for TritonCTS changed a little, to report cases where pins do not have shapes, the number of clocks, and others...

[Code in this PR was made with the help/additions of Matt Liberty, James Cherry, and Tom Spyrou]

### CODE REVIEW

**Comment by MarceloDanigno** [comment]
The first commit part is just from when me and Mateus created the fork to code for PartClusManager. The current PR has no code for it, but I'll see if I can clear up the commit history to remove it. Sorry about that.

For the part on changing the OpenRoad call, I can change it to only use it when initializing the DbWrapper class. 

parseClockNames is just a simple function that transforms an std::string to an std::vector<std::string>. It doesn't define any new names or creates any TritonCTS objects (Clock, Net...).

**Comment by MarceloDanigno** [comment]
Closing this and, after I finish the fixes, I'll do another PR.

**Comment by rovinski** [comment]
@MarceloDanigno A better work flow is to keep the original pull request open. When you push changes to your fork, the commits will automatically be added to the pull request. You can re-request a review whenever it's ready.

If the commit history is messy and you only want the final set of changes, you can select "squash and merge" as the merge option. This will squash all changes into a single commit before merging with OpenROAD (so for example, if you revert several changes, only the final state is captured).

If you need to ensure the history is clean _and_ spread over multiple commits, that might be a reason to close and open a different pull request. But that should be a rare circumstance.

**Comment by MarceloDanigno** [comment]
@rovinski Thanks for the information Austin! I wasn't aware of these options, so this is definitely useful. I'll keep it in mind for future PR's.

**Pull request closed without merging**
