### PR TITLE
sync readme OR images

### PR DESCRIPTION
**Pull request by vijayank88**
Update OpenROAD flow stages images as per latest features.

### CODE REVIEW

**Review by vvbandeira — APPROVED** [review]

**Comment by gadfort** [comment]
@maliberty @vijayank88 how come the background in these images is not black but is gray instead?  That seems to be a bug in the GUI?

**Comment by maliberty** [comment]
I recall Seyi had a similar screen but I've never seen it.  @vijayank88 do you see the gray background when running interactively?

**Comment by gadfort** [comment]
@maliberty that is why it caught my eye

**Comment by vijayank88** [comment]
I don't recall which commit has changed, but I see gray background past one month... But if I save image through command line arguments getting black for layout area.

**Comment by maliberty** [comment]
@vijayank88 what platform are you running on?

**Comment by vijayank88** [comment]
GCP CentOS 7

**Pull request merged**
