### PR TITLE
Feature: core_space for all margins

### PR DESCRIPTION
**Pull request by kareefardi**
Hello,

This commit allows setting the core space with independent values for all margins while maintaining the ability to set one value for all margins. Let me know if there is something you prefer to be done differently in the PR.

Thanks

### CODE REVIEW

**Comment by tspyrou** [comment]
I restarted the CI. It may have failed due to a network glitch.

**Comment by kareefardi** [comment]
Thanks. I was able to build locally and pass regression. I will add a unit test that exercises the additional feature.

**Comment by jjcherry56** [comment]
I don't see any reason to introduce another def file for the test.
Please use an existing one from the directory like the other tests.

The command arg doc is wonky. It should look like 
sta::define_cmd_args "initialize_floorplan" {[-utilization util]\
					       [-core_space space|{bottom top left right]\
	
instead of duplicating the keyword doc.

The README.md should be updated to document the change.

**Comment by kareefardi** [comment]
Hello @jjcherry56 . Thanks for the feedback. For the test case, I duplicated an existing test while changing the .tcl file adjusting the -core_space argument and providing .ok files for the output.

As for the command arg doc, the reason I decided to leave both `[-core_space space]` and `[-core_space {bottom top left right}]`, is that the PR allows for both options.

Let me know if there is more appropriate way to handle the command arg doc and the unit test

**Comment by jjcherry56** [comment]
Instead of **copying** the def file (https://github.com/The-OpenROAD-Project/OpenROAD/pull/229/commits/f922fe19727267df8f8f3aae364f07107398f11a#diff-a3f71022fe40673ada4892e945407b62) just read the existing one.

My previous comment was explicit about how to document the arg: you use | to mean **or**.

**Comment by kareefardi** [comment]
Oh sorry I miss read your comment. Ok got it will update the branch

**Comment by jjcherry56** [comment]
and lastly please update openroad/doc/README.md init_floorplan arg doc

**Comment by kareefardi** [comment]
I assume you mean the README.md in the main page? Does all look good now?

**Pull request merged**
