### PR TITLE
ord: Redirect writeDb file opening exception to ORD.

### PR DESCRIPTION
**Pull request by titan73**
Also add open method to strean handler so it can be instanciated outside the try block where file opening is done.

### CODE REVIEW

**Review by oharboe — CHANGES_REQUESTED** [review]
Keep the RAII interface unchanged and improve only error messages.

This PR requires all invocations to become substantially messier.

It is unclear to me why the API needs to change to fix the error messages and why we want to fix the error messages for only one case.

**Comment by titan73** [comment]
Created https://github.com/The-OpenROAD-Project/OpenROAD/pull/6133 for error message in stream handler.

**Comment by maliberty** [comment]
Is this still relevant after #6133 ?

**Comment by titan73** [comment]
No. Closing.

**Pull request closed without merging**
