### PR TITLE
[ioPlacer] Fix crash when design has no tracks

### PR DESCRIPTION
**Pull request by mpfogaca**
*** Please do not merge before https://github.com/The-OpenROAD-Project/OpenROAD/pull/176 ***

### CODE REVIEW

**Comment by jjcherry56** [comment]
I thought about this a bit and a better solution is to have the tcl command check for tracks so it never gets to the c++ error. Here is how opendp does something similar for rows:

  if { [ord::db_has_rows] } {
    opendp::detailed_placement_cmd $max_displacment
  } else {
    ord::error "no rows defined in design. Use initialize_floorplan to add rows."
  }

I suggest a similar tcl accessible function db_has_tracks in this case (and it sounds like fastroute too).

**Comment by mpfogaca** [comment]
@jjcherry56 
OK. But ioPlacer just cares about two layers, so I created these two functions:
`db_layer_has_hor_tracks layer_id` and `db_layer_has_ver_tracks layer_id`

For FastRoute, @eder-matheus can use create the `db_has_tracks` function to iterate
though all layers and use my two functions above to check if the track grid for each layer
exists.

**Comment by jjcherry56** [comment]
sounds good

**Comment by mpfogaca** [comment]
@jjcherry56 Could you approve the previous PR-176 to avoid conflicts?
https://github.com/The-OpenROAD-Project/OpenROAD/pull/176

**Comment by jjcherry56** [comment]
I approved it with the first comment

**Pull request merged**
