### PR TITLE
gui: change slack histogram preset filters for path groups

### LINKED ISSUE #5162: Improve speed of filtering in endpoint slack histogram
### Description

Larger designs can render no filter in seconds and yet it takes as much as an hour to filter regreg, regio, etc.

This is a problem with a larger design I cant provide a public test case for. When I tried with sky130hd/microwatt (largest design in ORFS?), performance for filtering was tolerable.

### Suggested Solution

Improve performance.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by AcKoucher**
Resolve #5162 

The filters menu will now show the path groups set in the .sdc when running the slack histogram.
For path groups created by running `group_paths` in the GUI Scripting, my idea was to add  a Refresh Filters button that will incorporate those newly generated groups into the menu.

In order for the changes here to work it was needed to make a small change in sta, that's why the submodule update.

Note: with these changes we're also avoiding constructing an entire clock tree structure (in the staGuiInterface that Charts use) just to get the clocks.

### CODE REVIEW

**Comment by oharboe** [comment]
I see that this is a draft and not ready for review, but I took it for a spin anyway :-)

I tried it on `make DESIGN_CONFIG=designs/asap7/mock-array/config.mk nuke final gui_final`

- Userinterface looks nice, but all the path groups show the same in the histogram, I would have expected differences
- there are no path groups in the timing report. It is possible to filter the timing report on path group by first clicking on endpoint slack histogram, which will take you to Timing Report having selected a bucket.

image

**Comment by oharboe** [comment]
Again, I know this is a draft, but I tried it on a larger design I can't share and it takes a long time to switch to another path group.

After a few minutes, I paused it in the debugger and got:

```
odb::dbObject::getObjectType() const (@odb::dbObject::getObjectType() const:5)
sta::dbNetwork::id(sta::Pin const*) const (@sta::dbNetwork::id(sta::Pin const*) const:21)
sta::PinSet::compare(sta::PinSet const*, sta::PinSet const*, sta::Network const*) (@sta::PinSet::compare(sta::PinSet const*, sta::PinSet const*, sta::Network const*):45)
sta::ExceptionFromTo::compare(sta::ExceptionPt*, sta::Network const*) const (@sta::ExceptionFromTo::compare(sta::ExceptionPt*, sta::Network const*) const:29)
sta::ExceptionPathLess::operator()(sta::ExceptionPath const*, sta::ExceptionPath const*) const (@sta::ExceptionPathLess::operator()(sta::ExceptionPath const*, sta::ExceptionPath const*) const:67)
sta::ExceptionStateLess::operator()(sta::ExceptionState const*, sta::ExceptionState const*) const (@sta::ExceptionStateLess::operator()(sta::ExceptionState const*, sta::ExceptionState const*) const:22)
std::pair<std::_Rb_tree_iterator<sta::ExceptionState*>, bool> std::_Rb_tree<sta::ExceptionState*, sta::ExceptionState*, std::_Identity<sta::ExceptionState*>, sta::ExceptionStateLess, std::allocator<sta::ExceptionState*>>::_M_insert_unique<sta::ExceptionState* const&>(sta::ExceptionState* const&) (@std::pair<std::_Rb_tree_iterator<sta::ExceptionState*>, bool> std::_Rb_tree<sta::ExceptionState*, sta::ExceptionState*, std::_Identity<sta::ExceptionState*>, sta::ExceptionStateLess, std::allocator<sta::ExceptionState*>>::_M_insert_unique<sta::ExceptionState* const&>(sta::ExceptionState* const&):63)
sta::Sdc::filterRegQStates(sta::Pin const*, sta::RiseFall const*, sta::MinMax const*, sta::Set<sta::ExceptionState*, sta::ExceptionStateLess>*&) const (@sta::Sdc::filterRegQStates(sta::Pin const*, sta::RiseFall const*, sta::MinMax const*, sta::Set<sta::ExceptionState*, sta::ExceptionStateLess>*&) const:91)
sta::PathVisitor::visitFromPath(sta::Pin const*, sta::Vertex*, sta::RiseFall const*, sta::PathVertex*, sta::Edge*, sta::TimingArc*, sta::Pin const*, sta::Vertex*, sta::RiseFall const*, sta::MinMax const*, sta::PathAnalysisPt const*) (@sta::PathVisitor::visitFromPath(sta::Pin const*, sta::Vertex*, sta::RiseFall const*, sta::PathVertex*, sta::Edge*, sta::TimingArc*, sta::Pin const*, sta::Vertex*, sta::RiseFall const*, sta::MinMax const*, sta::PathAnalysisPt const*):212)
sta::PathVisitor::visitEdge(sta::Pin const*, sta::Vertex*, sta::Edge*, sta::Pin const*, sta::Vertex*) (@sta::PathVisitor::visitEdge(sta::Pin const*, sta::Vertex*, sta::Edge*, sta::Pin const*, sta::Vertex*):94)
sta::PathVisitor::visitFaninPaths(sta::Vertex*) (@sta::PathVisitor::visitFaninPaths(sta::Vertex*):70)
sta::ArrivalVisitor::visit(sta::Vertex*) (@sta::ArrivalVisitor::visit(sta::Vertex*):36)
sta::BfsIterator::visit(int, sta::VertexVisitor*) (@sta::BfsIterator::visit(int, sta::VertexVisitor*):73)
sta::Search::findFilteredArrivals(bool) (@sta::Search::findFilteredArrivals(bool):97)
sta::Search::findPathEnds(sta::ExceptionFrom*, sta::Vector<sta::ExceptionThru*>*, sta::ExceptionTo*, bool, sta::Corner const*, sta::MinMaxAll const*, int, int, bool, float, float, bool, sta::Set<char const*, sta::CharPtrLess>*, bool, bool, bool, bool, bool, bool) (@sta::Search::findPathEnds(sta::ExceptionFrom*, sta::Vector<sta::ExceptionThru*>*, sta::ExceptionTo*, bool, sta::Corner const*, sta::MinMaxAll const*, int, int, bool, float, float, bool, sta::Set<char const*, sta::CharPtrLess>*, bool, bool, bool, bool, bool, bool):48)
gui::STAGuiInterface::getTimingPaths(std::set<sta::Pin const*, std::less<sta::Pin const*>, std::allocator<sta::Pin const*>> const&, std::vector<std::set<sta::Pin const*, std::less<sta::Pin const*>, std::allocator<sta::Pin const*>>, std::allocator<std::set<sta::Pin const*, std::less<sta::Pin const*>, std::allocator<sta::Pin const*>>>> const&, std::set<sta::Pin const*, std::less<sta::Pin const*>, std::allocator<sta::Pin const*>> const&) const (@gui::STAGuiInterface::getTimingPaths(std::set<sta::Pin const*, std::less<sta::Pin const*>, std::allocator<sta::Pin const*>> const&, std::vector<std::set<sta::Pin const*, std::less<sta::Pin const*>, std::allocator<sta::Pin const*>>, std::allocator<std::set<sta::Pin const*, std::less<sta::Pin const*>, std::allocator<sta::Pin const*>>>> const&, std::set<sta::Pin const*, std::less<sta::Pin const*>, std::allocator<sta::Pin const*>> const&) const:175)
gui::ChartsWidget::fetchPathsBasedOnStartEnd(gui::StartEndPathType) (@gui::ChartsWidget::fetchPathsBasedOnStartEnd(gui::StartEndPathType):650)
gui::ChartsWidget::changeStartEndFilter() (@gui::ChartsWidget::changeStartEndFilter():51)
```

**Comment by oharboe** [comment]
Tried with a large design; fast. Used to take hours to switch to reg2reg.

**Comment by maliberty** [comment]
This is pending on some sta changes as the path groups are only initialized by report_checks which shouldn't be required.

**Comment by AcKoucher** [comment]
@oharboe This should be working now :)
Could you please check to see if it attends your needs?

**Review by maliberty — APPROVED** [review]
I will wait to merge for @oharboe ok

**Comment by oharboe** [comment]
```
make DESIGN_CONFIG=designs/asap7/mock-array/config.mk gui_final
```

select "reg2out", try resizing window, the endpoint slack histogram does not resize


image


Also, there are nothing in the "reg2out" buckets in the histogram, even if there are at least 100 reported by `report_checks -from [all_registers] -to [all_outputs] -group_count 100`

Aha!

@tspyrou said that `report_checks -from [all_registers] -to [all_outputs]` and `report_checks -from [all_clocks] -to [all_outputs]` should give the same result, but they do not, the latter reports no paths.

```
>>> report_checks -from [all_clocks] -to [all_outputs]
No paths found.
```

**Comment by oharboe** [comment]
@AcKoucher Nice! I think resizing problem with 0 paths for a path group should be fixed and then as far as I am concerned it can be merged.

There are some remaining STA issues, but I don't see why the GUI code can't be merged now.

**Comment by oharboe** [comment]
I had a problem on a design I can't share, I emailed Matt some details. I observed in2reg in the Timing Report when I click on a bucket in the reg2reg path.

I have a suspicion: could it be that the "No Path Group", instead of the active path group in the drop down, is used when clicking on a bucket?

**Comment by AcKoucher** [comment]
@oharboe The Timing Report doesn't know about the path group. Currently it just receives the information of the endpoints and generates the report based on that.

@maliberty To solve that we could emit the pathgroup pointer with the endpoints and make Timing Report check it.

As this is already approved, I could do it in a subsequent PR.

**Comment by AcKoucher** [comment]
@oharboe For the resizing, how about we just clear the widget entirely and throw a warning like "No endpoints for the selected path group!" when there's nothing to show? I'm thinking that it looks a bit weird that for an empty histogram it keeps the axis from the previous one.

**Comment by oharboe** [comment]
"throw a warning" sounds omnious....

There is nothing wrong, just display "no paths in path group"?

**Comment by AcKoucher** [comment]
Like this?

**Pull request merged**
