### PR TITLE
pdngen: check if net is in domain net list before looking in net_map

### PR DESCRIPTION
**Pull request by gadfort**

### CODE REVIEW

**Comment by maliberty** [comment]
Is this ready for review?

**Comment by gadfort** [comment]
@maliberty yes

**Review by maliberty — APPROVED** [review]
It looks fine but when does this problem actually arise?

**Comment by gadfort** [comment]
It really shouldn't, but it's possible (possibly by defining overlapping domains, I'll need to track down the fundamental issue, hopefully I can figure it out this week). But during regular use, it doesn't come up.

**Pull request merged**
