### PR TITLE
Display busy cursor during heatmap calculations.

### PR DESCRIPTION
**Pull request by gudeh**
Asked by user on issue #4630.

### CODE REVIEW

**Comment by oharboe** [comment]
@gudeh @maliberty already adressed by the animating elipsis, no?

**Comment by gudeh** [comment]
Hi @oharboe! I am not aware about this change you mentioned. Although, the requested change is specifically for when we click the button to show the heatmap, since it takes some time on larger designs. Until now, we haven't had any indicator to show that it's loading.

**Comment by oharboe** [comment]
@gudeh Try #4638, it might need a bit of bling, bu

**Comment by maliberty** [comment]
I think this is different from the rendering busy signal.  The heat map generation runs in the main thread

**Comment by oharboe** [comment]
> I think this is different from the rendering busy signal. The heat map generation runs in the main thread

Ideally, the calculation could be moved to the rendering thread...?

**Comment by maliberty** [comment]
> Ideally, the calculation could be moved to the rendering thread...?

Its not a rendering operation.  Perhaps another thread could be used but that would add a lot more complexity.

**Comment by oharboe** [comment]
> > Ideally, the calculation could be moved to the rendering thread...?
> 
> Its not a rendering operation. Perhaps another thread could be used but that would add a lot more complexity.

Why have multiple non UI threads? 

Currently rendering is locked when the GUI thread is locked.... 

So locking rendering thread is an improvement over locking.main thread.

**Comment by maliberty** [comment]
Rendering is not the only concern.  Any modifications to odb while there are readers is unsafe.

**Pull request merged**
