### PR TITLE
[TritonCTS] Updated tests, OpenDB interface, reports and TCL

### PR DESCRIPTION
**Pull request by MarceloDanigno**
An updated version of PR #348; this fixes the comments from the last PR. Works on the latest version of OpenROAD. Also has some error handling to prevent floating nets.

### CODE REVIEW

**Comment by MarceloDanigno** [comment]
The latest commit fixes some of the logic that was not needed when loading LUT files (checking if it exists twice; if the characterization needs to be run or not depending on the input...)
This is now done inside the TechChar methods.

**Comment by MarceloDanigno** [comment]
The main difference from this PR with the last one is that, in here, TritonCTS only takes into consideration the net (odb::dbNet*). We do not search the current block for a net (by its name) anymore and instead use the net object. Net names are now only used for reports. The SDC name code was also removed.

**Comment by tspyrou** [comment]
Has this been tested on bp_single?

**Comment by MarceloDanigno** [comment]
I remember there was one run for bp_single, but it has been overwritten by now. I'll talk to Eder about another run (and save the log/report folder) and get back to this thread once it is done.
I think I'll also add a unit test for the floating nets check.

**Pull request merged**
