### PR TITLE
Add missing `#include <vector>` in src/odb/src/db/*

### PR DESCRIPTION
**Pull request by hzeller**
Files that use std::vector, but haven't included the corresponding header yet.

### CODE REVIEW

**Comment by hzeller** [comment]
mmh, looks like the clang-format version 17.0.6 I am using produces slightly different result than the CI one. Let me manually fix that.

**Comment by hzeller** [comment]
alright, formatting hurdle fixed by getting an old 14.0.6.
Looks like some of these files are actually generated, so I'll have to fix the generator templates instead...

**Comment by maliberty** [comment]
No need to touch the templates as we clang-format the output of code generation.  Probably it is still picking up the wrong version.

**Comment by hzeller** [comment]
what I mean with fix the templates is, that the `#include <vector>` needs to go into these or the generator script. Currently exploring how that is done.

**Comment by maliberty** [comment]
Yes in that case you'll need to adjust the templates to add the include.

**Comment by hzeller** [comment]
closing this for now, will have a closer look if I find time during the holidays.

**Pull request closed without merging**
