### PR TITLE
grt: clang-format

### PR DESCRIPTION
**Pull request by eder-matheus**
Signed-off-by: Eder Monteiro <emrmonteiro@inf.ufrgs.br>

### CODE REVIEW

**Review by maliberty — APPROVED** [review]
I'll approve on the idea that you are just formatting but you need to address the build issue.

**Comment by eder-matheus** [comment]
> I'll approve on the idea that you are just formatting but you need to address the build issue.

The issue was with the `GlobalRouter.i` file. clang-formating leads to the build issue, but my latest commit should fix it.

**Comment by eder-matheus** [comment]
@maliberty I don't get this error on the macOS build:

```
/Users/openroad/github-action-runners/actions-runner-0/_work/OpenROAD/OpenROAD/src/odb/src/lef/lef/lefrReader.cpp:319:14: error: use of undeclared identifier 'lefyyparse'
cd /Users/openroad/github-action-runners/actions-runner-0/_work/OpenROAD/OpenROAD/build/third-party/abc && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -I/Users/openroad/github-action-runners/actions-runner-0/_work/OpenROAD/OpenROAD/third-party/abc/src -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -Wall -Wno-array-bounds -Wno-nonnull -Wno-unused-variable -Wno-unused-function -Wno-write-strings -Wno-sign-compare -Wno-deprecated -Wno-c++11-narrowing -Wno-register -Wno-format -Wno-reserved-user-defined-literal -DABC_USE_STDINT_H=1 -DABC_MEMALIGN=4 -DABC_NAMESPACE=abc -fpermissive -DABC_USE_CUDD=1 -DABC_USE_PTHREADS -std=c++17 -MD -MT third-party/abc/CMakeFiles/libabc.dir/src/base/abci/abcBidec.c.o -MF CMakeFiles/libabc.dir/src/base/abci/abcBidec.c.o.d -o CMakeFiles/libabc.dir/src/base/abci/abcBidec.c.o -c /Users/openroad/github-action-runners/actions-runner-0/_work/OpenROAD/OpenROAD/third-party/abc/src/base/abci/abcBidec.c
    status = lefyyparse();
             ^
1 error generated.
make[2]: *** [src/odb/src/lef/CMakeFiles/lef.dir/lef/lefrReader.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

I don't see this error on my mac. Did you see something like this before?

**Comment by maliberty** [comment]
You should not use clang-format on the .i file as it isn't really c++

**Comment by maliberty** [comment]
> @maliberty I don't get this error on the macOS build:
> 
> ```
> /Users/openroad/github-action-runners/actions-runner-0/_work/OpenROAD/OpenROAD/src/odb/src/lef/lef/lefrReader.cpp:319:14: error: use of undeclared identifier 'lefyyparse'
> cd /Users/openroad/github-action-runners/actions-runner-0/_work/OpenROAD/OpenROAD/build/third-party/abc && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -I/Users/openroad/github-action-runners/actions-runner-0/_work/OpenROAD/OpenROAD/third-party/abc/src -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -Wall -Wno-array-bounds -Wno-nonnull -Wno-unused-variable -Wno-unused-function -Wno-write-strings -Wno-sign-compare -Wno-deprecated -Wno-c++11-narrowing -Wno-register -Wno-format -Wno-reserved-user-defined-literal -DABC_USE_STDINT_H=1 -DABC_MEMALIGN=4 -DABC_NAMESPACE=abc -fpermissive -DABC_USE_CUDD=1 -DABC_USE_PTHREADS -std=c++17 -MD -MT third-party/abc/CMakeFiles/libabc.dir/src/base/abci/abcBidec.c.o -MF CMakeFiles/libabc.dir/src/base/abci/abcBidec.c.o.d -o CMakeFiles/libabc.dir/src/base/abci/abcBidec.c.o -c /Users/openroad/github-action-runners/actions-runner-0/_work/OpenROAD/OpenROAD/third-party/abc/src/base/abci/abcBidec.c
>     status = lefyyparse();
>              ^
> 1 error generated.
> make[2]: *** [src/odb/src/lef/CMakeFiles/lef.dir/lef/lefrReader.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> ```
> 
> I don't see this error on my mac. Did you see something like this before?

I'm guessing there is more error message somewhere above as that seems incomplete.

**Comment by maliberty** [comment]
I don't see that message in https://github.com/The-OpenROAD-Project/OpenROAD/actions/runs/3441135922/jobs/5740427304 - where did you copy it from?

**Comment by eder-matheus** [comment]
> status = lefyyparse();

It is from this link, around line 402.

**Comment by maliberty** [comment]
I found it
```
2022-11-10T23:19:26.9047440Z /Users/openroad/github-action-runners/actions-runner-0/_work/OpenROAD/OpenROAD/src/odb/src/lef/lef/lefrReader.cpp:319:14: error: use of undeclared identifier 'lefyyparse'
```
I don't see how grt could affect odb so it is mysterious.  I've restarted the action but perhaps @vvbandeira has some ideas.

**Comment by maliberty** [comment]
@vvbandeira something has changed on the mac build.  I looked at https://github.com/The-OpenROAD-Project/OpenROAD/pull/2481 from two days ago and I see in https://pipelines.actions.githubusercontent.com/serviceHosts/0e85c22b-57c2-4209-9b54-a3eaf4fc9b50/_apis/pipelines/1/runs/93537/signedlogcontent/2?urlExpires=2022-11-11T00%3A13%3A13.2393551Z&urlSigningMethod=HMACV1&urlSignature=CWN6IbeHY6DJzcXInLIb33UE234ykp1O4SdZBIRK3Z4%3D

```
Found BISON: /opt/homebrew/Cellar/bison/3.8.2/bin/bison (found version "3.8.2") 
Found FLEX: /opt/homebrew/Cellar/flex/2.6.4_2/bin/flex (found version "2.6.4") 
```

but in this PR https://pipelines.actions.githubusercontent.com/serviceHosts/0e85c22b-57c2-4209-9b54-a3eaf4fc9b50/_apis/pipelines/1/runs/93710/signedlogcontent/2?urlExpires=2022-11-11T00%3A12%3A21.9197907Z&urlSigningMethod=HMACV1&urlSignature=lQPsFZmUwOptleYdPUtyK%2BhHMQfzDzKaBXQ%2BiSQP%2Fkw%3D
```
Found BISON: /usr/bin/bison (found version "2.3") 
Found FLEX: /usr/bin/flex (found version "2.6.4") 
```

**Comment by rovinski** [comment]
Yes, I have run into this error several times and it comes from accidentally using the MacOS system version of bison instead of the one installed by homebrew.

**Comment by vvbandeira** [comment]
@maliberty fixed, env of the runner was misconfigured as @rovinski suggested

**Pull request merged**
