### PR TITLE
pdn: create block via arrays for techvias to reduce instance count

### PR DESCRIPTION
**Pull request by gadfort**
Changes:
- if techvia requires rows or columns it will be built as a blockvia to avoid generating a huge number of SBoxes for vias.
- updated tests that were impacted by the change

@maliberty I would suggest running this in the secure-ci before merging. I hand checked a bunch of vias, to see that they were the same, but it's possible I missed something.

### CODE REVIEW

**Comment by maliberty** [comment]
@eder-matheus please start a secure CI

**Comment by eder-matheus** [comment]
> @eder-matheus please start a secure CI

Started it in the branch secure-pdn-generate-techvia-blockvias

**Comment by maliberty** [comment]
I have no code comments.  I'll leave it to @eder-matheus to approve/merge based on the CI.

**Comment by maliberty** [comment]
@gadfort any stats on odb file size?

**Comment by gadfort** [comment]
@maliberty do you have the script you used to generate the spreadsheet? The CI tests generate odb files that are fairly small so it's hard to tell. If you are able to rerun he megaboom example that would give a 1:1 comparison

**Review by eder-matheus — APPROVED** [review]
CI is passing.

**Pull request merged**
