### PR TITLE
drt: improve via selection

### PR DESCRIPTION
**Pull request by antonblanchard**
Restore part of commit a965d53f6e7d ("drt: improve via selection"), avoiding the GF14 specific changes.

### CODE REVIEW

**Comment by QuantamHD** [comment]
@antonblanchard particularly in GF12/14 the big vias that it tends to pick aren't legal outside the power grid. Should we maybe filter the list down to the list of vias that can pass DRC with a minwidth wire, or is adding the area check enough?

**Comment by maliberty** [comment]
Oddly similar to your other PR:

sky130hd microwatt (base)
  Flow reached last stage.
  Found 3 metrics failures.
      [ERROR] cts__timing__setup__ws__pre_repair fail test: -0.025965 >= 0.0
      [ERROR] cts__timing__setup__ws__post_repair fail test: -0.025798 >= 0.0
      [ERROR] finish__timing__setup__ws fail test: -2.17081 >= -1.76

**Comment by antonblanchard** [comment]
> Oddly similar to your other PR:
> 
> sky130hd microwatt (base) Flow reached last stage. Found 3 metrics failures. [ERROR] cts__timing__setup__ws__pre_repair fail test: -0.025965 >= 0.0 [ERROR] cts__timing__setup__ws__post_repair fail test: -0.025798 >= 0.0 [ERROR] finish__timing__setup__ws fail test: -2.17081 >= -1.76

I wonder if something is up with the CI test. I tested sky130hd/microwatt (baseline vs patched) and the final def and metrics were identical

**Comment by antonblanchard** [comment]
> @antonblanchard particularly in GF12/14 the big vias that it tends to pick aren't legal outside the power grid. Should we maybe filter the list down to the list of vias that can pass DRC with a minwidth wire, or is adding the area check enough?

This should help because it will penalise vias that have large bar sized cut areas. However, considering the original patch broke the CI, I guess there is more filtering that needs to be done.

**Pull request merged**
