### PR TITLE
rsz: clang-format

### PR DESCRIPTION
**Pull request by eder-matheus**

### CODE REVIEW

**Comment by eder-matheus** [comment]
@maliberty I'm not sure if there is a reason why all these files were not clang-formatted before, but I noticed a bunch of this while investigating resizer and decided to fix that before any other code update.

**Comment by maliberty** [comment]
We should wait for https://github.com/The-OpenROAD-Project/OpenROAD/pull/3896 to finish

**Comment by QuantamHD** [comment]
I wonder if this is an actual bug

image

**Comment by maliberty** [comment]
@QuantamHD I don't think its a bug as swapping is a commutative operation so it doesn't really matter.  You could make tidy happy by swapping the call

**Comment by maliberty** [comment]
This is a good idea but the PR is so old it would be good to redo it on the current head.

**Pull request closed without merging**
