### PR TITLE
grt: detect and fix invalid embedded trees

### PR DESCRIPTION
**Pull request by eder-matheus**

### CODE REVIEW

**Comment by maliberty** [comment]
You missed the DCO

**Comment by maliberty** [comment]
Does this resolve the crossing case we discussed last thursday?

**Comment by eder-matheus** [comment]
> Does this resolve the crossing case we discussed last thursday?

Not yet. Since the crossing case will require even more updates in the code, I want to review what I have stable now before the fix for the crossing edges.

**Comment by eder-matheus** [comment]
Closing this PR due to some unrelated changes that should not be here.

**Pull request closed without merging**
