### PR TITLE
Add ioplacer

### PR DESCRIPTION
**Pull request by mpfogaca**
Integrates ioPlacer into OpenRoad app

### CODE REVIEW

**Comment by tspyrou** [comment]
I don't see code for the top level tcl command, I think we should call it place_io

**Comment by mpfogaca** [comment]
Hi, Tom.

The top level command is in ioPlacer.tcl
https://github.com/The-OpenROAD-Project/ioPlacer/blob/openroad_app/src/ioPlacer.tcl

We are currently calling run_io_placement. I can rename it if you want.

Thanks,
--Mateus

**Comment by mpfogaca** [comment]
Sorry, I accidentally close the pull request..

**Comment by tspyrou** [comment]
Got it thanks. Go ahead and merge this to develop. If cherry has any comments we can make an update later. It looks pretty clean to me.

**Comment by jjcherry56** [comment]
This is a major enough change I really think it should have been done on a
branch for review before merging it into the main development branch.

I would really like to see boost and OpenMP dependence removed.
At this point I cannot build OpenROAD on OSX because of these dependencies.
I just removed similar pointless dependencies in replace.
................
does ioplace really need OpenMP?
I cannot imagine there is enough computation in io placement to warrent
using multiple threads.
................
this may look pretty:
sta::define_cmd_args "run_io_placement" {[-hor_layer h_layer] \
                                         [-ver_layer v_layer] \
                                         [-random]            \
}


but it messes up the help command output.
remove extra spaces

sta::define_cmd_args "run_io_placement" {[-hor_layer h_layer]\
                                         [-ver_layer v_layer]\
                                         [-random]\
}

....
8 space indentation is super ugly and assumes very wide editor screens.
Use 2 spaces.

proc run_io_placement { args } {
        sta::parse_key_args "run_io_placement" args \
        keys {-hor_layer -ver_layer} flags {-random}

        if { [info exists flags(-random)] } {
                ioPlacer::set_rand_seed 42
                ioPlacer::set_random_mode 2
        }

....

I am no fan of "run_io_placement" as a command name.
i suggest "place_io_pins".

....

There is no excuse to use a cast here:
  ioPlacer_ = (ioPlacer::IOPlacementKernel*) makeIoplacer();
return the right type
Do you see any of the other examples doing casts? Of course not.

....
why is the repo called "FastRoute4-lefdef"?
It is way too verbose and does NOT even use lefdef anymore.

**Comment by rovinski** [comment]
Re: tcl command name: maybe we can use "place_io"? It is the Avatar-sanctioned command name. I also agree that the repository name should probably drop "lefdef" at this point.

**Pull request merged**
