### PR TITLE
Updating lef parser from 2017 to 2020

### PR DESCRIPTION
**Pull request by fgaray**
This is an update of lef parser from the version of 2017 to the 2020 version. It passed the regressions in my system and also fixed some memory leaks that I was investigating with -fsanitize=leak:

Previous:
```
SUMMARY: LeakSanitizer: 98232 byte(s) leaked in 2017 allocation(s).
```

After updating:
```
SUMMARY: LeakSanitizer: 104 byte(s) leaked in 4 allocation(s).
```

2 of the last memory leaks are unrelated to the parser. 

Procedure: I updated the library at the beginning of the code history and then rebased master over it to replay the commits that were in openroad.

Some questions:
* Do we want to clang-format this code?
* There are several warnings, do we want to fix them now or post PR?

### CODE REVIEW

**Comment by fgaray** [comment]
@QuantamHD Could you please take a look?

**Comment by QuantamHD** [comment]
Taking a look.

**Comment by maliberty** [comment]
I see some compile errors:
```
/tmp/workspace/OpenROAD-Public_PR-3469-head/src/odb/src/lef/lef/lefiDebug.cpp: In function ‘void LefDefParser::lefiError(int, int, const char*)’:
/tmp/workspace/OpenROAD-Public_PR-3469-head/src/odb/src/lef/lef/lefiDebug.cpp:97:28: error: format not a string literal and no format arguments [-Werror=format-security]
         fprintf(stderr, str);
                            ^
/tmp/workspace/OpenROAD-Public_PR-3469-head/src/odb/src/lef/lef/lefiDebug.cpp: At global scope:
/tmp/workspace/OpenROAD-Public_PR-3469-head/src/odb/src/lef/lef/lefiDebug.cpp:390:20: error: redundant redeclaration of ‘const char* LefDefParser::lefUpperCase(const char*)’ in same scope [-Werror=redundant-decls]
 extern const char *lefUpperCase(const char *c);
                    ^~~~~~~~~~~~
/tmp/workspace/OpenROAD-Public_PR-3469-head/src/odb/src/lef/lef/lefiDebug.cpp:360:1: note: previous declaration of ‘const char* LefDefParser::lefUpperCase(const char*)’
 lefUpperCase(const char *str)
 ^~~~~~~~~~~~
```

You have good git-fu.  Do you think formatting the code would make it harder to take future updates?

**Comment by maliberty** [comment]
Please go ahead and format it to resolve "Format Code with pre commit trigger "

**Comment by fgaray** [comment]
Hi @maliberty ,

Could it be possible to re-run the github action for "Build on macOS"?

I don't think my last change (clang-format) would make clang to crash:

image

Or do I just send a dummy commit to re-trigger it?

**Comment by maliberty** [comment]
I've trigger the mac build again.

**Comment by QuantamHD** [comment]
@maliberty Ready to go?

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
Is there no version later than 2020?

**Comment by QuantamHD** [comment]
These were the files you provided me. Could you check your original source?

**Pull request merged**
