### PR TITLE
Add TritonPart and remove MLPart

### PR DESCRIPTION
**Pull request by ZhiangWang033**
I made following changes:  (1) removed the MLPart (2) Add TritionPart (3) integrate HierRTLMP with TritonPart.  (4) Update the parameter settings in HierRTLMP

### CODE REVIEW

**Comment by maliberty** [comment]
Please address the unit test failures:
image

**Comment by maliberty** [comment]
also "This branch has conflicts that must be resolved"

**Comment by rovinski** [comment]
image
image

**Comment by maliberty** [comment]
I don't think 
image
 should be included

**Comment by vvbandeira** [comment]
Since there are commits that add 12M and the current state of the PR adds "only" 19k lines, we should consider squashing this merge once it is approved.

**Comment by maliberty** [comment]
@vvbandeira I agree but will there be any issue with pulling that squashed commit back into the fork?

**Comment by ZhiangWang033** [comment]
I will remove the regression test,  so there will not be so many changes.

-- Zhiang

**Pull request closed without merging**
