### PR TITLE
Update to latest OpenSTA

### PR DESCRIPTION
**Pull request by openroadie**

### CODE REVIEW

**Comment by openroadie** [comment]
Marking DCO as passed (sorry for forgetting about this).

**Comment by openroadie** [comment]
@tspyrou @maliberty : PR to get the latest OpenSTA code. I have already run all regressions locally and they passed.

**Comment by oharboe** [comment]
> @tspyrou @maliberty @oharboe : PR to get the latest OpenSTA code. I have already run all regressions locally and they passed.

Great! Since I have already tested this, I will wait for it to go into master before trying to upgrade our build server.

**Comment by openroadie** [comment]
Seems to have CI/CD issues @vvbandeira 

+ ./etc/Build.sh -no-warnings
/tmp/workspace/OpenROAD-Public_PR-3167-head@tmp/durable-b1abb3ae/script.sh: line 1: ./etc/Build.sh: No such file or directory
script returned exit code 1

**Review by maliberty — APPROVED** [review]

**Comment by vvbandeira** [comment]
> Seems to have CI/CD issues @vvbandeira
> 
> * ./etc/Build.sh -no-warnings
>   /tmp/workspace/OpenROAD-Public_PR-3167-head@tmp/durable-b1abb3ae/script.sh: line 1: ./etc/Build.sh: No such file or directory
>   script returned exit code 1

Do you have a link @openroadie ? Looks like it is all passing:
image

**Pull request merged**
