### PR TITLE
[Docs] Addtool patch

### PR DESCRIPTION
**Pull request by luarss**
@vvbandeira @maliberty 

This addresses the issue in https://github.com/The-OpenROAD-Project/OpenROAD/discussions/3735#discussioncomment-6569842

How it works: Instead of manually maintaining the `AddTool.patch` file I separated into static file `AddToolFiles.patch` and dynamic file `AddTool.patch`, the latter will be programmatically generated by running `python getPatch.py`.

### CODE REVIEW

**Review by vvbandeira — COMMENTED** [review]
The idea of making this process more programmatic and future-proof is great, but this approach has an unnecessary level, in my opinion. If we generate the patch file on the fly, doesn't it make more sense to directly apply it or modify the files and let the user review and make the final commit? Example: running `./add_tool.py --name NewShiningTool --abbrev nst ...` would create the folder in `src/nst` add to CMake, create a README, etc.

Note: This is a rare occurrence, so it should be a stretch goal for the GSoC project with very low priority.

**Comment by luarss** [comment]
But in the meantime, would we need to update the patch file?

**Comment by vvbandeira** [comment]
> But in the meantime, would we need to update the patch file?

Yes, please update it once and also include the correct command to apply the patch.

**Comment by luarss** [comment]
@vvbandeira Removed the references to python script.

**Comment by luarss** [comment]
@vvbandeira Ready for review

**Review by vvbandeira — APPROVED** [review]

**Pull request merged**
