### PR TITLE
ant: consider violations in cut layers for repair_antennas

### PR DESCRIPTION
**Pull request by eder-matheus**
Partially fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/5325

The ant API was not returning violations related to CUT layers, leading to the mismatch between the repair_antennas report and the check_antennas report. This simple update fixes it, and the mismatch reported in the issue is not happening anymore (all violations are fixed).

### CODE REVIEW

**Comment by maliberty** [comment]
What does it mean to have a violation on a cut layer?

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
I'm ok with this as a solution to the current problem but separately I want to clarify what the checker is checking.

**Comment by eder-matheus** [comment]
> What does it mean to have a violation on a cut layer?

The violation that repair_antennas wasn't seeing was a PAR violation in the cut layer via4. The calculated PAR on that layer was higher than the allowed. We were not checking the cut layers in the ant code, so repair_antennas never knew such a violation existed. Now, we are returning PAR violations on both routing and cut layers.

**Comment by eder-matheus** [comment]
> I'm ok with this as a solution to the current problem but separately I want to clarify what the checker is checking.

Does my last comment clarify this or do you have other questions about the ant check?

**Comment by maliberty** [comment]
I didn't think we have par/car values on cut layers.  Is there a PDK that has those?

**Comment by eder-matheus** [comment]
> I didn't think we have par/car values on cut layers.  Is there a PDK that has those?

The design that had the violation was sky130hd/ibex. I didn't check the LEF, but I believe I also saw PAR values in cut layers for ihp platform.

**Comment by eder-matheus** [comment]
Here's the LEF definition for via4 in sky130hd:
image

**Comment by maliberty** [comment]
You would think the area on the cut layer would be rather small.  I guess such violation occur based on this PR but I'm surprised.

**Pull request merged**
