### PR TITLE
gui: allow layout view to be dragged while holding middle mouse button

### LINKED ISSUE #3840: Add ability to drag the view with the mouse
It would make moving around the design a lot easier.

The arrow keys is a bit clunky compared to dragging the view with the mouse.

_Originally posted by @oharboe in https://github.com/The-OpenROAD-Project/OpenROAD/discussions/3812_

### PR DESCRIPTION
**Pull request by AcKoucher**
Resolves #3840

Layout can be dragged by holding middle mouse button like in KLayout.

### CODE REVIEW

**Comment by maliberty** [comment]
I observed some strange scrolling if I first create a ruler and then immediately middle mouse drag.  I think those two features are interacting in an odd way.

**Comment by oharboe** [comment]
I tried it on a Dell laptop. Use two fingers on the touchpad and drag the view around :+1:

**Comment by AcKoucher** [comment]
I pushed a change to prevent dragging when the rubber band is showing (used KLayout as reference)

@maliberty I couldn't notice any strange scrolling when creating a ruler and then immediately middle mouse dragging. Could you please describe the weird scrolling?

**Comment by oharboe** [comment]
@AcKoucher Works great! :+1:

**Comment by maliberty** [comment]
I demo'ed the ruler problem to @AcKoucher yesterday so this will hold until it can be resolved.

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
I realized the problem I was seeing could happen even without the ruler.  My middle mouse wheel can also tilt left/right and I was getting a combination of hold and tilt causing the left scrolling.

**Pull request merged**
