### PR TITLE
odb: Fixes more ubsan violations in odb

### PR DESCRIPTION
**Pull request by QuantamHD**
std::memcpy instead of unsafe casts.

### CODE REVIEW

**Comment by QuantamHD** [comment]
@maliberty looks like there's something wrong with the ci runner

**Comment by maliberty** [comment]
> @maliberty looks like there's something wrong with the ci runner

"Timeout has been exceeded"

**Comment by maliberty** [comment]
What makes the casts unsafe?

**Comment by maliberty** [comment]
I restarted the failed step to see if it times out again

**Comment by QuantamHD** [comment]
> What makes the casts unsafe?


```
  uint32_t* flags__bit_field = (uint32_t*) &obj.flags_;
  stream >> *flags__bit_field;
```

Is a violation of strict aliasing. https://gist.github.com/shafik/848ae25ee209f698763cffee272a58f8

**Comment by QuantamHD** [comment]
I guess union type punning is also UB in C++, but not C. So I changed to std::memcpy which I guess is the only legal way to do this in C++

**Comment by QuantamHD** [comment]
Added some static asserts to ensure things are the right size

**Comment by QuantamHD** [comment]
I think the clang tidy is confused.

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
Note that this PR is only addressing the problem in code the use the code generator.  Older code is still 'wrong' eg 
```
dbOStream& operator<<(dbOStream& stream, const _dbBTerm& bterm)
{
  uint* bit_field = (uint*) &bterm._flags;
  stream << *bit_field;
````

**Pull request merged**
