### PR TITLE
Print error when resizer is unable to repair all setup violations

### PR DESCRIPTION
**Pull request by antonblanchard**

### CODE REVIEW

**Comment by antonblanchard** [comment]
We print an error when we run out of space when fixing setup and hold violations, but print nothing if we give up because we aren't making forward progress in setup repair. Our subsequent timing analysis will show up any issues, but it's useful to know what went wrong.

**Comment by maliberty** [comment]
You need to update the messages.txt file using etc/FindMessages.tcl

**Review by jjcherry56 — COMMENTED** [review]
Errors throw an error and abort the command script.
I don't think that is appropriate behavior.
I could see adding a warning, but not an error

**Comment by antonblanchard** [comment]
Thanks for the review.

> You need to update the messages.txt file using etc/FindMessages.tcl

@maliberty I updated messages.txt.

> Errors throw an error and abort the command script.
> I don't think that is appropriate behavior.
> I could see adding a warning, but not an error

@jjcherry56 Makes sense, I changed it to a warning.

**Comment by jjcherry56** [comment]
At some point the logger will have a command to remap message severity so you could change it.

**Pull request merged**
