### PR TITLE
Recover power

### PR DESCRIPTION
**Pull request by openroadie**
Improvements to recover power flow 

- All paths are now optimized
- Percent option to setting may be kept for runtime reasons for large designs (not sure about this yet)
- Once this PR and the corresponding ORFS PR is merged, will enable more designs to use this feature.
- General cleanup of unused code/variables etc.

### CODE REVIEW

**Comment by openroadie** [comment]
@QuantamHD some improvements based on your feedback on testing. PR in draft status so I can check how the OR and  ORFS CI/CD performs with this change before I ask for reviews :). 

cc: @tspyrou

**Comment by openroadie** [comment]
ORFS results here:

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1388

**Comment by maliberty** [comment]
I have no code comments.  Please work with @vvbandeira to verify the CI (including secure CI) passes with this change.  If so, he can approve/merge.

**Comment by openroadie** [comment]
> I have no code comments. Please work with @vvbandeira to verify the CI (including secure CI) passes with this change. If so, he can approve/merge.

Will do. FWIW this code is not even called on any design in the secure CI so I do not quite see how running secure CI would provide any useful data on quality.

**Comment by maliberty** [comment]
> Will do. FWIW this code is not even called on any design in the secure CI so I do not quite see how running secure CI would provide any useful data on quality.

ok - though I wonder if it should be.

**Comment by openroadie** [comment]
Alright. I will enable a couple of GF12 tests to do power recovery :).

**Comment by openroadie** [comment]
> Alright. I will enable a couple of GF12 tests to do power recovery :).

Matching private OR/ORFS PRs are created and going through CI/CD. Added secure CI/CD tests to test power recovery.

**Comment by vvbandeira** [comment]
Replaced by #3897 to match sha in ORFS.

**Pull request closed without merging**
