### PR TITLE
fix: Add missing gTest dependency

### PR DESCRIPTION
**Pull request by openroadie**

### CODE REVIEW

**Comment by maliberty** [comment]
lgtm - @vvbandeira approve if you have no concerns

**Comment by openroadie** [comment]
@maliberty gtest did not auto install on my Ubuntu 20.04 machine. I had to manually install it.

**Review by vvbandeira — APPROVED** [review]

**Comment by gadfort** [comment]
@maliberty I was having the same issue on my Ubuntu 20. @openroadie  Thanks for fixing

**Comment by maliberty** [comment]
The problem was fixed in https://github.com/The-OpenROAD-Project/OpenROAD/pull/3047 however if you had a build where gtest was installed you would continue to have this issue.  Removing install/OpenROAD will fix up an existing workspace.

**Pull request merged**
