### PR TITLE
DO NOT MERGE. Test for mermaid anchor fix

### PR DESCRIPTION
**Pull request by luarss**
This fixes the issue in https://github.com/The-OpenROAD-Project/OpenROAD/pull/3631

where the rendering of mermaid diagrams will cause misalignment in anchor links.

### CODE REVIEW

**Comment by luarss** [comment]
@vvbandeira @dralabeing

DRT Link
https://openroad--3743.org.readthedocs.build/en/3743/main/src/drt/README.html

Regression Tests Link [Now links correctly]
https://openroad--3743.org.readthedocs.build/en/3743/main/README.html#regression-tests

**Review by vvbandeira — CHANGES_REQUESTED** [review]
Can we increase the resolution of the generated images and improve the contrast? The "white" text no longer looks white. Could we also use transparent background so the image shows better in both light and dark themes?

### Before
image

### After
image

**Comment by vvbandeira** [comment]
@luarss I think the RTDs action will still run even as a draft, but if you feel the need, you can convert to non-draft.

**Comment by luarss** [comment]
For some reason the RTD automatic documentation is stuck on the 20th commit. Not sure if this is an issue with RTD servers, will check back later

**Comment by vvbandeira** [comment]
@luarss looks to be working, as far as I can tell. From newest to oldest:
https://readthedocs.org/projects/openroad/builds/21458242/
https://readthedocs.org/projects/openroad/builds/21458073/
https://readthedocs.org/projects/openroad/builds/21458008/
https://readthedocs.org/projects/openroad/builds/21457890/

**Comment by luarss** [comment]
image

When you click on `was created` it brings you to the build made in 20th commit where I changed the render format to png. Subsequent PRs are not working.

**Pull request closed without merging**
