### PR TITLE
 Initial CCS Calculator Working Doc ⌚

### PR DESCRIPTION
**Pull request by QuantamHD**
The inital documentation and implementation ideas for the CCS calculator. Currently worked on by ethanmoon@google.com and dinoruic@google.com :)

We hope others add to the implementation ideas over time.

```
    A Clock Stopped -- Not The Mantel's;
    Geneva's farthest skill
    Can't put the puppet bowing
    That just now dangled still.

    An awe came on the trinket!
    The figures hunched with pain,
    Then quivered out of decimals
    Into degreeless noon.

    It will not stir for doctors,
    This pendulum of snow;
    The shopman importunes it,
    While cool, concernless No

    Nods from the gilded pointers,
    Nods from the seconds slim,
    Decades of arrogance between
    The dial life and him.

-Emily Elizabeth Dickinson
```

Signed-off-by: Ethan Mahintorabi <ethanmoon@google.com>

### CODE REVIEW

**Comment by QuantamHD** [comment]
@maliberty It looks like the security scan is getting mad at the base64 encoded image

**Comment by maliberty** [comment]
I can add a security exception for ipynb files thought it looks like scan will need one too @habibayassin @vvbandeira

**Comment by maliberty** [comment]
It is possible to open this directly in colab?

**Comment by QuantamHD** [comment]
@maliberty Updated the README with a direct link to Colab

**Comment by QuantamHD** [comment]
Wrong link was provided above https://colab.sandbox.google.com/github/QuantamHD/OpenROAD/blob/ccs_calculator/src/ccs/ccs_calculator.ipynb

**Comment by maliberty** [comment]
I believe Cherry is now working on CCS so I don't think this is still relevant.

**Pull request closed without merging**
