### PR TITLE
delta_debug: reduce review noise by getting some simple formatting changes in

### PR DESCRIPTION
**Pull request by oharboe**
Broke out some changes from https://github.com/The-OpenROAD-Project/OpenROAD/pull/5223 top make review easier.

@maliberty We need to pick some Python code formatting standard and add that to the repository, otherwise "format source code" is going to give different results depending on locally configured Python IDE...

### CODE REVIEW

**Comment by oharboe** [comment]
@maliberty Picked some formatting rules as a starting point. Fairly forgiving, can be tightened. Only one "flake8 ." error now(a bit tricky to fix because it has to do with mocking and imports, so beyond this PR).

**Comment by oharboe** [comment]
@habibayassin FYI

**Comment by maliberty** [comment]
I would pick black over yapf.  flake8 is fine.

**Comment by oharboe** [comment]
> I would pick black over yapf. flake8 is fine.

Sounds good to me, I havent used it.  

Could you institute it?

**Comment by oharboe** [comment]
@maliberty Instituting black makes this PR moot

**Pull request closed without merging**
