### PR TITLE
Fix compiling error with GCC v13.

### PR DESCRIPTION
**Pull request by andreili**
To fix issue: https://github.com/The-OpenROAD-Project/OpenROAD/issues/3450

### CODE REVIEW

**Review by maliberty — APPROVED** [review]
Thanks

**Comment by maliberty** [comment]
Please fix the clang-format error.  The includes are out of order.

**Comment by vvbandeira** [comment]
> @vvbandeira perhaps we can setup a gcc13 action similar to the c++20 which uses clang-16

Will add to the feature request list of CI refactoring.

**Comment by andreili** [comment]
@maliberty Fixed - invalid include order.

**Pull request merged**
