### PR TITLE
sta: ensure heatmap and renderer is installed

### PR DESCRIPTION
**Pull request by gadfort**
Changes:
- make sure the power density heatmap is available when invoked via `gui::show`

### CODE REVIEW

**Review by maliberty — APPROVED** [review]

**Comment by QuantamHD** [comment]
@gadfort This breaks my version of openroad when you don't build the GUI? I need to make sure that the register renderer is gated. How can we make sure both of our use cases work?

**Comment by gadfort** [comment]
@QuantamHD I suspect the issue is that stub.cpp isn't handling things correctly.

**Comment by gadfort** [comment]
What breakage are you seeing?

**Comment by QuantamHD** [comment]
Yeah I'm seeing a segfault, because GUI::GUI::get() returns nullptr

**Comment by gadfort** [comment]
Do you have a stacktrace for that?

**Comment by gadfort** [comment]
I think you will need to be more specific about the segfault, I'm not able to reproduce it

**Pull request merged**
