### PR TITLE
Add OpenPhySyn

### PR DESCRIPTION
**Pull request by ahmed-agiza**
- Integrated OpenPhySyn.
- Did some updates to the Dockerfile:
    - Updated GCC to 7.3.0.
    - Updated SWIG to 4.0.1

### CODE REVIEW

**Comment by tspyrou** [comment]
Hi Ahmed,
We don't want end users to have to install boost. Instead if you absolutely need a package, add the code to your submodule and build it there. That way we won't require all of boost to be installed by everyone when we use a small piece or require end users to install boost.

**Comment by ahmed-agiza** [comment]
No problem, I can ditch Boost.

**Comment by ahmed-agiza** [comment]
@tspyrou Boost has been removed.
@jjcherry56 Do you have any advice with or against explicitly using SWIG 4.0 in the Dockerfile rather than leaving the default one in the image (2.0)?

**Comment by jjcherry56** [comment]
I am currently using swig 4.0 without issues.
I don't have a problem with updating it but would be a bit concerned if you
actually depend on latest and greatest features in it.

**Comment by ahmed-agiza** [comment]
The tool compiles fine with SWGI 3.0, I just upgraded it to 4.0 to reduce the gap for future updates.

**Comment by abdelrahmanhosny** [comment]
Please, re-write the `Dockerfile`. It has a total size of `9+GB` which constantly blows up disk space usage.
`openroad/openroad       latest              13872ee18d6e        27 hours ago        9.35GB`

Each container spawned from this image is takes that much space. The original Dockerfile has less than 2GB of disk space
`openroad/openroad                               base                001b7e2af995        5 days ago          1.98GB`

Also, for this specific repo, can you add `--rm` to every `docker run` in `test.sh`? This will prevent the containers from just being there.

Thanks

**Pull request closed without merging**
