### PR TITLE
Add RePlAce/OpenDP unit testcases.

### PR DESCRIPTION
**Pull request by mgwoo**
Could you check this PR for RePlAce test cases?
I can't check Jenkins' behavior in my forked repo...

### CODE REVIEW

**Comment by mgwoo** [comment]
I can confirm that my testcases worked well in Jenkins.

**Comment by mgwoo** [comment]
The integrated OpenDP only has a problem with multi-height testcases. 
Other testcases (fence-region, simple-case, low-util) worked well.

**Comment by tspyrou** [comment]
I see this failure in jenkins.

Access or-multi-height-test-01:

  run_opendp.tcl

CMD: /OpenROAD/build/src/openroad or-multi-height-test-01/run_opendp.tcl

Compare with golden: 

Traceback (most recent call last):

  File "regression.py", line 140, in <module>

    Run("simple", prog, openroadList)

  File "regression.py", line 106, in Run

    SimpleGoldenCompare(rptFile, goldenFile)

  File "regression.py", line 49, in SimpleGoldenCompare

    f = open(orig, "r")

FileNotFoundError: [Errno 2] No such file or directory: 'or-multi-height-test-01/ten_cells_multi.rpt'

script returned exit code 1

**Comment by jjcherry56** [comment]
Use the edit button to change this to merge into develop instead of mastdr

**Pull request merged**
