### PR TITLE
[init_fp] tracks orientation fixed when not using a tracks_file

### PR DESCRIPTION
**Pull request by ax3ghazy**
Same as  #249. Please see the PR on ioPlacer mentioned there to know why the CI reports a failed testcase.

### CODE REVIEW

**Comment by ax3ghazy** [comment]
@jjcherry56: I went through the process you described in https://github.com/The-OpenROAD-Project/OpenROAD/pull/249#issuecomment-629570584, and I made sure that all regressions pass locally, so I am not really sure why Jenkins is complaining (I don't have access to see the error myself in case you think I do)....

**Comment by jjcherry56** [comment]
jenkins gets confused all too often. I just restarted the flow tests (circle arrow top right) and it passed.

**Comment by ax3ghazy** [comment]
Thanks! Now at least I know the process...

About the copyright, sorry about that; It must be my vim setup that removes trailing whitespaces on save.

**Comment by ax3ghazy** [comment]
Closed by mistake.

**Comment by jjcherry56** [comment]
now you need to merge the PR

**Pull request merged**
