### PR TITLE
mpl2: fix macro blockage penalty

### LINKED ISSUE #4780: mpl2 is placing macros too close to the IO pins
### Describe the bug

mpl2 macro blockage penalty is responsible for avoiding overlap between cluster with macros and macro blockages. Mpl2 "sees" pin access in the form of blockages whose shapes are computed during multilevel autoclustering stage.

_This penalty is not null even when there's no overlap._

### Expected Behavior

Macro blockage should be 0 when there's no overlap and macros should not be placed in the front of IO pins.

### Environment

```shell
head of Master
```

### To Reproduce

Run any design with macros with mpl2

### Relevant log output

_No response_

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by AcKoucher**
Fix #4780 

This PR is to:
1) Change the way we compute the penalty for overlapping between clusters with macros and macro blockages during SA for SoftMacros. We now just compute the overlapping area between the `SoftMacro` and the `macro_blockage`.
2) Adapt the calculation of cluster placement penalties (SoftSA) to the fixed sequence pair.
3) Ensure we actually use the new sequence pair in when running enhanced macro placement function.

_For documentation: Not only were we using an overly complex expression to compute the penalty, but there was also a bug: even when there was no overlap, the computed `macro_blockage_penalty` between a `SoftMacro` and a `macro_blockage` was different from 0, because, even if the ratio of one of the coordinates was 0 the other one was not. This was due to way std::max was being used in the ratio of each coordinate._

_To keep the original computing, we would have to ensure that, if there was no overlap between a `SoftMacro` and a`macro_blockage` in any of the coordinates, the penalty would be 0._

### CODE REVIEW

**Comment by maliberty** [comment]
This could be simpler 
image
(https://www.geeksforgeeks.org/total-area-two-overlapping-rectangles/#)

**Comment by AcKoucher** [comment]
Running CI

**Comment by AcKoucher** [comment]
@maliberty 
Failures in Secure CI:

asap7/riscv32i: [ERROR] finish__timing__setup__ws fail test: -203.771 >= -180.41

**Comment by maliberty** [comment]
asap7 is public so you can take a look yourself.

**Comment by AcKoucher** [comment]
Once [#1641](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1641) is merged, I'll running Secure-CI again for this.

**Comment by maliberty** [comment]
#1641 is merged - is this ready to re-test?

**Comment by AcKoucher** [comment]
@maliberty After merging  [#1641](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1641), I ran Secure-CI again and got a failure in gf12/ariane during macro placement (the latter didn't finished).

Digging into to it resulted in opening #4354, as I showed you that we were actually getting a valid solution for macro placement during SA, but not using it.

Then when running CI for #4354 I got two problems:
1. Degradation in asap7/riscv32i metrics again;
2. 1 DRC in asap7/aes-block.

My next step was to combine this PR with #4354 to and run another Secure-CI.

In this last run, asap7/riscv32i metrics degradation was gone, but the DRC kept there.

As discussed in the R&D synch, the suggestion was that I tried to increase the halos a little bit (too bigger halos would imply problems in yosys update - that's the reason they were reduced).

Yesterday I increased the halos from 5 5 -> 7 7 and ran Secure-CI once more. The results were:

I got not only 1 DRC, but 3 in asap7/aes-block and some DRT warnings.

After talking to @eder-matheus we decided to investigate the DRC generated in the case with halos 5 5. I'll be opening an issue soon for him to take a look.

**Comment by maliberty** [comment]
Thanks for the update

**Comment by AcKoucher** [comment]
@maliberty Updating: I'm running Secure-CI again for the changes here combined with the changes in #4354 now that #[1712](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1712) was merged.

**Comment by AcKoucher** [comment]
Running Secure-CI now that the macro dominance factor for macro blockages' depth was merged.

**Comment by AcKoucher** [comment]
Secure-CI after yosys update to 0.38:
```
 tsmc65lp/bp_fe: [ERROR DPL-0036] Detailed placement failed.

**Comment by AcKoucher** [comment]
@maliberty FYI

@eder-matheus took a look and apparently this is caused by the same RSZ issue that occurred in a private design a while ago when trying to merge these changes. Basically a lot of instances that were added in the lower right corner of the design can't be legalized.

**Comment by maliberty** [comment]
Do you have a screen shot of the problem?

**Comment by AcKoucher** [comment]
I ran Secure-Ci here once more hoping that the updates in #4704 would have some positive impact on the DPL failure, but it persists..

```
tsmc65lp bp_fe (base)
  Last log file 5_1_grt.log
  Found 1 errors in the logs.
      [ERROR DPL-0036] Detailed placement failed.

**Comment by AcKoucher** [comment]
Update: running CI again now that the rsz issue was resolved by #4746

**Comment by AcKoucher** [comment]
Secure-CI showed just one small metrics error for a private design apart from the failures that were on master and are already fixed.

**Comment by eder-matheus** [comment]
@AcKoucher @maliberty The PR updating the metrics of the failing design is here: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1842

**Comment by AcKoucher** [comment]
@maliberty  FYI I'm running Secure-CI here one more time here now that CI is stable.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
