### PR TITLE
ariane136 testcase added for mpl2

### PR DESCRIPTION
**Pull request by vijayank88**
Signed-off-by: vijayank88 <paruthi143@gmail.com>
Ariane136 design added as test case for `mpl2` with `rtl_macro_placer` command for `Nangate45` PDK.

### CODE REVIEW

**Comment by vijayank88** [comment]
@vvbandeira 
How to fix this error?
```

ERROR: File src/mpl2/test/testcases/ariane136/ariane.def is big but not whitelisted (hash 120940cef610e8ee698bb4b7572f84d3)

Running pre-commit security hook....
To request an exception please file an issue on GitHub
Error: Process completed with exit code 1.
```

**Comment by maliberty** [comment]
How long does this take to run?  It seems rather too large for a unit test and you are already adding it to ORFS

**Comment by vijayank88** [comment]
Run time around 40Mins.
Thought of adding macro heavy designs for test case.
It make sense as design available in ORFS, we can skip this. 
Leave it you for merge or skip it. Thanks

**Comment by maliberty** [comment]
That's much to long for a unit test

**Pull request closed without merging**
