### PR TITLE
colors: tweak default colors to work better on black background

### PR DESCRIPTION
**Pull request by oharboe**
Made some darker colors brighter and easier to see. A side-by-side review of all the colors needs to be done, I don't know exactly where to find them in the GUI though.

Before:

image

After:

image

### CODE REVIEW

**Comment by gadfort** [comment]
@oharboe it might be nice to have a side by side of all the color changes you are proposing

**Comment by maliberty** [comment]
Just brightening it will make it confusing with metal2

**Comment by oharboe** [comment]
Will have a look. Is that the only conflict?

**Comment by maliberty** [comment]
How were these colors derived?  Please make a before and after comparison images.

**Comment by oharboe** [comment]
> How were these colors derived? Please make a before and after comparison images.

I'm going to revert all color changes but the one that is most problematic. The others looked a bit darker to me too, but it is a bridge to far. The problem is to create lots of easy on the eye high contrast colors... Which is enormously tricky. :-)

**Comment by oharboe** [comment]
Instead of changing multiple colors, I've changed only metal 5 and tried to introduce an additional different base color, bright orange, that works on black background.

Before:

image



After:

image

**Comment by oharboe** [comment]
I'm going to try on more monitors, but on one either was OK, on my laptop the new scheme was definitely better.

**Comment by gadfort** [comment]
Attempting to keep the color similar with higher contract with the adjacent layers: `QColor(222, 33, 96)`

image

This preserves the relative contract between M4 / M6 and increases the contrast with the background (although not as much as the orange).

**Comment by oharboe** [comment]
Thanks! Will try on some more monitors.

**Comment by oharboe** [comment]
@gadfort Used your proposed color. Works better on the monitors I tried. :+1:

**Review by maliberty — APPROVED** [review]

**Pull request merged**
