### PR TITLE
gui: display message to inform that design is loading before first render

### LINKED ISSUE #3937: OpenROAD GUI doesn't show any progress indication when drawing the first time
### Description

2_5_floorplan_tapcell.odb in my case draws quickly:

image

2_6_floorplan_pdn.odb when ready and responding to zooming commands is just black...  No matter how far  I zoom in...

image

Eventually, I get something. After the image is drawn the first time, it responds in seconds in my case(ca. 5mm^2 megaboom design).

image

### Suggested Solution

There should be some sort of progress indication of rendering the first time, because the first time the renderinger takes a lot longer than subsequently. Perhaps go from busy & black screen, to showing "Rendering..."  when rendering the first time?

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by AcKoucher**
Resolves #3937

Just drawing a string in the center of the layout viewer.

### CODE REVIEW

**Comment by AcKoucher** [comment]
This is not working properly, I'll close the PR to investigate.

**Comment by AcKoucher** [comment]
This is ready for review.

**Comment by rovinski** [comment]
> This is not working properly, I'll close the PR to investigate.

Is `is_first_render_done_` a variable shared between threads? If it's not working as expected it could be because it's not declared as `std::atomic<bool>`.

**Comment by AcKoucher** [comment]
@rovinski Apparently it's working fine now. 
Previously I didn't realize that I could use the same thread run to draw the message, erase it and then draw the design. Before the last commit, we would have to wait for the subsequent run to draw the design, but, in some cases this run does not happen, e. g. when the .odb has little data and loads fast.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
