### PR TITLE
Grt: Avoiding iterating all gcells and nets

### PR DESCRIPTION
**Pull request by luis201420**
Avoiding iterating all gcells and nets in FastRoute functions by improving the incremental GRT runtime.

### CODE REVIEW

**Review by eder-matheus — APPROVED** [review]
@luis201420 Did you run a secure-ci?

**Comment by oharboe** [comment]
@luis201420 Can you say something about the motivation for this change? Make it faster? Refactor or cleanup for future changes? Any numbers on speedup?

Just curious.

**Comment by eder-matheus** [comment]
> @luis201420 Can you say something about the motivation for this change? Make it faster? Refactor or cleanup for future changes? Any numbers on speedup?
> 
> Just curious.

This is related to the Issue https://github.com/The-OpenROAD-Project/OpenROAD/issues/4407. He's investigating how to improve the runtime, looking for hotspots on the code. @luis201420 can add his initial results after this update, where he considerably reduced the runtime of the design attached to the issue.

**Comment by luis201420** [comment]
@oharboe I am investigating how to improve the runtime when executing incremental GRT, with this modification the `repairDesign` runtime for the issue design is reduced from 43660.50s to **37073.16s**  (a difference of ~**109min**).

**Pull request merged**
