### PR TITLE
FastRoute and tapcell unit tests update

### PR DESCRIPTION
**Pull request by eder-matheus**

### CODE REVIEW

**Comment by jjcherry56** [comment]
well the sed issue is gone but there is still a failure in the fastroute tests.
I don't think it is a great idea to spew diffs on a def file to the regression results.
the regression script I use just tells you there are diffs and where to find them.

CerezaBook> src/FastRoute/test/regression

************************
* FastRoute unit tests *
************************

 > FastRoute binary: /Users/cherry/sta/openroad/src/FastRoute/test/../../../build/src/openroad
 > Now running test_coverage...
     - [ERROR] Test failed. Check /Users/cherry/sta/openroad/src/FastRoute/test/src/test_coverage/test.log
     - Test returned RED (failed)
 > Now running test_guides...
3,5c3,6
< 113400 46200 117600 50400 metal2
< 113400 46200 121800 50400 metal3
< 117600 46200 121800 50400 metal2
---
> 88200 29400 92400 37800 metal2
> 88200 29400 92400 33600 metal1
> 100800 29400 105000 37800 metal2
> 100800 29400 105000 33600 metal1
7,8c8,17
< 121800 63000 126000 71400 metal2
< 121800 63000 126000 67200 metal1
---
> 117600 46200 121800 50400 metal2
> 109200 46200 121800 50400 metal3
> 109200 46200 113400 50400 metal2
> 109200 50400 117600 54600 metal1
> 54600 63000 63000 67200 metal1
> 100800 33600 105000 37800 metal2
> 100800 33600 113400 37800 metal3
> 109200 33600 113400 50400 metal2
> 151200 117600 155400 121800 metal1
> 151200 105000 155400 121800 metal2
13,16c22,24
< 50400 92400 54600 96600 metal1
< 50400 92400 54600 96600 metal2
< 50400 92400 58800 96600 metal3
< 54600 92400 58800 96600 metal2
---
> 151200 84000 155400 88200 metal1
> 151200 75600 155400 88200 metal2
> 151200 75600 155400 79800 metal1
19,21d26
< 151200 75600 155400 79800 metal1
< 151200 75600 155400 88200 metal2
< 151200 84000 155400 88200 metal1
29,32c34,36
< 151200 121800 155400 126000 metal2
< 151200 121800 159600 126000 metal3
< 155400 105000 159600 126000 metal2
< 155400 105000 159600 109200 metal1
---
> 134400 67200 138600 71400 metal1
> 134400 67200 138600 71400 metal2
> 126000 67200 138600 71400 metal3
37,40c41
< 151200 117600 155400 126000 metal2
< 151200 117600 155400 121800 metal1
< 134400 130200 138600 134400 metal1
< 134400 121800 138600 134400 metal2
---
> 130200 130200 138600 134400 metal1
63,65c64,66
< 58800 63000 63000 67200 metal1
< 58800 63000 63000 67200 metal2
< 58800 63000 75600 67200 metal3
---
> 54600 63000 58800 67200 metal1
> 54600 63000 58800 67200 metal2
> 54600 63000 75600 67200 metal3
69,70d69
< 54600 63000 63000 67200 metal1
< 54600 71400 58800 100800 metal2
72,83c71,82
< 50400 84000 54600 96600 metal2
< 88200 29400 92400 33600 metal1
< 88200 29400 92400 33600 metal2
< 88200 29400 105000 33600 metal3
< 100800 29400 105000 33600 metal2
< 100800 29400 105000 33600 metal1
< 100800 29400 117600 33600 metal3
< 113400 29400 117600 54600 metal2
< 113400 50400 117600 54600 metal1
< 113400 67200 117600 71400 metal2
< 113400 67200 126000 71400 metal3
< 113400 50400 117600 71400 metal2
---
> 50400 71400 54600 88200 metal2
> 50400 71400 58800 75600 metal1
> 50400 92400 54600 96600 metal1
> 50400 84000 54600 100800 metal2
> 50400 96600 58800 100800 metal3
> 88200 33600 92400 37800 metal2
> 88200 33600 105000 37800 metal3
> 121800 63000 126000 67200 metal1
> 121800 63000 126000 71400 metal2
> 109200 46200 113400 54600 metal2
> 109200 50400 113400 54600 metal1
> 109200 50400 113400 71400 metal2
86,92c85
< 109200 67200 117600 71400 metal3
< 109200 67200 113400 79800 metal2
< 126000 67200 138600 71400 metal3
< 134400 67200 138600 71400 metal2
< 134400 67200 138600 71400 metal1
< 134400 67200 155400 71400 metal3
< 151200 67200 155400 79800 metal2
---
> 109200 67200 126000 71400 metal3
95,96c88,93
< 75600 29400 79800 37800 metal2
< 75600 29400 92400 33600 metal3
---
> 109200 67200 113400 79800 metal2
> 151200 84000 155400 109200 metal2
> 151200 105000 159600 109200 metal3
> 155400 105000 159600 109200 metal2
> 155400 105000 159600 109200 metal1
> 75600 33600 92400 37800 metal3
113a111,117
> 151200 117600 155400 126000 metal2
> 130200 130200 134400 138600 metal2
> 130200 130200 134400 134400 metal1
> 130200 121800 134400 134400 metal2
> 134400 121800 138600 126000 metal2
> 134400 121800 155400 126000 metal3
> 151200 121800 155400 126000 metal2
117,119d120
< 134400 121800 138600 126000 metal2
< 134400 121800 155400 126000 metal3
< 130200 121800 134400 138600 metal2
132,133c133,136
< 163800 176400 168000 201600 metal2
< 163800 197400 189000 201600 metal1
---
> 163800 176400 168000 180600 metal2
> 163800 176400 189000 180600 metal3
> 184800 176400 189000 201600 metal2
> 184800 197400 189000 201600 metal1
249,251c252,254
< 172200 126000 189000 130200 metal3
< 184800 126000 189000 130200 metal2
< 184800 126000 200260 130200 metal1
---
> 172200 126000 200260 130200 metal3
> 193200 126000 200260 130200 metal2
> 193200 126000 200260 130200 metal1
1119,1121c1122,1124
< 147000 113400 151200 117600 metal2
< 147000 113400 159600 117600 metal3
< 155400 109200 159600 117600 metal2
---
> 147000 109200 151200 117600 metal2
> 147000 109200 159600 113400 metal3
> 155400 109200 159600 113400 metal2
1177a1181,1182
> 88200 37800 92400 46200 metal2
> 88200 42000 96600 46200 metal1
1180,1183c1185
< 88200 37800 96600 42000 metal3
< 92400 37800 96600 46200 metal2
< 92400 42000 96600 46200 metal1
< 92400 37800 100800 42000 metal3
---
> 88200 37800 100800 42000 metal3
1239c1241,1245
< 100800 84000 109200 88200 metal1
---
> 100800 84000 105000 88200 metal1
> 100800 84000 105000 88200 metal2
> 100800 84000 109200 88200 metal3
> 105000 84000 109200 88200 metal2
> 105000 84000 109200 88200 metal1
1408d1413
< 147000 130200 151200 138600 metal2
1410,1412c1415,1417
< 147000 130200 151200 134400 metal2
< 147000 130200 155400 134400 metal3
< 151200 130200 155400 138600 metal2
---
> 147000 134400 151200 138600 metal2
> 147000 134400 155400 138600 metal3
> 151200 134400 155400 138600 metal2
1418a1424
> 147000 130200 151200 138600 metal2
1439,1440c1445,1446
< 100800 63000 105000 71400 metal2
< 100800 63000 109200 67200 metal1
---
> 105000 63000 109200 71400 metal2
> 105000 63000 109200 67200 metal1
1448c1454,1456
< 100800 67200 121800 71400 metal3
---
> 100800 67200 109200 71400 metal3
> 105000 67200 109200 71400 metal2
> 105000 67200 121800 71400 metal3
1538,1543c1546,1550
< 100800 134400 105000 142800 metal2
< 100800 134400 109200 138600 metal3
< 105000 134400 109200 138600 metal2
< 105000 147000 109200 151200 metal1
< 105000 147000 109200 151200 metal2
< 105000 147000 117600 151200 metal3
---
> 100800 138600 105000 142800 metal2
> 100800 138600 113400 142800 metal3
> 109200 138600 113400 142800 metal2
> 109200 147000 113400 151200 metal2
> 109200 147000 117600 151200 metal3
1546,1549c1553,1555
< 109200 130200 113400 138600 metal2
< 109200 130200 117600 134400 metal3
< 105000 134400 113400 138600 metal3
< 109200 134400 113400 138600 metal2
---
> 105000 147000 109200 151200 metal1
> 105000 147000 109200 151200 metal2
> 105000 147000 113400 151200 metal3
1551c1557,1561
< 105000 134400 109200 151200 metal2
---
> 109200 134400 113400 138600 metal2
> 109200 134400 117600 138600 metal3
> 113400 130200 117600 138600 metal2
> 109200 134400 113400 142800 metal2
> 109200 138600 113400 151200 metal2
1559,1566c1569,1571
< 113400 121800 117600 126000 metal2
< 113400 121800 121800 126000 metal3
< 117600 121800 121800 126000 metal2
< 117600 130200 121800 134400 metal2
< 117600 130200 126000 134400 metal3
< 121800 130200 126000 134400 metal2
< 121800 130200 126000 134400 metal1
< 117600 138600 121800 147000 metal2
---
> 113400 117600 117600 126000 metal2
> 113400 117600 121800 121800 metal1
> 117600 130200 121800 147000 metal2
1571,1573c1576,1581
< 117600 117600 121800 142800 metal2
< 117600 138600 130200 142800 metal3
< 126000 138600 130200 142800 metal2
---
> 117600 117600 121800 134400 metal2
> 117600 130200 126000 134400 metal3
> 121800 130200 126000 134400 metal2
> 121800 130200 126000 134400 metal1
> 121800 130200 130200 134400 metal3
> 126000 130200 130200 138600 metal2
1581,1583d1588
< 147000 92400 151200 96600 metal1
< 147000 84000 151200 96600 metal2
< 142800 84000 151200 88200 metal1
1587,1588c1592,1596
< 155400 79800 159600 100800 metal2
< 155400 96600 159600 100800 metal1
---
> 142800 84000 151200 88200 metal1
> 147000 92400 155400 96600 metal1
> 151200 92400 155400 100800 metal2
> 151200 96600 159600 100800 metal1
> 147000 84000 151200 88200 metal1
1589a1598,1599
> 147000 92400 151200 96600 metal1
> 147000 84000 151200 96600 metal2
1594,1598c1604,1609
< 155400 96600 159600 113400 metal2
< 147000 109200 151200 113400 metal2
< 147000 109200 159600 113400 metal3
< 155400 109200 159600 113400 metal2
< 147000 109200 151200 117600 metal2
---
> 155400 96600 159600 109200 metal2
> 147000 105000 151200 109200 metal1
> 147000 105000 151200 109200 metal2
> 147000 105000 159600 109200 metal3
> 155400 105000 159600 109200 metal2
> 147000 105000 151200 117600 metal2
1602,1603c1613
< 147000 105000 151200 109200 metal1
< 155400 109200 159600 117600 metal2
---
> 155400 105000 159600 117600 metal2
1605d1614
< 147000 105000 151200 113400 metal2
1660,1662d1668
< 58800 75600 63000 79800 metal1
< 58800 75600 63000 84000 metal2
< 58800 79800 67200 84000 metal1
1663a1670,1673
> 54600 79800 58800 84000 metal2
> 54600 79800 67200 84000 metal3
> 63000 79800 67200 84000 metal2
> 63000 79800 67200 84000 metal1
1666d1675
< 63000 79800 67200 84000 metal1
1683,1689d1691
< 75600 67200 79800 71400 metal1
< 75600 67200 79800 71400 metal2
< 75600 67200 84000 71400 metal3
< 79800 67200 84000 71400 metal2
< 79800 67200 84000 71400 metal1
< 79800 63000 84000 71400 metal2
< 79800 63000 84000 67200 metal1
1691c1693,1696
< 75600 63000 79800 75600 metal2
---
> 75600 63000 79800 67200 metal2
> 75600 63000 84000 67200 metal3
> 79800 63000 84000 67200 metal2
> 79800 63000 84000 67200 metal1
1692a1698,1700
> 75600 67200 79800 75600 metal2
> 75600 67200 79800 71400 metal1
> 79800 63000 84000 71400 metal2
1693a1702
> 75600 63000 79800 71400 metal2
1720,1727d1728
< 109200 54600 113400 58800 metal2
< 109200 54600 121800 58800 metal3
< 117600 54600 121800 58800 metal2
< 117600 54600 121800 58800 metal1
< 109200 54600 113400 63000 metal2
< 109200 58800 113400 63000 metal1
< 92400 63000 105000 67200 metal1
< 100800 54600 105000 67200 metal2
1730c1731,1733
< 105000 54600 113400 58800 metal3
---
> 105000 54600 121800 58800 metal3
> 117600 54600 121800 58800 metal2
> 117600 54600 121800 58800 metal1
1733a1737,1741
> 92400 63000 109200 67200 metal1
> 105000 58800 109200 67200 metal2
> 105000 58800 109200 63000 metal1
> 105000 54600 109200 63000 metal2
> 105000 58800 113400 63000 metal1
1756d1763
< 75600 50400 79800 54600 metal1
1760,1762c1767,1770
< 75600 50400 79800 58800 metal2
< 75600 54600 84000 58800 metal3
< 79800 54600 84000 58800 metal2
---
> 75600 50400 79800 54600 metal1
> 75600 50400 79800 54600 metal2
> 75600 50400 84000 54600 metal3
> 79800 50400 84000 58800 metal2
1830,1837c1838,1840
< 151200 88200 155400 92400 metal1
< 151200 88200 155400 92400 metal2
< 151200 88200 159600 92400 metal3
< 155400 84000 159600 92400 metal2
< 155400 84000 159600 88200 metal1
< 151200 92400 155400 96600 metal1
< 151200 88200 155400 96600 metal2
< 142800 88200 151200 92400 metal1
---
> 147000 92400 151200 100800 metal2
> 147000 92400 155400 96600 metal1
> 142800 88200 155400 92400 metal1
1843,1845c1846,1852
< 147000 88200 155400 92400 metal1
< 147000 88200 151200 100800 metal2
< 147000 88200 151200 92400 metal1
---
> 151200 92400 155400 96600 metal1
> 151200 88200 155400 96600 metal2
> 151200 88200 155400 92400 metal1
> 151200 84000 155400 92400 metal2
> 151200 84000 159600 88200 metal3
> 155400 84000 159600 88200 metal2
> 155400 84000 159600 88200 metal1
1914,1918c1921,1924
< 67200 75600 79800 79800 metal1
< 75600 71400 79800 79800 metal2
< 75600 71400 79800 75600 metal1
< 58800 79800 67200 84000 metal1
< 67200 79800 75600 84000 metal1
---
> 71400 75600 75600 79800 metal1
> 71400 71400 75600 79800 metal2
> 71400 71400 79800 75600 metal1
> 67200 75600 75600 79800 metal1
1922,1923d1927
< 58800 79800 63000 84000 metal2
< 58800 79800 63000 84000 metal1
1926,1930c1930,1936
< 67200 75600 71400 84000 metal2
< 67200 75600 71400 79800 metal1
< 58800 79800 71400 84000 metal3
< 67200 79800 71400 84000 metal2
< 67200 79800 71400 84000 metal1
---
> 71400 75600 75600 84000 metal2
> 63000 79800 67200 84000 metal1
> 63000 79800 67200 84000 metal2
> 63000 79800 75600 84000 metal3
> 71400 79800 75600 84000 metal2
> 71400 79800 75600 84000 metal1
> 58800 79800 67200 84000 metal3
1957,1960c1963,1966
< 113400 117600 117600 121800 metal1
< 113400 117600 117600 121800 metal2
< 113400 117600 142800 121800 metal3
< 138600 100800 142800 121800 metal2
---
> 113400 117600 121800 121800 metal1
> 117600 105000 121800 121800 metal2
> 117600 105000 142800 109200 metal3
> 138600 100800 142800 109200 metal2
1965,1967c1971,1974
< 117600 117600 121800 121800 metal1
< 117600 113400 121800 121800 metal2
< 117600 113400 121800 117600 metal1
---
> 113400 117600 117600 121800 metal1
> 113400 113400 117600 121800 metal2
> 113400 113400 121800 117600 metal1
> 113400 117600 121800 121800 metal1
1969,1971c1976,1978
< 113400 121800 117600 126000 metal2
< 113400 121800 130200 126000 metal3
< 126000 121800 130200 134400 metal2
---
> 113400 121800 117600 134400 metal2
> 113400 130200 130200 134400 metal3
> 126000 130200 130200 134400 metal2
1974d1980
< 113400 117600 121800 121800 metal1
1998,2000c2004,2006
< 79800 117600 113400 121800 metal3
< 109200 117600 113400 121800 metal2
< 109200 117600 117600 121800 metal1
---
> 79800 117600 109200 121800 metal3
> 105000 117600 109200 121800 metal2
> 105000 117600 117600 121800 metal1
2078,2081c2084,2086
< 79800 42000 84000 46200 metal1
< 79800 42000 84000 46200 metal2
< 79800 42000 88200 46200 metal3
< 84000 37800 88200 46200 metal2
---
> 79800 37800 84000 42000 metal2
> 79800 37800 88200 42000 metal3
> 84000 37800 88200 42000 metal2
2082a2088,2089
> 79800 37800 84000 46200 metal2
> 79800 42000 84000 46200 metal1
2091,2093c2098,2099
< 63000 50400 67200 54600 metal2
< 63000 50400 84000 54600 metal3
< 79800 42000 84000 54600 metal2
---
> 63000 37800 67200 54600 metal2
> 63000 37800 84000 42000 metal3
2110a2117,2120
> 105000 100800 109200 105000 metal1
> 105000 100800 109200 105000 metal2
> 105000 100800 113400 105000 metal3
> 109200 100800 113400 105000 metal2
2116a2127,2132
> 84000 109200 88200 126000 metal2
> 88200 134400 92400 138600 metal1
> 88200 134400 92400 138600 metal2
> 88200 134400 138600 138600 metal3
> 134400 134400 138600 138600 metal2
> 134400 134400 138600 138600 metal1
2121,2123d2136
< 105000 100800 109200 105000 metal1
< 105000 84000 109200 105000 metal2
< 105000 84000 117600 88200 metal3
2125,2134c2138,2145
< 84000 100800 88200 113400 metal2
< 84000 100800 109200 105000 metal1
< 84000 109200 88200 126000 metal2
< 84000 121800 88200 126000 metal1
< 84000 121800 88200 138600 metal2
< 84000 134400 92400 138600 metal3
< 88200 134400 92400 138600 metal2
< 88200 134400 92400 138600 metal1
< 88200 134400 117600 138600 metal3
< 113400 134400 117600 138600 metal2
---
> 84000 109200 88200 113400 metal2
> 84000 109200 113400 113400 metal3
> 109200 109200 113400 113400 metal2
> 109200 100800 117600 105000 metal3
> 113400 84000 117600 105000 metal2
> 109200 100800 113400 113400 metal2
> 109200 109200 117600 113400 metal3
> 113400 109200 117600 138600 metal2
2136,2139c2147,2148
< 113400 134400 138600 138600 metal3
< 134400 134400 138600 138600 metal2
< 134400 134400 138600 138600 metal1
< 134400 134400 147000 138600 metal3
---
> 113400 134400 117600 138600 metal2
> 113400 134400 147000 138600 metal3
2146,2148c2155,2157
< 138600 96600 155400 100800 metal3
< 151200 96600 155400 100800 metal2
< 151200 96600 159600 100800 metal1
---
> 138600 96600 159600 100800 metal3
> 155400 96600 159600 100800 metal2
> 155400 96600 159600 100800 metal1
2159,2161c2168,2170
< 113400 142800 117600 151200 metal2
< 113400 142800 121800 147000 metal3
< 117600 142800 121800 147000 metal2
---
> 113400 147000 117600 151200 metal2
> 113400 147000 121800 151200 metal3
> 117600 142800 121800 151200 metal2
2253,2257c2262
< 100800 84000 105000 88200 metal1
< 100800 84000 105000 88200 metal2
< 100800 84000 109200 88200 metal3
< 105000 84000 109200 88200 metal2
< 105000 84000 109200 88200 metal1
---
> 100800 84000 109200 88200 metal1
2367d2371
< 134400 96600 142800 100800 metal1
2376,2377c2380,2382
< 117600 100800 142800 105000 metal3
< 138600 96600 142800 105000 metal2
---
> 117600 100800 138600 105000 metal3
> 134400 96600 138600 105000 metal2
> 134400 96600 142800 100800 metal1
2540,2542c2545,2549
< 71400 71400 84000 75600 metal1
< 75600 71400 79800 79800 metal2
< 75600 75600 84000 79800 metal1
---
> 71400 71400 79800 75600 metal1
> 79800 71400 84000 75600 metal1
> 79800 71400 84000 79800 metal2
> 79800 75600 84000 79800 metal1
> 75600 71400 84000 75600 metal1
2647,2649d2653
< 96600 46200 100800 50400 metal1
< 96600 46200 100800 58800 metal2
< 96600 54600 100800 58800 metal1
2652a2657,2658
> 92400 50400 96600 58800 metal2
> 92400 54600 100800 58800 metal1
2743,2744d2748
< 117600 67200 121800 75600 metal2
< 117600 67200 121800 71400 metal1
2746,2748c2750
< 92400 71400 96600 75600 metal2
< 92400 71400 121800 75600 metal3
< 117600 71400 121800 75600 metal2
---
> 117600 67200 121800 75600 metal2
2749a2752,2756
> 92400 67200 96600 71400 metal1
> 92400 67200 96600 71400 metal2
> 92400 67200 121800 71400 metal3
> 117600 67200 121800 71400 metal2
> 117600 67200 121800 71400 metal1
2920,2922c2927,2929
< 88200 46200 105000 50400 metal3
< 100800 42000 105000 50400 metal2
< 100800 42000 109200 46200 metal1
---
> 88200 46200 109200 50400 metal3
> 105000 42000 109200 50400 metal2
> 105000 42000 109200 46200 metal1
2925,2927c2932,2934
< 88200 96600 100800 100800 metal3
< 96600 96600 100800 100800 metal2
< 96600 96600 105000 100800 metal1
---
> 88200 96600 96600 100800 metal3
> 92400 96600 96600 100800 metal2
> 92400 96600 105000 100800 metal1
2932,2934c2939,2940
< 63000 58800 67200 63000 metal2
< 63000 58800 71400 63000 metal3
< 67200 46200 71400 63000 metal2
---
> 63000 46200 67200 63000 metal2
> 63000 46200 71400 50400 metal3
2949,2952d2954
< 100800 96600 105000 100800 metal1
< 100800 96600 105000 100800 metal2
< 100800 96600 109200 100800 metal3
< 105000 96600 109200 100800 metal2
2970c2972,2974
< 105000 96600 113400 100800 metal3
---
> 100800 96600 105000 100800 metal1
> 100800 96600 105000 100800 metal2
> 100800 96600 113400 100800 metal3
2975,2977c2979,2981
< 105000 113400 109200 117600 metal2
< 105000 113400 130200 117600 metal3
< 105000 96600 109200 117600 metal2
---
> 100800 113400 105000 117600 metal2
> 100800 113400 130200 117600 metal3
> 100800 96600 105000 117600 metal2
2980d2983
< 100800 113400 109200 117600 metal3
3095,3097c3098,3100
< 79800 92400 84000 96600 metal1
< 79800 92400 84000 96600 metal2
< 79800 92400 96600 96600 metal3
---
> 75600 92400 84000 96600 metal1
> 75600 92400 79800 96600 metal2
> 75600 92400 96600 96600 metal3
3107d3109
< 75600 92400 84000 96600 metal1
3133d3134
< 138600 109200 142800 113400 metal1
3139,3141c3140,3143
< 126000 117600 130200 121800 metal2
< 126000 117600 142800 121800 metal3
< 138600 109200 142800 121800 metal2
---
> 126000 109200 130200 121800 metal2
> 126000 109200 142800 113400 metal3
> 138600 109200 142800 113400 metal2
> 138600 109200 142800 113400 metal1
3260d3261
< 134400 96600 142800 100800 metal1
3262a3264
> 138600 96600 142800 100800 metal1
3266,3268c3268,3270
< 117600 96600 142800 100800 metal3
< 138600 96600 142800 100800 metal2
< 138600 96600 142800 100800 metal1
---
> 117600 96600 138600 100800 metal3
> 134400 96600 138600 100800 metal2
> 134400 96600 142800 100800 metal1
3501d3502
< 71400 84000 75600 88200 metal1
3504,3505c3505,3508
< 71400 88200 79800 92400 metal1
< 75600 84000 79800 92400 metal2
---
> 71400 84000 75600 88200 metal1
> 71400 84000 75600 88200 metal2
> 71400 84000 79800 88200 metal3
> 75600 84000 79800 88200 metal2
3654,3656c3657,3659
< 96600 46200 100800 50400 metal1
< 96600 46200 100800 50400 metal2
< 96600 46200 109200 50400 metal3
---
> 92400 46200 100800 50400 metal1
> 92400 46200 96600 50400 metal2
> 92400 46200 109200 50400 metal3
3663d3665
< 92400 46200 100800 50400 metal1
3831,3832c3833,3834
< 105000 37800 109200 54600 metal2
< 105000 37800 109200 42000 metal1
---
> 84000 92400 88200 96600 metal1
> 84000 79800 88200 96600 metal2
3834,3838c3836,3838
< 75600 46200 79800 54600 metal2
< 75600 50400 84000 54600 metal3
< 79800 50400 84000 54600 metal2
< 105000 58800 113400 63000 metal1
< 79800 50400 84000 67200 metal2
---
> 75600 46200 79800 63000 metal2
> 75600 58800 84000 63000 metal3
> 79800 58800 84000 67200 metal2
3839a3840,3841
> 105000 58800 113400 63000 metal1
> 84000 92400 92400 96600 metal1
3842,3847c3844,3846
< 84000 92400 92400 96600 metal1
< 105000 58800 109200 63000 metal1
< 105000 50400 109200 63000 metal2
< 105000 58800 109200 71400 metal2
< 79800 50400 109200 54600 metal3
< 105000 50400 109200 54600 metal2
---
> 84000 79800 88200 84000 metal2
> 84000 79800 105000 84000 metal3
> 100800 79800 105000 84000 metal2
3849,3851c3848,3849
< 100800 67200 105000 84000 metal2
< 100800 67200 109200 71400 metal3
< 105000 67200 109200 71400 metal2
---
> 100800 79800 109200 84000 metal3
> 105000 67200 109200 84000 metal2
3853,3856c3851,3856
< 88200 92400 92400 96600 metal1
< 88200 84000 92400 96600 metal2
< 88200 84000 105000 88200 metal3
< 100800 79800 105000 88200 metal2
---
> 79800 63000 84000 84000 metal2
> 79800 79800 88200 84000 metal3
> 105000 37800 109200 42000 metal1
> 105000 37800 109200 63000 metal2
> 105000 58800 109200 63000 metal1
> 105000 58800 109200 71400 metal2
4090,4094c4090,4094
< 147000 117600 151200 121800 metal1
< 147000 117600 151200 126000 metal2
< 147000 121800 168000 126000 metal3
< 163800 121800 168000 126000 metal2
< 163800 121800 176400 126000 metal1
---
> 147000 117600 155400 121800 metal1
> 151200 117600 155400 121800 metal2
> 151200 117600 172200 121800 metal3
> 168000 117600 172200 126000 metal2
> 168000 121800 176400 126000 metal1
4167,4169c4167,4169
< 113400 134400 117600 138600 metal2
< 113400 134400 121800 138600 metal3
< 117600 134400 121800 176400 metal2
---
> 113400 134400 117600 163800 metal2
> 113400 159600 121800 163800 metal3
> 117600 159600 121800 176400 metal2
4228,4231d4227
< 92400 37800 96600 42000 metal2
< 92400 37800 113400 42000 metal3
< 109200 33600 113400 42000 metal2
< 109200 33600 113400 37800 metal1
4233,4235c4229,4230
< 71400 37800 75600 42000 metal2
< 71400 37800 96600 42000 metal3
< 79800 63000 84000 67200 metal1
---
> 71400 37800 75600 67200 metal2
> 71400 63000 84000 67200 metal3
4237c4232,4234
< 79800 63000 96600 67200 metal3
---
> 79800 63000 84000 67200 metal1
> 109200 33600 113400 37800 metal1
> 109200 33600 113400 67200 metal2
4239c4236
< 105000 63000 109200 67200 metal1
---
> 92400 63000 109200 67200 metal3
4241,4243c4238
< 105000 63000 117600 67200 metal3
< 113400 63000 117600 67200 metal2
< 113400 63000 117600 67200 metal1
---
> 105000 63000 109200 67200 metal1
4255,4257c4250,4252
< 92400 37800 96600 67200 metal2
< 92400 63000 109200 67200 metal3
< 92400 63000 96600 88200 metal2
---
> 79800 63000 96600 67200 metal3
> 105000 63000 113400 67200 metal3
> 109200 63000 113400 67200 metal2
4259c4254,4257
< 92400 84000 96600 100800 metal2
---
> 92400 63000 96600 100800 metal2
> 109200 63000 117600 67200 metal3
> 113400 63000 117600 67200 metal2
> 113400 63000 117600 67200 metal1
4270,4272c4268,4270
< 67200 121800 79800 126000 metal1
< 75600 121800 79800 134400 metal2
< 75600 130200 84000 134400 metal1
---
> 67200 121800 84000 126000 metal1
> 79800 121800 84000 134400 metal2
> 79800 130200 84000 134400 metal1
4406a4405
> 142800 96600 147000 100800 metal1
4409,4413c4408,4411
< 142800 96600 147000 100800 metal1
< 142800 96600 147000 100800 metal2
< 142800 96600 159600 100800 metal3
< 155400 92400 159600 100800 metal2
< 155400 92400 163800 96600 metal1
---
> 142800 92400 147000 100800 metal2
> 142800 92400 163800 96600 metal3
> 159600 92400 163800 96600 metal2
> 159600 92400 163800 96600 metal1
     - [ERROR] Test failed. Check /Users/cherry/sta/openroad/src/FastRoute/test/src/test_guides/test.log and Check /Users/cherry/sta/openroad/src/FastRoute/test/src/test_guides/golden.guide
     - Test returned RED (failed)
 > Now running test_obstacles...
     - Test returned GREEN (passed)
 > Now running test_wl...
     - [ERROR] Test failed. Check /Users/cherry/sta/openroad/src/FastRoute/test/src/test_wl/test.log and Check /Users/cherry/sta/openroad/src/FastRoute/test/src/test_wl/golden.wl
     - Test returned RED (failed)

FastRoute tests finished!
CerezaBook>

**Comment by jjcherry56** [comment]
still crapping in the repo, now with garbage character file names:

Untracked files (6)
test/src/test_coverage/log.txt
test/src/test_guides/2_E
test/src/test_guides/log.txt
test/src/test_guides/out.guide
test/src/test_wl/2_)
test/src/test_wl/out.guide

**Comment by tspyrou** [comment]
Tutu is complaining about those messages already.

**Comment by eder-matheus** [comment]
@jjcherry56 I have found that FastRoute results are different when compiled with gcc and compiled with clang. I trying to narrow down this problem.

But I added the log files of unit tests to .gitignore, and I updated the scripts to avoid print diff information in the regression results. Now it tells where to find the diff file.

**Comment by jjcherry56** [comment]
what about tapcell?
the regression script does not return 0 on success (it is too busy removing files that you now .gitignore)

**Comment by eder-matheus** [comment]
@jjcherry56  "exit 0" was added to tapcell and FastRoute regression scripts.

Also, I found that FastRoute unit tests are failing with Apple clang. I was able to run it with clang on Ubuntu. Did you see it before?
Maybe I should delete this branch and close this pull request until I fix this issue...

**Comment by jjcherry56** [comment]
Yes, I saw the clang issue; that was the source of the huge logfile diffs I
posted earlier.
Why don't we commit what you have and then work on the clang issue
separately?
I am drowning in the repo turds while I am testing the regression script
for the whole app.

**Pull request merged**
