### PR TITLE
Fixes boost spirit parsing issues.

### PR DESCRIPTION
**Pull request by QuantamHD**
It turns out that boost spirit is very sensitive to being encapsulated
in functions since it heavily relies on template meta-programming.

Meaning that the lambda and functions in the old version made the parser
not actually work even though it compiled. This is the best we can
do.

Signed-off-by: Ethan Mahintorabi <ethanmoon@google.com>

### CODE REVIEW

**Comment by maliberty** [comment]
Would you explain why the encapsulation didn't work?

**Comment by QuantamHD** [comment]
Boost qi relies on both parser references and template specializations. When you put a parser in a lambda or function, it no longer allows the compiler to correctly figure out what the parser structure is. It also creates memory issues since the final construction in a given function context ref is no longer considered valid.

All examples of boost qi construct the parser in a single function.

**Comment by QuantamHD** [comment]
Also added a basic unit test.

**Comment by maliberty** [comment]
I like the current structure better and don't really understand why it doesn't work.  I'd like to study this a bit but will approve if you are in a rush.

**Comment by QuantamHD** [comment]
I would say I need it Wednesday ish. I've tried a bunch of different things, but no matter what i did I could not return a rule from a function and still have the parser work.

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
It looks like there is a better solution based on the feedback in https://github.com/boostorg/spirit/issues/729

**Review by maliberty — CHANGES_REQUESTED** [review]
use qi::copy

**Comment by maliberty** [comment]
Closed in favor of https://github.com/The-OpenROAD-Project/OpenROAD/pull/2093

**Pull request closed without merging**
