### PR TITLE
ifp: fix double to int rounding in meterToDbu

### PR DESCRIPTION
**Pull request by mooredan**
Addresses issue #849 and one I've seen in my own testing.
Adds 0.5 to double value before "casting" to int (return data type of meterToDbu method), maybe std::round should have been used?
re: https://stackoverflow.com/questions/9695329/c-how-to-round-a-double-to-an-int

"broke" several regression tests now that proper rounding allows for more rows and tracks in floorplans, those have been updated as well.  Looks OK to me, but needs a second set of eyes before merging onto main.

### CODE REVIEW

**Comment by rovinski** [comment]
@jjcherry56 has waged a war on code that adds 0.5 instead of `std::ceil()`. I think this code should be using `std::round()` anyways.

**Comment by maliberty** [comment]
This is a good but the distance_ui_sta problem remains in sta too.

**Comment by mooredan** [comment]
@maliberty : I'm willing to take a look at sta::distance_ui_sta and did take a brief look, but I'm not seeing the issue.  Is there a small test case that could be run that demonstrates the issue?

The procedure is called in InitFloorplan.tcl and defined in OpenSTA/tcl/StaTcl.i  which takes a double and returns a double. Where is the double-to-int rounding issue coming into play?  ...or is this something slightly different?

Played with sta::distance_ui_sta on the command line a bit giving it a variety of arguments, didn't see anything "funny" unless using a lot of significant digits, e.g.

openroad 1> sta::distance_ui_sta 99.999999999999999
100.0

that's one too many nines

openroad 1> sta::distance_ui_sta 99.00000000000000000000001
99.0

At any rate, this pull request solves the issue originally reported by @donn  That is, the test case now operates as expected (and solves the issue that I saw in my own tests).

**Review by maliberty — APPROVED** [review]

**Comment by donn** [comment]
Does this fix the issue I had?

**Comment by mooredan** [comment]
@donn 

Yes:

```
mooredan@lemur:~/Downloads/RAM32_SIZE32$ ./fp_init.tcl 
OpenROAD 1 f8c73ff999bc957a4804879bb2422486bdd9370f
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
[INFO ODB-0222] Reading LEF file: ./sky130_fd_sc_hd.merged.lef
[WARNING ODB-0220] WARNING (LEFPARS-2008): NOWIREEXTENSIONATPIN statement is obsolete in version 5.6 or later.
The NOWIREEXTENSIONATPIN statement will be ignored. See file ./sky130_fd_sc_hd.merged.lef at line 2.

[INFO ODB-0223]     Created 13 technology layers
[INFO ODB-0224]     Created 25 technology vias
[INFO ODB-0225]     Created 437 library cells
[INFO ODB-0226] Finished LEF file:  ./sky130_fd_sc_hd.merged.lef
[INFO IFP-0001] Added 35 rows of 981 sites.

```

**Pull request merged**
