### PR TITLE
grt: add usage and capacity to heatmap

### PR DESCRIPTION
**Pull request by gadfort**
This is what I mocked up to view the GCells in #2924 
If it's of interest to include.

### CODE REVIEW

**Review by maliberty — APPROVED** [review]
Thanks

**Comment by maliberty** [comment]
image

**Comment by maliberty** [comment]
double value = 0; should solve it

**Comment by gadfort** [comment]
@maliberty I just fixed the value = 0 (I didn't see your review so I forced pushed unfortunately)

**Comment by maliberty** [comment]
no problem I already approved

**Pull request merged**
