### PR TITLE
Fix Dockerfile

### PR DESCRIPTION
**Pull request by bkoppelmann**
Hi, 

while trying to build OpenROAD in Docker, I fixed two out of date problems.

Cheers,
Bastian

### CODE REVIEW

**Comment by FreakyPenguin** [comment]
I ended up fixing this in parallel as well. The first commit is the same for me. For git2u, I think that might have gotten renamed to git216, which seems to have been archived in favor of git222. That's what I replaced it with in my dockerfile, that seems to get the job done. But if git1.8 is sufficient then maybe just keeping the stock git is easier, as the name seems to change with versions, looks like there is already git224.

**Comment by bkoppelmann** [comment]
Cool :). I'm happy with that as well. I'm just wondering why we need a specific git version.

**Comment by rovinski** [comment]
There haven't been any problems on our end, probably because the Docker cache is keeping these dependencies from rebuilding.

With respect to the iuscommunity link, that seems like a warranted fix. With respect to the git change, that will not work because the default version of git included with CentOS 7 has issues. The container isn't necessarily run with a username that exists, and if that happens, git < 2.6.5 will fail to check out any repository, regardless of whether it needs credentials or not. See https://github.com/jenkinsci/docker/issues/519. This is why the CI failed on this commit.

The other alleged solution was to set `GIT_COMMITTER_NAME` and `GIT_COMMITTER_EMAIL` through the environment, but I wasn't able to get that to work in our CI. My preferred solution is to just use a newer version of git, because then the issue won't occur on the user side when they try git cloning from inside the image. Is there's a compelling reason to use the environment solution?

**Comment by tspyrou** [comment]
I just changed the website url to pull centos from, thank you for this

**Comment by rovinski** [comment]
This has been resolved in #296. I went with the solution of using package git224, as I feel that this creates the best chance for a user to avoid running into jenkinsci/docker#519. I left a comment that any version of git > 2.6.5 works.

I would have merged this PR and then added the git package fix, but it looks like others modified the Dockerfile in the meantime, so it was easier to just redo the changes I needed. Thanks for your contributions.

**Pull request closed without merging**
