### PR TITLE
drt: set VIA_ACCESS_LAYERNUM when adding the first routing level 

### PR DESCRIPTION
**Pull request by gadfort**
Issue:
if multiple vias are defined before the first routing level, the `VIA_ACCESS_LAYERNUM` will be pointing to a via instead of the first routing level.

Changes:
- set VIA_ACCESS_LAYERNUM when adding the first routing level to ensure it matches the layer stack
- just loop over layers to init gcells to avoid assumptions about the start of the layer stack
- minor changes to error message for guideIN to make it clear what the via access is.

### CODE REVIEW

**Comment by maliberty** [comment]
drt has strong assumptions about the layer stack.  I think it is best to hide the extra via layer.  I expect more problems will arise otherwise.

**Comment by gadfort** [comment]
@maliberty alright, it's skipping successive cut layers now

**Comment by gadfort** [comment]
@maliberty anything else needed on this one?

**Comment by maliberty** [comment]
Is there any need to mess with  VIA_ACCESS_LAYERNUM or buildGCellPatterns now that you skip successive layers?

**Comment by gadfort** [comment]
I've removed it, but it looks like this PR and my branch are no longer connected... Might need to debug a bit

**Comment by maliberty** [comment]
> I've removed it, but it looks like this PR and my branch are no longer connected... Might need to debug a bit

Maybe you forgot to push your change?

**Comment by gadfort** [comment]
@maliberty thats what I thought too: https://github.com/gadfort/OpenROAD/tree/drt-skip-double-cuts
maybe I'll just close this one and reopen it again

**Comment by gadfort** [comment]
@maliberty a force push fixed it, sorry about that

**Review by maliberty — APPROVED** [review]
clang-tidy nit

**Pull request merged**
