### PR TITLE
odb: version checking fixes

### PR DESCRIPTION
**Pull request by antonblanchard**
It looks like the minor revision check is reversed, because before I added the second patch I was getting:

```
incompatible database schema minor revision (database requires 56 or greater but OpenROAD is 57)
```

I presume the idea of a minor revision is an update that retains compatibility with older minor revisions (is that correct?). After making the fix I tested that database (minor rev 56, OpenROAD minor rev 57) and it promptly used all of my memory and crashed. That suggests we are misusing the minor rev number.

### CODE REVIEW

**Comment by maliberty** [comment]
> I presume the idea of a minor revision is an update that retains compatibility with older minor revisions (is that correct?). 

Yes, in the sense that a new rev can read the older rev but not visa-versa.

> After making the fix I tested that database (minor rev 56, OpenROAD minor rev 57) and it promptly used all of my memory and crashed. That suggests we are misusing the minor rev number.

Do you have an example of that?  57 should read 56.

**Comment by antonblanchard** [comment]
> > After making the fix I tested that database (minor rev 56, OpenROAD minor rev 57) and it promptly used all of my memory and crashed. That suggests we are misusing the minor rev number.
> 
> Do you have an example of that? 57 should read 56.

I was trying the test case from https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/576

If I patch OpenROAD with the first of my commits, which just adds revision numbers to the incompatibility errors:
```
Error: global_place_skip_io.tcl, 2 incompatible database schema minor revision (database requires 56 or greater but OpenROAD is 57)
```

If I add the patch to reverse the minor revision check, it died after consuming 43GB of RAM.

**Comment by antonblanchard** [comment]
This seems to be the problem:

```
Thread 1 (Thread 0x7fb3fa57d8c0 (LWP 1765885) "openroad"):
#0  0x00007fb3f9558ac0 in __memset_avx2_unaligned_erms () from /lib64/libc.so.6
#1  0x0000000000cd6db6 in std::vector<unsigned int, std::allocator<unsigned int> >::_M_default_append(unsigned long) ()
#2  0x0000000002af0da0 in odb::dbIStream& odb::operator>><unsigned int>(odb::dbIStream&, odb::dbMatrix<unsigned int>&) [clone .isra.0] ()
#3  0x0000000002af3408 in odb::operator>>(odb::dbIStream&, odb::_dbTechLayer&) ()
#4  0x0000000002a31cd0 in odb::operator>>(odb::dbIStream&, odb::_dbTech&) ()
#5  0x00000000029d323a in odb::operator>>(odb::dbIStream&, odb::_dbDatabase&) ()
#6  0x00000000029d3ca5 in odb::dbDatabase::read(_IO_FILE*) ()
#7  0x0000000000c33ecf in ord::OpenRoad::readDb(char const*) ()
#8  0x0000000000c41c46 in _wrap_read_db_cmd ()
#9  0x00007fb3fb722970 in TclNRRunCallbacks () from /lib64/libtcl8.6.so
```

**Comment by antonblanchard** [comment]
One of these two patches is making an incompatible change to the database:

commit 2f0cb8875fa3f79d80db2c546fbad65d4452ee42 ('odb: use 2 bits for overlap instead of int')

commit fc7d8a9508785f8b6ad3282434d4dcd4ff1b36ab ('odb: use int for mask and overlap and remove setNumber')

@eder-matheus FYI

**Comment by maliberty** [comment]
its the first of those two

**Comment by maliberty** [comment]
You've found a real issue where we failed to update the schema.  This PR however is wrong.  db_schema_initial is the older version of the schema that this code can load (it can load any later version).  If you have an even older schema it is an error.  The code is correct to me.

**Comment by maliberty** [comment]
It looks like the schema version has been updated since @eder-matheus change so there is no easy way to fix this omission.  We'll just have to be careful for a while until such dbs become obsolete.

**Comment by antonblanchard** [comment]
Perhaps this change:

```
-      "type": "int",
-      "name": "overlap_"
+      "type": "uint",
+      "name": "overlap_",
+      "bits": 2
```

Seems like we should have bumped the major revision to the database.

**Comment by maliberty** [comment]
You can solve that in the io operators and remain backwardly compatible but its too late now.

**Comment by antonblanchard** [comment]
I misunderstood how the versioning worked and thought it was a bad check because many of the test cases I've downloaded recently (odb based, no longer def based) wont load in OpenROAD. It would be nice to have some older databases in our test suite so things don't break over time.

**Comment by maliberty** [comment]
We do have one test but apparently it didn't catch this

**Pull request closed without merging**
