### PR TITLE
Changing dbSigType and dbIoType from enum to enum class

### PR DESCRIPTION
**Pull request by fgaray**
Making dbSigType and dbIoType more type safe to prevent mixing up both classes.

I have been bitten by this in the past by mixing dbSigType and dbIoType.

If this is approved I will do the same for other types in odb/dbTypes.h

### CODE REVIEW

**Comment by maliberty** [comment]
They are both already nested inside a class so I'm wondering how they could get mixed up.  Would you give an example of the problem.

**Comment by fgaray** [comment]
Hi @maliberty , Yeah, they should be, but I have found that code like:


```
if (bterm->getIoType() == odb::dbIoType::OUTPUT) {
/// Something
}

if (bterm->getSigType() == odb::dbIoType::OUTPUT) {
///Something else
}
```

Compiles successfully in my system: gcc-10.2.1-6 inside the debian testing docker image.

**Comment by maliberty** [comment]
Interesting clang will complain about it and g++ will complain about
```
if (bterm->getIoType().getValue == odb::dbIoType::OUTPUT) {
/// Something
}
```
Apparently if the 'operator Value()' is used then it doesn't complain which isn't nice.  I found
```
-  operator Value() const { return _value; }
+  bool operator==(const dbSigType& v) const { return _value == v._value; }
+  bool operator!=(const dbSigType& v) const { return _value != v._value; }
+  bool operator==(const Value v) const { return _value == v; }
+  bool operator!=(const Value v) const { return _value != v; }
```
works pretty well.  You do have to use getVaue() in a few places, like switch statements but its much less pervasive.  It avoids making the lengthy odb::dbIoType::INPUT into the even longer odb::dbIoType::Value::INPUT.

Thoughts?

**Comment by fgaray** [comment]
Ah, I like that much better than my approach actually. It is less intrusive. How do you want to proceed?, do you want me to work on that and cancel this PR?

**Comment by maliberty** [comment]
> Ah, I like that much better than my approach actually. It is less intrusive. How do you want to proceed?, do you want me to work on that and cancel this PR?

If you ware willing to work on it that would be great.

**Comment by fgaray** [comment]
Sure, I will work on that tomorrow!, Thanks!

**Pull request closed without merging**
