### PR TITLE
Or3907

### PR DESCRIPTION
**Pull request by openroadie**
Delete nets that are no longer needed when undoing gate cloning.

### CODE REVIEW

**Comment by openroadie** [comment]
Fixes #3907

**Review by maliberty — APPROVED** [review]

**Review by gadfort — CHANGES_REQUESTED** [review]
This removes the floating nets in name only. The iterms of the instances are still floating:
image

```
foreach iterm [[ord::get_db_block] getITerms] {
if { [ $iterm getIoType ] == "INPUT" && [ $iterm getNet ] == "NULL" } {
puts "Floating iterm: [[$iterm getInst] getName]/[[$iterm getMTerm] getName]"
}
}
```
There are a ton of them

**Comment by openroadie** [comment]
> This removes the floating nets in name only. The iterms of the instances are still floating: image
> 
> ```
> foreach iterm [[ord::get_db_block] getITerms] {
> if { [ $iterm getIoType ] == "INPUT" && [ $iterm getNet ] == "NULL" } {
> puts "Floating iterm: [[$iterm getInst] getName]/[[$iterm getMTerm] getName]"
> }
> }
> ```
> 
> There are a ton of them

Thank you @gadfort. I guess there are intricacies of ODB I still need to understand. I will work on this.

**Comment by openroadie** [comment]
@gadfort Thanks for catching this. Should be all fixed now. I still have an issue in one of the regressions (repair_fanout7) where we are left with 2 floating iterms but that is unrelated to gate cloning. 

@maliberty  I will debug/fix that as well but it need not block this PR.

**Comment by openroadie** [comment]
ORFS results here:

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/1404

**Comment by gadfort** [comment]
@maliberty @openroadie what kind of verification for correctness has been done on this functionality? Any kind of formal verification / lec?

**Comment by maliberty** [comment]
> @maliberty @openroadie what kind of verification for correctness has been done on this functionality? Any kind of formal verification / lec?

I think that is a good idea but it shouldn't hold up this PR.

**Pull request merged**
