### PR TITLE
cts: revert insertion delay on by default

### PR DESCRIPTION
**Pull request by eder-matheus**
Reverting this CTS update, as it breaks two private designs in our secure-ci.
@precisionmoon FYI.

### CODE REVIEW

**Review by maliberty — APPROVED** [review]
I'll approve but you need to resolve the c++20 failure

Which two designs?

**Comment by eder-matheus** [comment]
> I'll approve but you need to resolve the c++20 failure
> 
> Which two designs?

gf12/bp_single timeout and gf12/ca53 crash. However, ca53 is timing out in my revert branch. I don't remember if it was timing out before.

**Comment by oharboe** [comment]
@maliberty Is there a plan to restore this?

**Comment by maliberty** [comment]
Yes once it doesn't break the CI

**Comment by oharboe** [comment]
@maliberty Is this fixed now? Is there anywhere I can follow this?

**Comment by maliberty** [comment]
@precisionmoon do you have an update?

**Comment by precisionmoon** [comment]
https://github.com/The-OpenROAD-Project/OpenROAD/pull/4721 is being validated with CI tests.   The fatal issue has been resolved.   We should be able to make insertion delay on by default this week.

**Comment by precisionmoon** [comment]
PR 4721 has been merged.

**Pull request merged**
