### PR TITLE
deltaDebug: ignore irrelevant errors

### PR DESCRIPTION
**Pull request by oharboe**
fixes false negatives

### CODE REVIEW

**Comment by maliberty** [comment]
What is ERROR falsely matching?  I'm wondering if there is a way we an narrow the check rather than remove it.

**Comment by oharboe** [comment]
> What is ERROR falsely matching? I'm wondering if there is a way we an narrow the check rather than remove it.

Two examples:

```
[deleted]
[*** LOG ERROR #0001 ***] [2023-03-29 14:05:24] [logger] ***argument not found***
[deleted]
[ERROR PPL-0061] Pins for set_io_pin_constraint command were not found.
```

- I don't know what the first error is about
- The second is a known harmless error, I've scaled down the design so that this pin is not present. I have a ```tcl catch``` statement around the `set_io_pin_constraint` statement to ignore that error.

**Comment by QuantamHD** [comment]
The first error is a runtime issue with a log statement missing a template argument. See the following example.

`logger_->warn(UTL, 1000, "{} {} {}", "hi", "bye");`

**Comment by oharboe** [comment]
@eder-matheus Probably not relevant here, but how can we find out which error doesn't have arguments specified?

**Comment by eder-matheus** [comment]
> @eder-matheus Probably not relevant here, but how can we find out which error doesn't have arguments specified?

This looks trick. It is not necessarily an error message that doesn't have arguments. It can be any message. I will revise the PPL messages looking for this error.

**Comment by maliberty** [comment]
A catch around an error was not anticipated.  However the common use case is that an unrelated error is failure.  I think it better to make a non-default option to continue on error instead or removing the check.

**Comment by oharboe** [comment]
> The first error is a runtime issue with a log statement missing a template argument. See the following example.
> 
> `logger_->warn(UTL, 1000, "{} {} {}", "hi", "bye");`

@eder-matheus @QuantamHD  This hack removes the problem... https://github.com/The-OpenROAD-Project/OpenROAD/pull/3115

**Comment by oharboe** [comment]
@maliberty So this is what we want I think, but I haven't tested it yet. If someone can vouch for it :-) it should be good to go in.

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
I think I prefer the default to be on but it isn't that important to me.

**Comment by oharboe** [comment]
> I think I prefer the default to be on but it isn't that important to me.

I prefer the default to be on, but the problem is that when it doesnt work, the user has to figure out why it isnt working and disable the option.... Default off gives the highest chance of a user succeeding, even if it takes longer.

**Pull request merged**
