### PR TITLE
grt: repair_antennas fix to avoid overlaps with pins

### PR DESCRIPTION
**Pull request by eder-matheus**
Unblock Yosys 0.37 update.

### CODE REVIEW

**Comment by eder-matheus** [comment]
@maliberty The `ibex_sky130hd` test that fails in the PR is not failing when running locally. Is it a rounding issue?
`ibex_sky130hd (tcl) *FAIL* DRT::max_capacitance_slack  -0% <  -0%`

**Comment by maliberty** [comment]
@vvbandeira is looking into this.  I had a PR with all green checks that failed after merging (with no intervening changes).

**Comment by eder-matheus** [comment]
> @vvbandeira is looking into this. I had a PR with all green checks that failed after merging (with no intervening changes).

Got it. Should we wait for this fix, or can we merge this PR? This is the last blocker on the Yosys update.

**Comment by maliberty** [comment]
If the failures match master then go ahead

**Comment by eder-matheus** [comment]
They're similar but not the same.
This PR: `ibex_sky130hd (tcl) *FAIL* DRT::max_slew_slack  -0% <   0% ; DRT::max_capacitance_slack  -2% <  -0%`
Master branch: `ibex_sky130hd (tcl) *FAIL* GRT::ANT::errors   1 >   0 ; DRT::max_slew_slack  -6% <  -5%`

**Comment by maliberty** [comment]
Hopefully #4662 will resolve the issue.  Once it is merged you can merge and see if it solves this as well.

**Comment by eder-matheus** [comment]
@maliberty This is ready to merge now.

**Review by maliberty — APPROVED** [review]

**Pull request merged**
