### PR TITLE
Fix to maximize via array in power strapping overlap

### PR DESCRIPTION
**Pull request by mooredan**
Potential fix for issue #805 

After applied the fix, the via comes out as expected (and DRC free)

$ grep 'VIARULE viagen32'  pdn.def 
    - via2_2200x900 + VIARULE viagen32 + CUTSIZE 500 500  + LAYERS metal2 via2 metal3  + CUTSPACING 800 800  + ENCLOSURE 200 200 200 200  + ROWCOL 1 2  ;

Screenshot from 2021-06-30 16-45-32

### CODE REVIEW

**Comment by maliberty** [comment]
@Colin-Holehouse would you please take a look at this?  The change is pretty trivial.

**Comment by tspyrou** [comment]
@mooredan can you take a look at the CI failure. You can click details to see what is happening. Also it seems there is a source code conflict.

**Comment by mooredan** [comment]
Well it was merge-able when I submitted the pull request.  The diff is a two character change on a single line.  Another commit in the same area must got in ahead of this one.  I'll look into how to resolve the conflict.....

**Comment by mooredan** [comment]
Merge-able again -- will look into why the CI has issues -- suspect that the results for the test cases may be slightly different now due to the number of vias that were added on power strapping

**Comment by mooredan** [comment]
regression passes on my end, but CI is having issues with the rcx area. I've updated the appropriate "ok" files, and pushed them and even forced CI to run again, but no joy.   Could CI be used a different set of ok files for the rcx test? ...or could this be a "precision" differences between different OS's/compilers?   

Here's the diff for one of the rcx/ ok files:

```
diff --git a/src/rcx/test/ext_pattern.ok b/src/rcx/test/ext_pattern.ok
index 6cf4fd33d..7695970fb 100644
--- a/src/rcx/test/ext_pattern.ok
+++ b/src/rcx/test/ext_pattern.ok
@@ -11,7 +11,7 @@
 [INFO RCX-0029] Defined extraction corner X
 [INFO RCX-0008] extracting parasitics of blk ...
 [INFO RCX-0435] Reading extraction model file ext_pattern.rules ...
-[INFO RCX-0436] RC segment generation blk (max_merge_res 0.0) ...
+[INFO RCX-0436] RC segment generation blk (max_merge_res 0) ...
 [INFO RCX-0040] Final 70552 rc segments
 [INFO RCX-0439] Coupling Cap extraction blk ...
 [INFO RCX-0440] Coupling threshhold is 0.1000 fF, coupling capacitance less than 0.1000 fF will be grounded.
```

Note: 0.0 vs 0    Could this be the notorious compare to zero problem that's common in programming?



```
$ test/regression rcx
------------------------------------------------------
rcx
generate_pattern pass
generate_rules pass
ext_pattern pass
gcd pass
45_gcd pass
------------------------------------------------------
Passed 5
See /home/mooredan/src/OpenROAD/src/rcx/test/results for log files
------------------------------------------------------
Passed all tool regressions.
```

**Comment by mooredan** [comment]
From Jenkins, I pulled out the rcx results.tgz from artifacts and found this in the diff file:

```
mooredan@lemur:~/Downloads/src/rcx/test/results$ more diffs 
*** /tmp/workspace/OpenROAD-Public_PR-806-merge@2/src/rcx/test/ext_pattern.ok   2021-07-23 11:50:46.220351622 +0000
--- /tmp/workspace/OpenROAD-Public_PR-806-merge@2/src/rcx/test/results/ext_pattern.log  2021-07-23 12:10:29.598977103 +0000
***************
*** 11,17 ****
  [INFO RCX-0029] Defined extraction corner X
  [INFO RCX-0008] extracting parasitics of blk ...
  [INFO RCX-0435] Reading extraction model file ext_pattern.rules ...
! [INFO RCX-0436] RC segment generation blk (max_merge_res 0) ...
  [INFO RCX-0040] Final 70552 rc segments
  [INFO RCX-0439] Coupling Cap extraction blk ...
  [INFO RCX-0440] Coupling threshhold is 0.1000 fF, coupling capacitance less than 0.1000 fF will be grounded.
--- 11,17 ----
  [INFO RCX-0029] Defined extraction corner X
  [INFO RCX-0008] extracting parasitics of blk ...
  [INFO RCX-0435] Reading extraction model file ext_pattern.rules ...
! [INFO RCX-0436] RC segment generation blk (max_merge_res 0.0) ...
  [INFO RCX-0040] Final 70552 rc segments
  [INFO RCX-0439] Coupling Cap extraction blk ...
  [INFO RCX-0440] Coupling threshhold is 0.1000 fF, coupling capacitance less than 0.1000 fF will be grounded.

```

It's not clear as to how to resolve this.

**Comment by maliberty** [comment]
It could be OS, compiler, or spdlog version.  I think the simplest thing is to just revert your rcx changes and those tests should pass on Jenkins even if they don't for you locally.

**Comment by mooredan** [comment]
I may be onto a solution for the integration....hang on...

**Comment by maliberty** [comment]
@Colin-Holehouse please review as CI is now passing

**Review by tspyrou — APPROVED** [review]
@Colin-Holehouse this has been sitting and looks simple so I am approving. Please send feedback if any concerns.

**Pull request merged**
