### PR TITLE
[ODB] lefout: Fix typo

### PR DESCRIPTION
**Pull request by rovinski**

### CODE REVIEW

**Review by maliberty — APPROVED** [review]

**Comment by QuantamHD** [comment]
LGTM other than the build failure.

**Comment by maliberty** [comment]
if you merge master the mac problem should go away (GH changed their mac setup and I had to fix a bunch of things to make it happy)

**Comment by QuantamHD** [comment]
Out of curiosity how did you find this bug? I didn't know anyone was using the abstract lef support.

**Comment by rovinski** [comment]
@QuantamHD https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/312 was opened. I suggested using this instead and deprecating the script. I was skimming through the code to see if it handled the issue and I spotted this.

To be fair, many origins are centered at (0, 0) so the bug infrequently manifests.

**Pull request merged**
