### PR TITLE
MBFF Clustering Cleanup / FOARS Implementation

### PR DESCRIPTION
**Pull request by therealshreyas**
1. FOARS: FLUTE Based Obstacle-Avoiding Rectilinear Steiner Tree Construction (added to STT)
Paper Reference: https://ieeexplore.ieee.org/document/5690251 
Todo: add refinement, runtime optimizations

2. Updated MBFF:
(a) Added timing-critical path (launch-capture FF pairs) support
(b) Updated cluster_flops command (top_k variable, default 0)
(c) Updated ratios_ calculation (normalize to single-bit FF area)
(d) Updated slot location calculation (w.r.t. center instead of bottom left corner)
(e) Updated GetRows() to be accurate 
(f) Updated ILP to reflect latest experiments
(g) Updated ModifyPinConnections() to actually work (bitmask logic was previously incorrect). 
(h) Updated logs to print useful information
(i) Fixed tests to actually be sensible (read asap7 single bit FF, DIEAREA)

### CODE REVIEW

**Comment by rovinski** [comment]
https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/

**Comment by maliberty** [comment]
Please cleanup the remaining clang-tidy

**Comment by maliberty** [comment]
Why did you close this?

**Comment by maliberty** [comment]
This last push seems unrelated to foars

**Pull request closed without merging**
