### PR TITLE
gui: Make drc marker blink when selected as for mouse over.

### PR DESCRIPTION
**Pull request by titan73**
Mouse over makes the marker blink and then clicking stops it. Make it continue blinking after selection.

### CODE REVIEW

**Comment by titan73** [comment]
For https://github.com/The-OpenROAD-Project/OpenROAD/issues/6149.

**Comment by gadfort** [comment]
@titan73 I'm unable to get a different behavior before or after this change. What exactly is the sequence of events that you are expecting this to cause? and how to test it?

**Comment by titan73** [comment]
To reproduce
- extract test case below [drc_blink.zip](https://github.com/user-attachments/files/17738308/drc_blink.zip)
- cd to folder
- openroad -gui
- open test.odb from menu
- load violations.drc
- expand "short" tree
- click on first violation
- move mouse out of violation entry
- move mouse back to violation, the marker starts blinking
- click on violation entry and the marker stops blinking
With the change the last step does not make blinking stop

**Review by gadfort — APPROVED** [review]
@titan73 I'm able to replicate it. It doesn't actually "keep" the animation going, but instead its getting restarted.
I seems like this exposes and masks some odd behavior of the GUI, but in the short run it seems fine. I think we should keep the issue open to track fixing the inspector animation behavior.

**Comment by titan73** [comment]
Yes indeed, it is restarted.
I'll keep the issue open. What behavior did you see?

**Pull request merged**
