### PR TITLE
fix: Fixed some paths/imports to handle the OpenDb->odb name change. …

### PR DESCRIPTION
**Pull request by openroadie**
…TCL/python regressions work now (fail after #7 due to a different issue)

Signed-off-by: Harsh Vardhan <openroad@chez-vardhan.com>

### CODE REVIEW

**Comment by openroadie** [comment]
@maliberty @vvbandeira Decided to keep it simple and closed the other request. I hope this looks more reasonable. odb python/TCL regressions are working for me after these changes (they did not before).

**Review by maliberty — APPROVED** [review]
@macd FYI

**Comment by macd** [comment]
So the renaming of `opendbpy` to `odbpy` works OK with the stand alone exe in `build/src/odb/src/swig/python/odbpy` but it does not work with using `openroad -python`.  There we must use `import odb`, (which I prefer). I also believe we should be testing `openroad -python`. I would like to move to pytest, and I can make these changes at that time, if you like.

**Comment by openroadie** [comment]
Hi DonI have a lot to learn 😁. Let me try to fix this and I will add you as a reviewer to the pull request to ensure that I have not missed anything. Thank you Sent from my iPhoneOn Oct 17, 2022, at 6:34 PM, Don MacMillen ***@***.***> wrote:﻿
So the renaming of opendbpy to odbpy works OK with the stand alone exe in build/src/odb/src/swig/python/odbpy but it does not work with using openroad -python.  There we must use import odb, (which I prefer). I also believe we should be testing openroad -python. I would like to move to pytest, and I can make these changes at that time, if you like.

**Comment by macd** [comment]
Sounds good!

**Comment by openroadie** [comment]
@macd I tried to run openedroad -python and this is what I got:

root@35bcee6f5ff2:/store/work/harsh/OpenROAD# ./build/src/openroad -python
OpenROAD a1a6cfdba39fd00ecd439ca0b8158e7fcda4725b 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
[WARNING ORD-0039] .openroad ignored with -python
**[WARNING ORD-0040] cannot open: '-python'**
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

Looking through the code I also see:

```
src/odb/test/unitTestsPython/TestBTerm.py:import opendbpy as odb
src/odb/test/unitTestsPython/TestBlock.py:import opendbpy as odb
src/odb/test/unitTestsPython/TestDestroy.py:import opendbpy as odb
src/odb/test/unitTestsPython/TestGroup.py:import opendbpy as odb
src/odb/test/unitTestsPython/TestITerm.py:import opendbpy as odb
src/odb/test/unitTestsPython/TestInst.py:import opendbpy as odb
src/odb/test/unitTestsPython/TestModule.py:import opendbpy as odb
src/odb/test/unitTestsPython/TestNet.py:import opendbpy as odb
grep: src/pad/test/caravel_sky130/lef: Is a directory
grep: src/pad/test/caravel_sky130/lib: Is a directory
src/odb/test/unitTestsPython/TestWireCodec.py:import opendbpy as odb
src/odb/test/unitTestsPython/helper.py:import opendbpy as odb

```
I could definitely use some help on how to see the problem you are describing.

**Comment by maliberty** [comment]
[WARNING ORD-0040] looks to be surprious.  @proppy is this due to your recent change?

You should be at the OR prompt with a python interpreter.

**Comment by macd** [comment]
Hmm, is there a separate OR prompt? I haven't seen that but I have seen the ORD-0040 error, but just discounted it. I usually just get the Python prompt. This is what I see on then trying to import odbpy

```
OpenROAD v2.0-5310-g2680091f3 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
[WARNING ORD-0039] .openroad ignored with -python
[WARNING ORD-0040] cannot open: '-python'
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import odbpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'odbpy'
```
However, importing odb works just fine here.

**Pull request merged**
