### PR TITLE
gui: timing report based on slack histogram

### LINKED ISSUE #4633: Add feature to click on bucket in slack endpoint histogram to navigate to timing report
### Description

It would be nice to be able to click in the endpoint slack histogram and read in those endpoints in the timing report:

image

### Suggested Solution

Click in endpoint histogram, read in those end points in the timing report.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by AcKoucher**
Resolve #4633

### CODE REVIEW

**Comment by AcKoucher** [comment]
@oharboe Would you test if the changes here cover what you ask?

**Comment by oharboe** [comment]
Nice!

It is hard to hit the columns to the left. Can you modify the mouse clicck check so that it gets a hit for the entire vertical height, even if there are few samples?

image

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
please resolve the conflict

**Comment by AcKoucher** [comment]
Done

**Pull request merged**
