### PR TITLE
Support Ubuntu 23.04++

### PR DESCRIPTION
**Pull request by pettermk**
A few adjustments necessary to accommodate development on newer Ubuntu versions

### CODE REVIEW

**Review by oharboe — APPROVED** [review]
LGTM

**Comment by oharboe** [comment]
@vvbandeira @maliberty Unrelated failures, as far as I can see:

```
15.53 Complete!
15.71 Loaded plugins: fastestmirror, ovl
16.13 Cannot open: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm. Skipping.
16.13 Error: Nothing to do
```

**Comment by luarss** [comment]
@vvbandeira Should I update the tutorials for ORFS pending this pr?

**Comment by oharboe** [comment]
> @vvbandeira Should I update the tutorials for ORFS pending this pr?

My opinion is no: if you use ubuntu 23.04, then you are on your own, it is not an official longterm release of ubuntu.

**Review by vvbandeira — APPROVED** [review]

**Comment by vvbandeira** [comment]
> > @vvbandeira Should I update the tutorials for ORFS pending this pr?
> 
> My opinion is no: if you use ubuntu 23.04, then you are on your own, it is not an official longterm release of ubuntu.

No need @luarss, thanks for the offer, but I agree with Oyvind

**Pull request merged**
