### PR TITLE
metrics: fix timing metrics

### PR DESCRIPTION
**Pull request by gadfort**
Replaces: #2752

### CODE REVIEW

**Comment by gadfort** [comment]
@maliberty @ravi-varadarajan FYI. This does not address the unit inconsistency... though

**Comment by maliberty** [comment]
I don't see this addressing skew

**Comment by maliberty** [comment]
I've closed my PR

**Comment by gadfort** [comment]
@maliberty while the comment says it fixes skew, skew was already correct (just a typo on my part): https://github.com/The-OpenROAD-Project/OpenSTA/blob/6b8ab8aa9cc04da5a657354e25137955e4d8f38d/tcl/Search.tcl#L1030

**Comment by gadfort** [comment]
Basically, here it just switches to using the opensta commands directly (and adds the worst negative slack which was missing for SC).
I still don't know what to do with power... (and any others that might be there)

**Review by maliberty — APPROVED** [review]

**Comment by ravi-varadarajan** [comment]
Thanks.. I verified the timing unit fix. I had opened a branch for this
issue, I will fix the Power units in the metrics file in the merge of that
branch.

thanks
-ravi

**Pull request merged**
