### PR TITLE
Add the latest codes of Hier-RTLMP

### PR DESCRIPTION
**Pull request by ZhiangWang033**
(1)  update the default parameters in Hier-RTLMP
(2) disable the bus synthesis
(3) disable CP-SAT due to the no response for some testcases.

### CODE REVIEW

**Comment by QuantamHD** [comment]
@ZhiangWang033 Could you rebase your changes to master. @vvbandeira and I have just fixed the clang-tidy-review action

**Comment by ZhiangWang033** [comment]
Done.

**Comment by QuantamHD** [comment]
Thanks!

**Comment by maliberty** [comment]
Replaced by #3288 3288

**Pull request closed without merging**
