### PR TITLE
Update to latest OpenSTA 

### PR DESCRIPTION
**Pull request by openroadie**
Latest OpenSTA code + regression ok file update. PSM and RSZ regressions are passing

### CODE REVIEW

**Comment by openroadie** [comment]
@maliberty @vvbandeira : All my commits are signed off as far as I can tell. So why is DCO failing here?

**Comment by maliberty** [comment]
Your last two are unsigned.

**Review by maliberty — APPROVED** [review]

**Comment by maliberty** [comment]
I waived the DCO but please remember it in the future.  I just use a git alias "ci = commit -s" to avoid thinking about it.

**Comment by openroadie** [comment]
Thanks @maliberty. Much appreciated. Aliasing is done :).

**Pull request merged**
