### PR TITLE
drt: Move FIXEDSHAPECOST and MARKERDECAY into SearchRepairArgs 

### PR DESCRIPTION
**Pull request by antonblanchard**
FIXEDSHAPECOST and MARKERDECAY change based on the iteration, so move
them into SearchRepairArgs where all other per iteration variables are
set.

Signed-off-by: Anton Blanchard <anton@linux.ibm.com>

### CODE REVIEW

**Comment by antonblanchard** [comment]
I noticed this when scanning through drt. It seems preferable to me that all iteration dependent settings are in the one place.

**Comment by antonblanchard** [comment]
SearchRepairArgs is pretty horribly formatted by clang-format

**Comment by maliberty** [comment]
> SearchRepairArgs is pretty horribly formatted by clang-format

I agree.  Perhaps the /* 8 */ could be moved to the end of line // 8 to save a few characters (or dropped).  Another option is to turn off formatting locally and manually format the lines allowing them to be extra long.

**Comment by antonblanchard** [comment]
> > SearchRepairArgs is pretty horribly formatted by clang-format
> 
> I agree. Perhaps the /* 8 */ could be moved to the end of line // 8 to save a few characters (or dropped). Another option is to turn off formatting locally and manually format the lines allowing them to be extra long.

I did both of these, but also aligned the columns so hopefully it makes it easier to read.

**Pull request merged**
